create or replace procedure insert_violations(ASSET_IDS ARRAY)
  returns boolean
  language javascript
  EXECUTE AS CALLER
  as     
  $$
    
var assets = "'" + ASSET_IDS.join("','") + "'";
var useSchema = snowflake.execute({sqlText: 'use schema %ENV%_DDEX_DSR.VALIDATION_AVP_MRB_10'});


var insertViolations_HEAD = snowflake.execute({sqlText: `INSERT INTO VIOLATION (
  ASSET_ID,
  ASSET_PART,
  VIOLATION,
  VIOLATION_DETAIL
) 
WITH
v as (SELECT
  ASSET_ID,
  LINE_INDEX,
  'HEAD' as RECORD_TYPE,
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('HEAD'), null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(MESSAGE_VERSION is not null AND ARRAY_SIZE(MESSAGE_VERSION) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'MESSAGE_VERSION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', MESSAGE_VERSION, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(MESSAGE_VERSION is null OR ARRAY_SIZE(MESSAGE_VERSION) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'MESSAGE_VERSION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', MESSAGE_VERSION, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(MESSAGE_VERSION[0] is null, null, IFF(MESSAGE_VERSION[0]::string REGEXP 'dsrf(\\/30|(\\/\\\\d+(\\.\\\\d+){0,2}){3})', null, OBJECT_CONSTRUCT('FIELD', 'MESSAGE_VERSION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', MESSAGE_VERSION, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(PROFILE is not null AND ARRAY_SIZE(PROFILE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'PROFILE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', PROFILE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(PROFILE is null OR ARRAY_SIZE(PROFILE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'PROFILE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', PROFILE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(PROFILE[0] is null, null, IFF(PROFILE[0]::string REGEXP 'Audio\\\\s*Visual\\\\s*Profile', null, OBJECT_CONSTRUCT('FIELD', 'PROFILE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', PROFILE, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(PROFILE_VERSION is not null AND ARRAY_SIZE(PROFILE_VERSION) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'PROFILE_VERSION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', PROFILE_VERSION, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(PROFILE_VERSION is null OR ARRAY_SIZE(PROFILE_VERSION) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'PROFILE_VERSION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', PROFILE_VERSION, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(PROFILE_VERSION[0] is null, null, IFF(PROFILE_VERSION[0]::string IN ('1.0'), null, OBJECT_CONSTRUCT('FIELD', 'PROFILE_VERSION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', PROFILE_VERSION, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(MESSAGE_ID is not null AND ARRAY_SIZE(MESSAGE_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'MESSAGE_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', MESSAGE_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(MESSAGE_ID is null OR ARRAY_SIZE(MESSAGE_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'MESSAGE_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', MESSAGE_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(MESSAGE_CREATED_DATE_TIME is not null AND ARRAY_SIZE(MESSAGE_CREATED_DATE_TIME) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'MESSAGE_CREATED_DATE_TIME', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', MESSAGE_CREATED_DATE_TIME, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(MESSAGE_CREATED_DATE_TIME is null OR ARRAY_SIZE(MESSAGE_CREATED_DATE_TIME) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'MESSAGE_CREATED_DATE_TIME', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', MESSAGE_CREATED_DATE_TIME, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(MESSAGE_CREATED_DATE_TIME[0] is null, null, 
      IFF(TRY_TO_TIMESTAMP(MESSAGE_CREATED_DATE_TIME[0]::string, 'YYYY-MM-DDTHH24:MI:SSZ') is not null, null, OBJECT_CONSTRUCT('FIELD', 'MESSAGE_CREATED_DATE_TIME', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', MESSAGE_CREATED_DATE_TIME, 'VIOLATION_TYPE', 'NOT_DATETIME'))),
    IFF(FILE_NUMBER is not null AND ARRAY_SIZE(FILE_NUMBER) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'FILE_NUMBER', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', FILE_NUMBER, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(FILE_NUMBER is null OR ARRAY_SIZE(FILE_NUMBER) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'FILE_NUMBER', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', FILE_NUMBER, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(FILE_NUMBER[0] is null, null, IFF(FILE_NUMBER[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'FILE_NUMBER', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', FILE_NUMBER, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(NUMBER_OF_FILES is not null AND ARRAY_SIZE(NUMBER_OF_FILES) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_FILES', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', NUMBER_OF_FILES, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(NUMBER_OF_FILES is null OR ARRAY_SIZE(NUMBER_OF_FILES) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_FILES', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', NUMBER_OF_FILES, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(NUMBER_OF_FILES[0] is null, null, IFF(NUMBER_OF_FILES[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_FILES', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', NUMBER_OF_FILES, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(USAGE_START_DATE is not null AND ARRAY_SIZE(USAGE_START_DATE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'USAGE_START_DATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', USAGE_START_DATE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(USAGE_START_DATE is null OR ARRAY_SIZE(USAGE_START_DATE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'USAGE_START_DATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', USAGE_START_DATE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(USAGE_START_DATE[0] is null, null, 
      IFF(TRY_TO_DATE(USAGE_START_DATE[0]::string, 'YYYY-MM-DD') is not null, null, 
      IFF(TRY_TO_DATE(USAGE_START_DATE[0]::string, 'YYYY-MM') is not null, null, 
      IFF(TRY_TO_DATE(USAGE_START_DATE[0]::string, 'YYYY') is not null, null, OBJECT_CONSTRUCT('FIELD', 'USAGE_START_DATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', USAGE_START_DATE, 'VIOLATION_TYPE', 'NOT_DATE'))))),
    IFF(USAGE_END_DATE is not null AND ARRAY_SIZE(USAGE_END_DATE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'USAGE_END_DATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', USAGE_END_DATE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(USAGE_END_DATE is null OR ARRAY_SIZE(USAGE_END_DATE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'USAGE_END_DATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', USAGE_END_DATE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(USAGE_END_DATE[0] is null, null, 
      IFF(TRY_TO_DATE(USAGE_END_DATE[0]::string, 'YYYY-MM-DD') is not null, null, 
      IFF(TRY_TO_DATE(USAGE_END_DATE[0]::string, 'YYYY-MM') is not null, null, 
      IFF(TRY_TO_DATE(USAGE_END_DATE[0]::string, 'YYYY') is not null, null, OBJECT_CONSTRUCT('FIELD', 'USAGE_END_DATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', USAGE_END_DATE, 'VIOLATION_TYPE', 'NOT_DATE'))))),
    IFF(SENDER_PARTY_ID is not null AND ARRAY_SIZE(SENDER_PARTY_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'SENDER_PARTY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', SENDER_PARTY_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(SENDER_PARTY_ID is null OR ARRAY_SIZE(SENDER_PARTY_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SENDER_PARTY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', SENDER_PARTY_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SENDER_PARTY_ID[0] is null, null, IFF(SENDER_PARTY_ID[0]::string REGEXP 'PADPIDA[0-9A-Za-z]{11}', null, OBJECT_CONSTRUCT('FIELD', 'SENDER_PARTY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', SENDER_PARTY_ID, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(SENDER_NAME is not null AND ARRAY_SIZE(SENDER_NAME) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'SENDER_NAME', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', SENDER_NAME, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(SENDER_NAME is null OR ARRAY_SIZE(SENDER_NAME) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SENDER_NAME', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', SENDER_NAME, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SERVICE_DESCRIPTION is null OR ARRAY_SIZE(SERVICE_DESCRIPTION) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SERVICE_DESCRIPTION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', SERVICE_DESCRIPTION, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECIPIENT_PARTY_ID is null OR ARRAY_SIZE(RECIPIENT_PARTY_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECIPIENT_PARTY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', RECIPIENT_PARTY_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECIPIENT_PARTY_ID[0] is null, null, IFF(RECIPIENT_PARTY_ID[0]::string REGEXP 'PADPIDA[0-9A-Za-z]{11}', null, OBJECT_CONSTRUCT('FIELD', 'RECIPIENT_PARTY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', RECIPIENT_PARTY_ID, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(RECIPIENT_NAME is null OR ARRAY_SIZE(RECIPIENT_NAME) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECIPIENT_NAME', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', RECIPIENT_NAME, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS'))
  ) as VIOLATION_DETAILS
from %ENV%_DDEX_DSR.UNTYPED_AVP_MRB_10.HEAD
where asset_id in (${assets}))
select asset_id, line_index::varchar as asset_part, concat_ws('::', RECORD_TYPE, GET_PATH(value, 'FIELD')::varchar, GET_PATH(value, 'VIOLATION_TYPE')::varchar) violation, value as violation_details from v, table(flatten(input => v.VIOLATION_DETAILS));`});


var insertViolations_FOOT = snowflake.execute({sqlText: `INSERT INTO VIOLATION (
  ASSET_ID,
  ASSET_PART,
  VIOLATION,
  VIOLATION_DETAIL
) 
WITH
v as (SELECT
  ASSET_ID,
  LINE_INDEX,
  'FOOT' as RECORD_TYPE,
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('FOOT'), null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(NUMBER_OF_LINES_IN_FILE is not null AND ARRAY_SIZE(NUMBER_OF_LINES_IN_FILE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_LINES_IN_FILE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_LINES_IN_FILE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(NUMBER_OF_LINES_IN_FILE is null OR ARRAY_SIZE(NUMBER_OF_LINES_IN_FILE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_LINES_IN_FILE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_LINES_IN_FILE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(NUMBER_OF_LINES_IN_FILE[0] is null, null, IFF(NUMBER_OF_LINES_IN_FILE[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_LINES_IN_FILE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_LINES_IN_FILE, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(NUMBER_OF_LINES_IN_REPORT is null OR ARRAY_SIZE(NUMBER_OF_LINES_IN_REPORT) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_LINES_IN_REPORT', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_LINES_IN_REPORT, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(NUMBER_OF_LINES_IN_REPORT[0] is null, null, IFF(NUMBER_OF_LINES_IN_REPORT[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_LINES_IN_REPORT', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_LINES_IN_REPORT, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(NUMBER_OF_SUMMARY_RECORDS is not null AND ARRAY_SIZE(NUMBER_OF_SUMMARY_RECORDS) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_SUMMARY_RECORDS', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_SUMMARY_RECORDS, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(NUMBER_OF_SUMMARY_RECORDS is null OR ARRAY_SIZE(NUMBER_OF_SUMMARY_RECORDS) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_SUMMARY_RECORDS', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_SUMMARY_RECORDS, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(NUMBER_OF_SUMMARY_RECORDS[0] is null, null, IFF(NUMBER_OF_SUMMARY_RECORDS[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_SUMMARY_RECORDS', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_SUMMARY_RECORDS, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(NUMBER_OF_BLOCKS_IN_FILE is not null AND ARRAY_SIZE(NUMBER_OF_BLOCKS_IN_FILE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_BLOCKS_IN_FILE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_BLOCKS_IN_FILE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(NUMBER_OF_BLOCKS_IN_FILE is null OR ARRAY_SIZE(NUMBER_OF_BLOCKS_IN_FILE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_BLOCKS_IN_FILE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_BLOCKS_IN_FILE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(NUMBER_OF_BLOCKS_IN_FILE[0] is null, null, IFF(NUMBER_OF_BLOCKS_IN_FILE[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_BLOCKS_IN_FILE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_BLOCKS_IN_FILE, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(NUMBER_OF_BLOCKS_IN_REPORT is null OR ARRAY_SIZE(NUMBER_OF_BLOCKS_IN_REPORT) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_BLOCKS_IN_REPORT', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_BLOCKS_IN_REPORT, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(NUMBER_OF_BLOCKS_IN_REPORT[0] is null, null, IFF(NUMBER_OF_BLOCKS_IN_REPORT[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_BLOCKS_IN_REPORT', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_BLOCKS_IN_REPORT, 'VIOLATION_TYPE', 'NOT_INTEGER')))
  ) as VIOLATION_DETAILS
from %ENV%_DDEX_DSR.UNTYPED_AVP_MRB_10.FOOT
where asset_id in (${assets}))
select asset_id, line_index::varchar as asset_part, concat_ws('::', RECORD_TYPE, GET_PATH(value, 'FIELD')::varchar, GET_PATH(value, 'VIOLATION_TYPE')::varchar) violation, value as violation_details from v, table(flatten(input => v.VIOLATION_DETAILS));`});


var insertViolations_SY04_01 = snowflake.execute({sqlText: `INSERT INTO VIOLATION (
  ASSET_ID,
  ASSET_PART,
  VIOLATION,
  VIOLATION_DETAIL
) 
WITH
v as (SELECT
  ASSET_ID,
  LINE_INDEX,
  'SY04.01' as RECORD_TYPE,
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('SY04.01'), null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(SUMMARY_RECORD_ID is not null AND ARRAY_SIZE(SUMMARY_RECORD_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUMMARY_RECORD_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', SUMMARY_RECORD_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(SUMMARY_RECORD_ID is null OR ARRAY_SIZE(SUMMARY_RECORD_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUMMARY_RECORD_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', SUMMARY_RECORD_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISTRIBUTION_CHANNEL is null OR ARRAY_SIZE(DISTRIBUTION_CHANNEL) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DISTRIBUTION_CHANNEL', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', DISTRIBUTION_CHANNEL, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISTRIBUTION_CHANNEL_DPID is null OR ARRAY_SIZE(DISTRIBUTION_CHANNEL_DPID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DISTRIBUTION_CHANNEL_DPID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', DISTRIBUTION_CHANNEL_DPID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISTRIBUTION_CHANNEL_DPID[0] is null, null, IFF(DISTRIBUTION_CHANNEL_DPID[0]::string REGEXP 'PADPIDA[0-9A-Za-z]{11}', null, OBJECT_CONSTRUCT('FIELD', 'DISTRIBUTION_CHANNEL_DPID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', DISTRIBUTION_CHANNEL_DPID, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(COMMERCIAL_MODEL is not null AND ARRAY_SIZE(COMMERCIAL_MODEL) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'COMMERCIAL_MODEL', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', COMMERCIAL_MODEL, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(COMMERCIAL_MODEL is null OR ARRAY_SIZE(COMMERCIAL_MODEL) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'COMMERCIAL_MODEL', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', COMMERCIAL_MODEL, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(COMMERCIAL_MODEL[0] is null, null, IFF(is_commercial_model(COMMERCIAL_MODEL[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'COMMERCIAL_MODEL', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', COMMERCIAL_MODEL, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(USE_TYPE is null OR ARRAY_SIZE(USE_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'USE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', USE_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(USE_TYPE[0] is null, null, IFF(is_use_type(USE_TYPE[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'USE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', USE_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(TERRITORY is not null AND ARRAY_SIZE(TERRITORY) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'TERRITORY', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', TERRITORY, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(TERRITORY is null OR ARRAY_SIZE(TERRITORY) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'TERRITORY', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', TERRITORY, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(TERRITORY[0] is null, null, IFF(is_territory(TERRITORY[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'TERRITORY', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', TERRITORY, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(SERVICE_DESCRIPTION is not null AND ARRAY_SIZE(SERVICE_DESCRIPTION) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'SERVICE_DESCRIPTION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', SERVICE_DESCRIPTION, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(SERVICE_DESCRIPTION is null OR ARRAY_SIZE(SERVICE_DESCRIPTION) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SERVICE_DESCRIPTION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', SERVICE_DESCRIPTION, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SUBSCRIBER_TYPE is not null AND ARRAY_SIZE(SUBSCRIBER_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUBSCRIBER_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', SUBSCRIBER_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(SUBSCRIBER_TYPE is null OR ARRAY_SIZE(SUBSCRIBER_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUBSCRIBER_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', SUBSCRIBER_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SUBSCRIBERS is not null AND ARRAY_SIZE(SUBSCRIBERS) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUBSCRIBERS', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', SUBSCRIBERS, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(SUBSCRIBERS is null OR ARRAY_SIZE(SUBSCRIBERS) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUBSCRIBERS', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', SUBSCRIBERS, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SUBSCRIBERS[0] is null, null, IFF(SUBSCRIBERS[0]::string REGEXP '\\\\d+(\\.\\\\d+)?', null, OBJECT_CONSTRUCT('FIELD', 'SUBSCRIBERS', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', SUBSCRIBERS, 'VIOLATION_TYPE', 'NOT_DECIMAL'))),
    IFF(SUB_PERIOD_START_DATE is null OR ARRAY_SIZE(SUB_PERIOD_START_DATE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUB_PERIOD_START_DATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', SUB_PERIOD_START_DATE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SUB_PERIOD_START_DATE[0] is null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_START_DATE[0]::string, 'YYYY-MM-DD') is not null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_START_DATE[0]::string, 'YYYY-MM') is not null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_START_DATE[0]::string, 'YYYY') is not null, null, OBJECT_CONSTRUCT('FIELD', 'SUB_PERIOD_START_DATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', SUB_PERIOD_START_DATE, 'VIOLATION_TYPE', 'NOT_DATE'))))),
    IFF(SUB_PERIOD_END_DATE is null OR ARRAY_SIZE(SUB_PERIOD_END_DATE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUB_PERIOD_END_DATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', SUB_PERIOD_END_DATE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SUB_PERIOD_END_DATE[0] is null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_END_DATE[0]::string, 'YYYY-MM-DD') is not null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_END_DATE[0]::string, 'YYYY-MM') is not null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_END_DATE[0]::string, 'YYYY') is not null, null, OBJECT_CONSTRUCT('FIELD', 'SUB_PERIOD_END_DATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', SUB_PERIOD_END_DATE, 'VIOLATION_TYPE', 'NOT_DATE'))))),
    IFF(USAGES_IN_SUB_PERIOD is null OR ARRAY_SIZE(USAGES_IN_SUB_PERIOD) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'USAGES_IN_SUB_PERIOD', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', USAGES_IN_SUB_PERIOD, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(USAGES_IN_SUB_PERIOD[0] is null, null, IFF(USAGES_IN_SUB_PERIOD[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'USAGES_IN_SUB_PERIOD', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', USAGES_IN_SUB_PERIOD, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(USAGES_IN_REPORTING_PERIOD is null OR ARRAY_SIZE(USAGES_IN_REPORTING_PERIOD) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'USAGES_IN_REPORTING_PERIOD', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', USAGES_IN_REPORTING_PERIOD, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(USAGES_IN_REPORTING_PERIOD[0] is null, null, IFF(USAGES_IN_REPORTING_PERIOD[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'USAGES_IN_REPORTING_PERIOD', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', USAGES_IN_REPORTING_PERIOD, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(CURRENCY_OF_REPORTING is not null AND ARRAY_SIZE(CURRENCY_OF_REPORTING) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'CURRENCY_OF_REPORTING', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', CURRENCY_OF_REPORTING, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(CURRENCY_OF_REPORTING is null OR ARRAY_SIZE(CURRENCY_OF_REPORTING) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'CURRENCY_OF_REPORTING', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', CURRENCY_OF_REPORTING, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(CURRENCY_OF_REPORTING[0] is null, null, IFF(is_currency(CURRENCY_OF_REPORTING[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'CURRENCY_OF_REPORTING', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', CURRENCY_OF_REPORTING, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(CURRENCY_OF_TRANSACTION is null OR ARRAY_SIZE(CURRENCY_OF_TRANSACTION) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'CURRENCY_OF_TRANSACTION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', CURRENCY_OF_TRANSACTION, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(CURRENCY_OF_TRANSACTION[0] is null, null, IFF(is_currency(CURRENCY_OF_TRANSACTION[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'CURRENCY_OF_TRANSACTION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', CURRENCY_OF_TRANSACTION, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(EXCHANGE_RATE is null OR ARRAY_SIZE(EXCHANGE_RATE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'EXCHANGE_RATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', EXCHANGE_RATE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(EXCHANGE_RATE[0] is null, null, IFF(EXCHANGE_RATE[0]::string REGEXP '\\\\d+(\\.\\\\d+)?', null, OBJECT_CONSTRUCT('FIELD', 'EXCHANGE_RATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', EXCHANGE_RATE, 'VIOLATION_TYPE', 'NOT_DECIMAL'))),
    IFF(CONSUMER_PAID_UNIT_PRICE is not null AND ARRAY_SIZE(CONSUMER_PAID_UNIT_PRICE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'CONSUMER_PAID_UNIT_PRICE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', CONSUMER_PAID_UNIT_PRICE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(CONSUMER_PAID_UNIT_PRICE is null OR ARRAY_SIZE(CONSUMER_PAID_UNIT_PRICE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'CONSUMER_PAID_UNIT_PRICE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', CONSUMER_PAID_UNIT_PRICE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(CONSUMER_PAID_UNIT_PRICE[0] is null, null, IFF(CONSUMER_PAID_UNIT_PRICE[0]::string REGEXP '\\\\d+(\\.\\\\d+)?', null, OBJECT_CONSTRUCT('FIELD', 'CONSUMER_PAID_UNIT_PRICE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', CONSUMER_PAID_UNIT_PRICE, 'VIOLATION_TYPE', 'NOT_DECIMAL'))),
    IFF(NET_REVENUE is not null AND ARRAY_SIZE(NET_REVENUE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'NET_REVENUE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', NET_REVENUE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(NET_REVENUE is null OR ARRAY_SIZE(NET_REVENUE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'NET_REVENUE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', NET_REVENUE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(NET_REVENUE[0] is null, null, IFF(NET_REVENUE[0]::string REGEXP '\\\\d+(\\.\\\\d+)?', null, OBJECT_CONSTRUCT('FIELD', 'NET_REVENUE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', NET_REVENUE, 'VIOLATION_TYPE', 'NOT_DECIMAL'))),
    IFF(MUSIC_USAGE_PERCENTAGE is not null AND ARRAY_SIZE(MUSIC_USAGE_PERCENTAGE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'MUSIC_USAGE_PERCENTAGE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', MUSIC_USAGE_PERCENTAGE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(MUSIC_USAGE_PERCENTAGE is null OR ARRAY_SIZE(MUSIC_USAGE_PERCENTAGE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'MUSIC_USAGE_PERCENTAGE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', MUSIC_USAGE_PERCENTAGE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(MUSIC_USAGE_PERCENTAGE[0] is null, null, IFF(MUSIC_USAGE_PERCENTAGE[0]::string REGEXP '\\\\d+(\\.\\\\d+)?', null, OBJECT_CONSTRUCT('FIELD', 'MUSIC_USAGE_PERCENTAGE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', MUSIC_USAGE_PERCENTAGE, 'VIOLATION_TYPE', 'NOT_DECIMAL'))),
    IFF(MUSIC_USAGE_PERCENTAGE[0] is null, null, IFF(MUSIC_USAGE_PERCENTAGE[0]::number <= 100, null, OBJECT_CONSTRUCT('FIELD', 'MUSIC_USAGE_PERCENTAGE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04.01', 'FIELD_VALUE', MUSIC_USAGE_PERCENTAGE, 'VIOLATION_TYPE', 'GREATER_THAN_MAX_SIZE')))
  ) as VIOLATION_DETAILS
from %ENV%_DDEX_DSR.UNTYPED_AVP_MRB_10.SY04_01
where asset_id in (${assets}))
select asset_id, line_index::varchar as asset_part, concat_ws('::', RECORD_TYPE, GET_PATH(value, 'FIELD')::varchar, GET_PATH(value, 'VIOLATION_TYPE')::varchar) violation, value as violation_details from v, table(flatten(input => v.VIOLATION_DETAILS));`});


var insertViolations_RE03 = snowflake.execute({sqlText: `INSERT INTO VIOLATION (
  ASSET_ID,
  ASSET_PART,
  VIOLATION,
  VIOLATION_DETAIL
) 
WITH
v as (SELECT
  ASSET_ID,
  LINE_INDEX,
  'RE03' as RECORD_TYPE,
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE03', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE03', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('RE03'), null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE03', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(BLOCK_ID is not null AND ARRAY_SIZE(BLOCK_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'BLOCK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE03', 'FIELD_VALUE', BLOCK_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(BLOCK_ID is null OR ARRAY_SIZE(BLOCK_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'BLOCK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE03', 'FIELD_VALUE', BLOCK_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RELEASE_REFERENCE is not null AND ARRAY_SIZE(RELEASE_REFERENCE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RELEASE_REFERENCE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE03', 'FIELD_VALUE', RELEASE_REFERENCE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RELEASE_REFERENCE is null OR ARRAY_SIZE(RELEASE_REFERENCE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RELEASE_REFERENCE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE03', 'FIELD_VALUE', RELEASE_REFERENCE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DSP_RELEASE_ID is not null AND ARRAY_SIZE(DSP_RELEASE_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'DSP_RELEASE_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE03', 'FIELD_VALUE', DSP_RELEASE_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(DSP_RELEASE_ID is null OR ARRAY_SIZE(DSP_RELEASE_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DSP_RELEASE_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE03', 'FIELD_VALUE', DSP_RELEASE_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(ICPN is null OR ARRAY_SIZE(ICPN) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'ICPN', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE03', 'FIELD_VALUE', ICPN, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(TITLE is not null AND ARRAY_SIZE(TITLE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'TITLE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE03', 'FIELD_VALUE', TITLE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(TITLE is null OR ARRAY_SIZE(TITLE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'TITLE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE03', 'FIELD_VALUE', TITLE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SUB_TITLE is null OR ARRAY_SIZE(SUB_TITLE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUB_TITLE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE03', 'FIELD_VALUE', SUB_TITLE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SERIES_TITLE is null OR ARRAY_SIZE(SERIES_TITLE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SERIES_TITLE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE03', 'FIELD_VALUE', SERIES_TITLE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SEASON_NUMBER is null OR ARRAY_SIZE(SEASON_NUMBER) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SEASON_NUMBER', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE03', 'FIELD_VALUE', SEASON_NUMBER, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SEASON_NUMBER[0] is null, null, IFF(SEASON_NUMBER[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'SEASON_NUMBER', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE03', 'FIELD_VALUE', SEASON_NUMBER, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(DISPLAY_ARTIST_NAME is null OR ARRAY_SIZE(DISPLAY_ARTIST_NAME) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DISPLAY_ARTIST_NAME', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE03', 'FIELD_VALUE', DISPLAY_ARTIST_NAME, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISPLAY_ARTIST_PARTY_ID is null OR ARRAY_SIZE(DISPLAY_ARTIST_PARTY_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DISPLAY_ARTIST_PARTY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE03', 'FIELD_VALUE', DISPLAY_ARTIST_PARTY_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISPLAY_ARTIST_PARTY_ID[0] is null, null, IFF(DISPLAY_ARTIST_PARTY_ID[0]::string REGEXP 'INSI::\\\\d{16}', null, OBJECT_CONSTRUCT('FIELD', 'DISPLAY_ARTIST_PARTY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE03', 'FIELD_VALUE', DISPLAY_ARTIST_PARTY_ID, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(RELEASE_TYPE is null OR ARRAY_SIZE(RELEASE_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RELEASE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE03', 'FIELD_VALUE', RELEASE_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RELEASE_TYPE[0] is null, null, IFF(is_release_type(RELEASE_TYPE[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'RELEASE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE03', 'FIELD_VALUE', RELEASE_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(DATA_PROVIDER_NAME is null OR ARRAY_SIZE(DATA_PROVIDER_NAME) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DATA_PROVIDER_NAME', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE03', 'FIELD_VALUE', DATA_PROVIDER_NAME, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS'))
  ) as VIOLATION_DETAILS
from %ENV%_DDEX_DSR.UNTYPED_AVP_MRB_10.RE03
where asset_id in (${assets}))
select asset_id, line_index::varchar as asset_part, concat_ws('::', RECORD_TYPE, GET_PATH(value, 'FIELD')::varchar, GET_PATH(value, 'VIOLATION_TYPE')::varchar) violation, value as violation_details from v, table(flatten(input => v.VIOLATION_DETAILS));`});


var insertViolations_AS03 = snowflake.execute({sqlText: `INSERT INTO VIOLATION (
  ASSET_ID,
  ASSET_PART,
  VIOLATION,
  VIOLATION_DETAIL
) 
WITH
v as (SELECT
  ASSET_ID,
  LINE_INDEX,
  'AS03' as RECORD_TYPE,
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('AS03'), null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(BLOCK_ID is not null AND ARRAY_SIZE(BLOCK_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'BLOCK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', BLOCK_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(BLOCK_ID is null OR ARRAY_SIZE(BLOCK_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'BLOCK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', BLOCK_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RESOURCE_REFERENCE is not null AND ARRAY_SIZE(RESOURCE_REFERENCE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RESOURCE_REFERENCE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', RESOURCE_REFERENCE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RESOURCE_REFERENCE is null OR ARRAY_SIZE(RESOURCE_REFERENCE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RESOURCE_REFERENCE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', RESOURCE_REFERENCE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DSP_RESOURCE_ID is not null AND ARRAY_SIZE(DSP_RESOURCE_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'DSP_RESOURCE_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', DSP_RESOURCE_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(DSP_RESOURCE_ID is null OR ARRAY_SIZE(DSP_RESOURCE_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DSP_RESOURCE_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', DSP_RESOURCE_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(ISAN is null OR ARRAY_SIZE(ISAN) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'ISAN', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', ISAN, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(ISAN[0] is null, null, IFF(ISAN[0]::string REGEXP '([0-9A-Fa-f]{4}-?){3}([0-9A-Fa-f]{4}(-?[\\\\w\\\\d])?(-?([0-9A-Fa-f]{4}-?){2}[\\\\w\\\\d]?)?)', null, OBJECT_CONSTRUCT('FIELD', 'ISAN', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', ISAN, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(EIDR is null OR ARRAY_SIZE(EIDR) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'EIDR', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', EIDR, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(EIDR[0] is null, null, IFF(EIDR[0]::string REGEXP '\\\\d{2}\\.\\\\d{4}\\/([0-9A-Fa-f]{4}-?){5}\\\\w', null, OBJECT_CONSTRUCT('FIELD', 'EIDR', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', EIDR, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(PROPRIETARY_ID is null OR ARRAY_SIZE(PROPRIETARY_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'PROPRIETARY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', PROPRIETARY_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(PROPRIETARY_ID[0] is null, null, IFF(PROPRIETARY_ID[0]::string REGEXP '\\.+::\\.+', null, OBJECT_CONSTRUCT('FIELD', 'PROPRIETARY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', PROPRIETARY_ID, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(VIDEO_TYPE is not null AND ARRAY_SIZE(VIDEO_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'VIDEO_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', VIDEO_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(VIDEO_TYPE is null OR ARRAY_SIZE(VIDEO_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'VIDEO_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', VIDEO_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(VIDEO_TYPE[0] is null, null, IFF(is_video_type(VIDEO_TYPE[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'VIDEO_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', VIDEO_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(TITLE is not null AND ARRAY_SIZE(TITLE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'TITLE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', TITLE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(TITLE is null OR ARRAY_SIZE(TITLE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'TITLE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', TITLE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SUB_TITLE is null OR ARRAY_SIZE(SUB_TITLE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUB_TITLE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', SUB_TITLE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(ORIGINAL_TITLE is null OR ARRAY_SIZE(ORIGINAL_TITLE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'ORIGINAL_TITLE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', ORIGINAL_TITLE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SEASON_NUMBER is null OR ARRAY_SIZE(SEASON_NUMBER) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SEASON_NUMBER', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', SEASON_NUMBER, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SEASON_NUMBER[0] is null, null, IFF(SEASON_NUMBER[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'SEASON_NUMBER', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', SEASON_NUMBER, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(EPISODE_NUMBER is null OR ARRAY_SIZE(EPISODE_NUMBER) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'EPISODE_NUMBER', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', EPISODE_NUMBER, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(EPISODE_NUMBER[0] is null, null, IFF(EPISODE_NUMBER[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'EPISODE_NUMBER', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', EPISODE_NUMBER, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(GENRE is null OR ARRAY_SIZE(GENRE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'GENRE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', GENRE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DURATION is not null AND ARRAY_SIZE(DURATION) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'DURATION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', DURATION, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(DURATION is null OR ARRAY_SIZE(DURATION) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DURATION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', DURATION, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DURATION[0] is null, null, IFF(DURATION[0]::string REGEXP 'PT((\\\\d+H)?\\\\d+M)?\\\\d+(\\.\\\\d+)?S', null, OBJECT_CONSTRUCT('FIELD', 'DURATION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', DURATION, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(LANGUAGE_LOCALIZATION_TYPE is null OR ARRAY_SIZE(LANGUAGE_LOCALIZATION_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'LANGUAGE_LOCALIZATION_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', LANGUAGE_LOCALIZATION_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(LANGUAGE_LOCALIZATION_TYPE[0] is null, null, IFF(is_language(LANGUAGE_LOCALIZATION_TYPE[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'LANGUAGE_LOCALIZATION_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', LANGUAGE_LOCALIZATION_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(HAS_CAPTIONING is null OR ARRAY_SIZE(HAS_CAPTIONING) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'HAS_CAPTIONING', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', HAS_CAPTIONING, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(HAS_CAPTIONING[0] is null, null, IFF(RLIKE(HAS_CAPTIONING[0]::string, '(true|false|yes|no|y|n|0|1)', 'i'), null, OBJECT_CONSTRUCT('FIELD', 'HAS_CAPTIONING', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', HAS_CAPTIONING, 'VIOLATION_TYPE', 'NOT_BOOLEAN'))),
    IFF(HAS_AUDIO_DESCRIPTION is null OR ARRAY_SIZE(HAS_AUDIO_DESCRIPTION) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'HAS_AUDIO_DESCRIPTION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', HAS_AUDIO_DESCRIPTION, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(HAS_AUDIO_DESCRIPTION[0] is null, null, IFF(RLIKE(HAS_AUDIO_DESCRIPTION[0]::string, '(true|false|yes|no|y|n|0|1)', 'i'), null, OBJECT_CONSTRUCT('FIELD', 'HAS_AUDIO_DESCRIPTION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', HAS_AUDIO_DESCRIPTION, 'VIOLATION_TYPE', 'NOT_BOOLEAN'))),
    IFF(LANGUAGE_OF_PERFORMANCE is null OR ARRAY_SIZE(LANGUAGE_OF_PERFORMANCE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'LANGUAGE_OF_PERFORMANCE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', LANGUAGE_OF_PERFORMANCE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(LANGUAGE_OF_PERFORMANCE[0] is null, null, IFF(is_language(LANGUAGE_OF_PERFORMANCE[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'LANGUAGE_OF_PERFORMANCE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', LANGUAGE_OF_PERFORMANCE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(LANGUAGE_OF_DUBBING is null OR ARRAY_SIZE(LANGUAGE_OF_DUBBING) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'LANGUAGE_OF_DUBBING', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', LANGUAGE_OF_DUBBING, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(LANGUAGE_OF_DUBBING[0] is null, null, IFF(is_language(LANGUAGE_OF_DUBBING[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'LANGUAGE_OF_DUBBING', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', LANGUAGE_OF_DUBBING, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(PRODUCTION_OR_RELEASE_DATE is null OR ARRAY_SIZE(PRODUCTION_OR_RELEASE_DATE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'PRODUCTION_OR_RELEASE_DATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', PRODUCTION_OR_RELEASE_DATE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(PRODUCTION_OR_RELEASE_DATE[0] is null, null, 
      IFF(TRY_TO_DATE(PRODUCTION_OR_RELEASE_DATE[0]::string, 'YYYY-MM-DD') is not null, null, 
      IFF(TRY_TO_DATE(PRODUCTION_OR_RELEASE_DATE[0]::string, 'YYYY-MM') is not null, null, 
      IFF(TRY_TO_DATE(PRODUCTION_OR_RELEASE_DATE[0]::string, 'YYYY') is not null, null, OBJECT_CONSTRUCT('FIELD', 'PRODUCTION_OR_RELEASE_DATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS03', 'FIELD_VALUE', PRODUCTION_OR_RELEASE_DATE, 'VIOLATION_TYPE', 'NOT_DATE')))))
  ) as VIOLATION_DETAILS
from %ENV%_DDEX_DSR.UNTYPED_AVP_MRB_10.AS03
where asset_id in (${assets}))
select asset_id, line_index::varchar as asset_part, concat_ws('::', RECORD_TYPE, GET_PATH(value, 'FIELD')::varchar, GET_PATH(value, 'VIOLATION_TYPE')::varchar) violation, value as violation_details from v, table(flatten(input => v.VIOLATION_DETAILS));`});


var insertViolations_SU03_01 = snowflake.execute({sqlText: `INSERT INTO VIOLATION (
  ASSET_ID,
  ASSET_PART,
  VIOLATION,
  VIOLATION_DETAIL
) 
WITH
v as (SELECT
  ASSET_ID,
  LINE_INDEX,
  'SU03.01' as RECORD_TYPE,
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU03.01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU03.01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('SU03.01'), null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU03.01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(BLOCK_ID is not null AND ARRAY_SIZE(BLOCK_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'BLOCK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU03.01', 'FIELD_VALUE', BLOCK_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(BLOCK_ID is null OR ARRAY_SIZE(BLOCK_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'BLOCK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU03.01', 'FIELD_VALUE', BLOCK_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SALES_TRANSACTION_ID is not null AND ARRAY_SIZE(SALES_TRANSACTION_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'SALES_TRANSACTION_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU03.01', 'FIELD_VALUE', SALES_TRANSACTION_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(SALES_TRANSACTION_ID is null OR ARRAY_SIZE(SALES_TRANSACTION_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SALES_TRANSACTION_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU03.01', 'FIELD_VALUE', SALES_TRANSACTION_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SUMMARY_RECORD_ID is null OR ARRAY_SIZE(SUMMARY_RECORD_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUMMARY_RECORD_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU03.01', 'FIELD_VALUE', SUMMARY_RECORD_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DSP_RESOURCE_ID is not null AND ARRAY_SIZE(DSP_RESOURCE_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'DSP_RESOURCE_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU03.01', 'FIELD_VALUE', DSP_RESOURCE_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(DSP_RESOURCE_ID is null OR ARRAY_SIZE(DSP_RESOURCE_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DSP_RESOURCE_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU03.01', 'FIELD_VALUE', DSP_RESOURCE_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(USAGES is not null AND ARRAY_SIZE(USAGES) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'USAGES', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU03.01', 'FIELD_VALUE', USAGES, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(USAGES is null OR ARRAY_SIZE(USAGES) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'USAGES', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU03.01', 'FIELD_VALUE', USAGES, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(USAGES[0] is null, null, IFF(USAGES[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'USAGES', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU03.01', 'FIELD_VALUE', USAGES, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(NET_REVENUE is not null AND ARRAY_SIZE(NET_REVENUE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'NET_REVENUE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU03.01', 'FIELD_VALUE', NET_REVENUE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(NET_REVENUE is null OR ARRAY_SIZE(NET_REVENUE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'NET_REVENUE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU03.01', 'FIELD_VALUE', NET_REVENUE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(NET_REVENUE[0] is null, null, IFF(NET_REVENUE[0]::string REGEXP '\\\\d+(\\.\\\\d+)?', null, OBJECT_CONSTRUCT('FIELD', 'NET_REVENUE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU03.01', 'FIELD_VALUE', NET_REVENUE, 'VIOLATION_TYPE', 'NOT_DECIMAL'))),
    IFF(VALIDITY_PERIOD_START is null OR ARRAY_SIZE(VALIDITY_PERIOD_START) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'VALIDITY_PERIOD_START', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU03.01', 'FIELD_VALUE', VALIDITY_PERIOD_START, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(VALIDITY_PERIOD_START[0] is null, null, 
      IFF(TRY_TO_DATE(VALIDITY_PERIOD_START[0]::string, 'YYYY-MM-DD') is not null, null, 
      IFF(TRY_TO_DATE(VALIDITY_PERIOD_START[0]::string, 'YYYY-MM') is not null, null, 
      IFF(TRY_TO_DATE(VALIDITY_PERIOD_START[0]::string, 'YYYY') is not null, null, OBJECT_CONSTRUCT('FIELD', 'VALIDITY_PERIOD_START', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU03.01', 'FIELD_VALUE', VALIDITY_PERIOD_START, 'VIOLATION_TYPE', 'NOT_DATE'))))),
    IFF(VALIDITY_PERIOD_END is null OR ARRAY_SIZE(VALIDITY_PERIOD_END) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'VALIDITY_PERIOD_END', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU03.01', 'FIELD_VALUE', VALIDITY_PERIOD_END, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(VALIDITY_PERIOD_END[0] is null, null, 
      IFF(TRY_TO_DATE(VALIDITY_PERIOD_END[0]::string, 'YYYY-MM-DD') is not null, null, 
      IFF(TRY_TO_DATE(VALIDITY_PERIOD_END[0]::string, 'YYYY-MM') is not null, null, 
      IFF(TRY_TO_DATE(VALIDITY_PERIOD_END[0]::string, 'YYYY') is not null, null, OBJECT_CONSTRUCT('FIELD', 'VALIDITY_PERIOD_END', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU03.01', 'FIELD_VALUE', VALIDITY_PERIOD_END, 'VIOLATION_TYPE', 'NOT_DATE')))))
  ) as VIOLATION_DETAILS
from %ENV%_DDEX_DSR.UNTYPED_AVP_MRB_10.SU03_01
where asset_id in (${assets}))
select asset_id, line_index::varchar as asset_part, concat_ws('::', RECORD_TYPE, GET_PATH(value, 'FIELD')::varchar, GET_PATH(value, 'VIOLATION_TYPE')::varchar) violation, value as violation_details from v, table(flatten(input => v.VIOLATION_DETAILS));`});


  $$
  ;

