use schema VALIDATION_BAP_MRB_12;

create or replace function is_commercial_model(value varchar)
  returns boolean
  as
  $$
    value in (
      'AdvertisementSupportedModel','AsPerContract','DeviceFeeModel','FreeOfChargeModel','PayAsYouGoModel','PerformanceRoyaltiesModel','RightsClaimModel','SubscriptionModel','Unknown','UserDefined'
    )
  $$
  ;


create or replace function is_use_type(value varchar)
  returns boolean
  as
  $$
    value in (
      'AsPerContract','Broadcast','ConditionalDownload','ContentInfluencedStream','Display','Download','DubForAdvertisement','DubForLivePerformance','DubForMovies','DubForMusicOnHold','DubForPublicPerformance','DubForRadio','DubForTV','ExtractForInternet','KioskDownload','Narrowcast','NonInteractiveStream','OnDemandStream','PerformAsMusicOnHold','PerformInLivePerformance','PerformInPublic','PermanentDownload','Playback','PlayInPublic','Podcast','Print','PrivateCopy','ProgrammedContentStream','PurchaseAsPhysicalProduct','Rent','Simulcast','Stream','TetheredDownload','TimeInfluencedStream','Unknown','UseAsAlertTone','UseAsDevice','UseAsKaraoke','UseAsRingbackTone','UseAsRingbackTune','UseAsRingtone','UseAsRingtune','UseAsScreensaver','UseAsVoiceMail','UseAsWallpaper','UseForIdentification','UseInMobilePhoneMessaging','UseInPhoneListening','UserDefined','UserMakeAvailableLabelProvided','UserMakeAvailableUserProvided','Webcast'
    )
  $$
  ;


create or replace function is_territory(value varchar)
  returns boolean
  as
  $$
    value in (
      'AD','AE','AF','AG','AI','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AW','AX','AZ','BA','BB','BD','BE','BF','BG','BH','BI','BJ','BL','BM','BN','BO','BQ','BR','BS','BT','BV','BW','BY','BZ','CA','CC','CD','CF','CG','CH','CI','CK','CL','CM','CN','CO','CR','CS','CU','CV','CW','CX','CY','CZ','DE','DJ','DK','DM','DO','DZ','EC','EE','EG','EH','ER','ES','ES-CE','ES-CN','ES-ML','ET','FI','FJ','FK','FM','FO','FR','GA','GB','GD','GE','GF','GG','GH','GI','GL','GM','GN','GP','GQ','GR','GS','GT','GU','GW','GY','HK','HM','HN','HR','HT','HU','ID','IE','IL','IM','IN','IO','IQ','IR','IS','IT','JE','JM','JO','JP','KE','KG','KH','KI','KM','KN','KP','KR','KW','KY','KZ','LA','LB','LC','LI','LK','LR','LS','LT','LU','LV','LY','MA','MC','MD','ME','MF','MG','MH','MK','ML','MM','MN','MO','MP','MQ','MR','MS','MT','MU','MV','MW','MX','MY','MZ','NA','NC','NE','NF','NG','NI','NL','NO','NP','NR','NU','NZ','OM','PA','PE','PF','PG','PH','PK','PL','PM','PN','PR','PS','PT','PW','PY','QA','RE','RO','RS','RU','RW','SA','SB','SC','SD','SE','SG','SH','SI','SJ','SK','SL','SM','SN','SO','SR','SS','ST','SV','SX','SY','SZ','TC','TD','TF','TG','TH','TJ','TK','TL','TM','TN','TO','TR','TT','TV','TW','TZ','UA','UG','UM','US','UY','UZ','VA','VC','VE','VG','VI','VN','VU','WF','WS','YE','YT','ZA','ZM','ZW','4','8','12','20','24','28','31','32','36','40','44','48','50','51','52','56','64','68','70','72','76','84','90','96','100','104','108','112','116','120','124','132','140','144','148','152','156','158','170','174','178','180','188','191','192','196','200','203','204','208','212','214','218','222','226','230','231','232','233','242','246','250','258','262','266','268','270','276','278','280','288','296','300','308','320','324','328','332','336','340','344','348','352','356','360','364','368','372','376','380','384','388','392','398','400','404','408','410','414','417','418','422','426','428','430','434','438','440','442','450','454','458','462','466','470','478','480','484','492','496','498','499','504','508','512','516','520','524','528','540','548','554','558','562','566','578','583','584','585','586','591','598','600','604','608','616','620','624','626','630','634','642','643','646','659','662','670','674','678','682','686','688','690','694','702','703','704','705','706','710','716','720','724','728','729','732','736','740','748','752','756','760','762','764','768','776','780','784','788','792','795','798','800','804','807','810','818','826','834','840','854','858','860','862','882','886','887','890','891','894','2100','2101','2102','2103','2104','2105','2106','2107','2108','2109','2110','2111','2112','2113','2114','2115','2116','2117','2118','2119','2120','2121','2122','2123','2124','2125','2126','2127','2128','2129','2130','2131','2132','2133','2134','2136','Worldwide'
    )
  $$
  ;


create or replace function is_currency(value varchar)
  returns boolean
  as
  $$
    value in (
      'AED','AFN','ALL','AMD','ANG','AOA','ARS','AUD','AWG','AZN','BAM','BBD','BDT','BGN','BHD','BIF','BMD','BND','BOB','BOV','BRL','BSD','BTN','BWP','BYR','BZD','CAD','CDF','CHF','CLF','CLP','CNY','COP','COU','CRC','CUC','CUP','CVE','CZK','DJF','DKK','DOP','DZD','EGP','ERN','ETB','EUR','FJD','FKP','GBP','GEL','GHS','GIP','GMD','GNF','GTQ','GYD','HKD','HNL','HRK','HTG','HUF','IDR','ILS','INR','IQD','IRR','ISK','JMD','JOD','JPY','KES','KGS','KHR','KMF','KPW','KRW','KWD','KYD','KZT','LAK','LBP','LKR','LRD','LSL','LYD','MAD','MDL','MGA','MKD','MMK','MNT','MOP','MRU','MUR','MVR','MWK','MXN','MXV','MYR','MZN','NAD','NGN','NIO','NOK','NPR','NZD','OMR','PAB','PEN','PGK','PHP','PKR','PLN','PYG','QAR','RON','RSD','RUB','RWF','SAR','SBD','SCR','SDG','SEK','SGD','SHP','SLL','SOS','SRD','SSP','STN','SVC','SYP','SZL','THB','TJS','TMT','TND','TOP','TRY','TTD','TWD','TZS','UAH','UGX','USD','UYI','UYU','UZS','VES','VND','VUV','WST','XAF','XCD','XOF','XPF','YER','ZAR','ZMW','ZWL','CYP','EEK','LTL','LVL','MTL','MRO','ROL','SIT','SKK','STD','VEF'
    )
  $$
  ;


create or replace function is_right_type(value varchar)
  returns boolean
  as
  $$
    value in (
      'MakeAvailableRight','MechanicalRight','PerformingRight','PrintRight','ReproductionRight','SynchronizationRight','UserDefined'
    )
  $$
  ;


create or replace function is_release_type(value varchar)
  returns boolean
  as
  $$
    value in (
      'AdvertisementVideo','Album','AlertToneRelease','Animation','AsPerContract','AudioBookRelease','AudioClipRelease','BackCoverImageRelease','BookletBackImageRelease','BookletFrontImageRelease','BookletRelease','Bundle','ClassicalAlbum','ConcertVideo','CorporateFilm','DigitalBoxSetRelease','Documentary','DocumentImageRelease','EBookRelease','Episode','FeatureFilm','FilmBundle','FrontCoverImageRelease','IconRelease','InfomercialVideo','InteractiveBookletRelease','KaraokeRelease','LiveEventVideo','LogoRelease','LongFormMusicalWorkVideoRelease','LongFormNonMusicalWorkVideoRelease','LyricSheetRelease','MultimediaAlbum','MultimediaSingle','MusicalWorkBasedGameRelease','MusicalWorkClipRelease','MusicalWorkReadalongVideoRelease','MusicalWorkTrailerRelease','MusicalWorkVideoChapterRelease','News','NonMusicalWorkBasedGameRelease','NonMusicalWorkClipRelease','NonMusicalWorkReadalongVideoRelease','NonMusicalWorkTrailerRelease','NonMusicalWorkVideoChapterRelease','NonSerialAudioVisualRecording','PhotographRelease','RingbackToneRelease','RingtoneRelease','ScreensaverRelease','Season','Series','SheetMusicRelease','ShortFormMusicalWorkVideoRelease','ShortFormNonMusicalWorkVideoRelease','Single','SingleResourceRelease','SingleResourceReleaseWithCoverArt','TrackRelease','TrailerVideo','TrayImageRelease','Unknown','UserDefined','VideoAlbum','VideoChapterRelease','VideoClipRelease','VideoScreenCaptureRelease','VideoSingle','VideoTrackRelease','WallpaperRelease'
    )
  $$
  ;


create or replace function is_resource_type(value varchar)
  returns boolean
  as
  $$
    value in (
      'Image','MIDI','SheetMusic','Software','SoundRecording','Text','UserDefinedResource','Video'
    )
  $$
  ;


CREATE OR REPLACE VIEW HEAD_VALIDATION (
  ASSET_ID,
  LINE_INDEX,
  RECORD_TYPE,
  VIOLATIONS
) AS SELECT
  ASSET_ID,
  LINE_INDEX,
  'HEAD',
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, 'RECORD_TYPE_REQUIRED'),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, 'RECORD_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('HEAD'), null, 'RECORD_TYPE_NOT_ALLOWED_VALUE')),
    IFF(MESSAGE_VERSION is not null AND ARRAY_SIZE(MESSAGE_VERSION) >= 1, null, 'MESSAGE_VERSION_REQUIRED'),
    IFF(MESSAGE_VERSION is null OR ARRAY_SIZE(MESSAGE_VERSION) <= 1, null, 'MESSAGE_VERSION_HAS_MULTIPLE_ITEMS'),
    IFF(MESSAGE_VERSION[0] is null, null, IFF(MESSAGE_VERSION[0]::string REGEXP 'dsrf(\/30|(\/\\d+(\.\\d+){0,2}){3})', null, 'MESSAGE_VERSION_NOT_ALLOWED_PATTERN')),
    IFF(PROFILE is not null AND ARRAY_SIZE(PROFILE) >= 1, null, 'PROFILE_REQUIRED'),
    IFF(PROFILE is null OR ARRAY_SIZE(PROFILE) <= 1, null, 'PROFILE_HAS_MULTIPLE_ITEMS'),
    IFF(PROFILE[0] is null, null, IFF(PROFILE[0]::string REGEXP 'Basic\\s*Audio\\s*Profile', null, 'PROFILE_NOT_ALLOWED_PATTERN')),
    IFF(PROFILE_VERSION is not null AND ARRAY_SIZE(PROFILE_VERSION) >= 1, null, 'PROFILE_VERSION_REQUIRED'),
    IFF(PROFILE_VERSION is null OR ARRAY_SIZE(PROFILE_VERSION) <= 1, null, 'PROFILE_VERSION_HAS_MULTIPLE_ITEMS'),
    IFF(PROFILE_VERSION[0] is null, null, IFF(PROFILE_VERSION[0]::string IN ('1.2'), null, 'PROFILE_VERSION_NOT_ALLOWED_VALUE')),
    IFF(MESSAGE_ID is not null AND ARRAY_SIZE(MESSAGE_ID) >= 1, null, 'MESSAGE_ID_REQUIRED'),
    IFF(MESSAGE_ID is null OR ARRAY_SIZE(MESSAGE_ID) <= 1, null, 'MESSAGE_ID_HAS_MULTIPLE_ITEMS'),
    IFF(MESSAGE_CREATED_DATE_TIME is not null AND ARRAY_SIZE(MESSAGE_CREATED_DATE_TIME) >= 1, null, 'MESSAGE_CREATED_DATE_TIME_REQUIRED'),
    IFF(MESSAGE_CREATED_DATE_TIME is null OR ARRAY_SIZE(MESSAGE_CREATED_DATE_TIME) <= 1, null, 'MESSAGE_CREATED_DATE_TIME_HAS_MULTIPLE_ITEMS'),
    IFF(MESSAGE_CREATED_DATE_TIME[0] is null, null, 
      IFF(TRY_TO_TIMESTAMP(MESSAGE_CREATED_DATE_TIME[0]::string, 'YYYY-MM-DDTHH24:MI:SSZ') is not null, null, 'MESSAGE_CREATED_DATE_TIME_NOT_DATETIME')),
    IFF(FILE_NUMBER is not null AND ARRAY_SIZE(FILE_NUMBER) >= 1, null, 'FILE_NUMBER_REQUIRED'),
    IFF(FILE_NUMBER is null OR ARRAY_SIZE(FILE_NUMBER) <= 1, null, 'FILE_NUMBER_HAS_MULTIPLE_ITEMS'),
    IFF(FILE_NUMBER[0] is null, null, IFF(FILE_NUMBER[0]::string REGEXP '\\d+', null, 'FILE_NUMBER_NOT_INTEGER')),
    IFF(FILE_NUMBER[0] is null, null, IFF(FILE_NUMBER[0]::number >= 1, null, 'FILE_NUMBER_LESS_THAN_MIN_SIZE')),
    IFF(NUMBER_OF_FILES is not null AND ARRAY_SIZE(NUMBER_OF_FILES) >= 1, null, 'NUMBER_OF_FILES_REQUIRED'),
    IFF(NUMBER_OF_FILES is null OR ARRAY_SIZE(NUMBER_OF_FILES) <= 1, null, 'NUMBER_OF_FILES_HAS_MULTIPLE_ITEMS'),
    IFF(NUMBER_OF_FILES[0] is null, null, IFF(NUMBER_OF_FILES[0]::string REGEXP '\\d+', null, 'NUMBER_OF_FILES_NOT_INTEGER')),
    IFF(NUMBER_OF_FILES[0] is null, null, IFF(NUMBER_OF_FILES[0]::number >= 1, null, 'NUMBER_OF_FILES_LESS_THAN_MIN_SIZE')),
    IFF(USAGE_START_DATE is not null AND ARRAY_SIZE(USAGE_START_DATE) >= 1, null, 'USAGE_START_DATE_REQUIRED'),
    IFF(USAGE_START_DATE is null OR ARRAY_SIZE(USAGE_START_DATE) <= 1, null, 'USAGE_START_DATE_HAS_MULTIPLE_ITEMS'),
    IFF(USAGE_START_DATE[0] is null, null, 
      IFF(TRY_TO_DATE(USAGE_START_DATE[0]::string, 'YYYY-MM-DD') is not null, null, 
      IFF(TRY_TO_DATE(USAGE_START_DATE[0]::string, 'YYYY-MM') is not null, null, 
      IFF(TRY_TO_DATE(USAGE_START_DATE[0]::string, 'YYYY') is not null, null, 'USAGE_START_DATE_NOT_DATE')))),
    IFF(USAGE_END_DATE is not null AND ARRAY_SIZE(USAGE_END_DATE) >= 1, null, 'USAGE_END_DATE_REQUIRED'),
    IFF(USAGE_END_DATE is null OR ARRAY_SIZE(USAGE_END_DATE) <= 1, null, 'USAGE_END_DATE_HAS_MULTIPLE_ITEMS'),
    IFF(USAGE_END_DATE[0] is null, null, 
      IFF(TRY_TO_DATE(USAGE_END_DATE[0]::string, 'YYYY-MM-DD') is not null, null, 
      IFF(TRY_TO_DATE(USAGE_END_DATE[0]::string, 'YYYY-MM') is not null, null, 
      IFF(TRY_TO_DATE(USAGE_END_DATE[0]::string, 'YYYY') is not null, null, 'USAGE_END_DATE_NOT_DATE')))),
    IFF(SENDER_PARTY_ID is not null AND ARRAY_SIZE(SENDER_PARTY_ID) >= 1, null, 'SENDER_PARTY_ID_REQUIRED'),
    IFF(SENDER_PARTY_ID is null OR ARRAY_SIZE(SENDER_PARTY_ID) <= 1, null, 'SENDER_PARTY_ID_HAS_MULTIPLE_ITEMS'),
    IFF(SENDER_PARTY_ID[0] is null, null, IFF(SENDER_PARTY_ID[0]::string REGEXP 'PADPIDA[0-9A-Za-z]{11}', null, 'SENDER_PARTY_ID_NOT_ALLOWED_PATTERN')),
    IFF(SENDER_NAME is not null AND ARRAY_SIZE(SENDER_NAME) >= 1, null, 'SENDER_NAME_REQUIRED'),
    IFF(SENDER_NAME is null OR ARRAY_SIZE(SENDER_NAME) <= 1, null, 'SENDER_NAME_HAS_MULTIPLE_ITEMS'),
    IFF(SERVICE_DESCRIPTION is null OR ARRAY_SIZE(SERVICE_DESCRIPTION) <= 1, null, 'SERVICE_DESCRIPTION_HAS_MULTIPLE_ITEMS'),
    IFF(RECIPIENT_PARTY_ID is null OR ARRAY_SIZE(RECIPIENT_PARTY_ID) <= 1, null, 'RECIPIENT_PARTY_ID_HAS_MULTIPLE_ITEMS'),
    IFF(RECIPIENT_PARTY_ID[0] is null, null, IFF(RECIPIENT_PARTY_ID[0]::string REGEXP 'PADPIDA[0-9A-Za-z]{11}', null, 'RECIPIENT_PARTY_ID_NOT_ALLOWED_PATTERN')),
    IFF(RECIPIENT_NAME is null OR ARRAY_SIZE(RECIPIENT_NAME) <= 1, null, 'RECIPIENT_NAME_HAS_MULTIPLE_ITEMS')
  )
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_12.HEAD;


CREATE OR REPLACE VIEW FOOT_VALIDATION (
  ASSET_ID,
  LINE_INDEX,
  RECORD_TYPE,
  VIOLATIONS
) AS SELECT
  ASSET_ID,
  LINE_INDEX,
  'FOOT',
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, 'RECORD_TYPE_REQUIRED'),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, 'RECORD_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('FOOT'), null, 'RECORD_TYPE_NOT_ALLOWED_VALUE')),
    IFF(NUMBER_OF_LINES_IN_FILE is not null AND ARRAY_SIZE(NUMBER_OF_LINES_IN_FILE) >= 1, null, 'NUMBER_OF_LINES_IN_FILE_REQUIRED'),
    IFF(NUMBER_OF_LINES_IN_FILE is null OR ARRAY_SIZE(NUMBER_OF_LINES_IN_FILE) <= 1, null, 'NUMBER_OF_LINES_IN_FILE_HAS_MULTIPLE_ITEMS'),
    IFF(NUMBER_OF_LINES_IN_FILE[0] is null, null, IFF(NUMBER_OF_LINES_IN_FILE[0]::string REGEXP '\\d+', null, 'NUMBER_OF_LINES_IN_FILE_NOT_INTEGER')),
    IFF(NUMBER_OF_LINES_IN_REPORT is null OR ARRAY_SIZE(NUMBER_OF_LINES_IN_REPORT) <= 1, null, 'NUMBER_OF_LINES_IN_REPORT_HAS_MULTIPLE_ITEMS'),
    IFF(NUMBER_OF_LINES_IN_REPORT[0] is null, null, IFF(NUMBER_OF_LINES_IN_REPORT[0]::string REGEXP '\\d+', null, 'NUMBER_OF_LINES_IN_REPORT_NOT_INTEGER')),
    IFF(NUMBER_OF_SUMMARY_RECORDS is not null AND ARRAY_SIZE(NUMBER_OF_SUMMARY_RECORDS) >= 1, null, 'NUMBER_OF_SUMMARY_RECORDS_REQUIRED'),
    IFF(NUMBER_OF_SUMMARY_RECORDS is null OR ARRAY_SIZE(NUMBER_OF_SUMMARY_RECORDS) <= 1, null, 'NUMBER_OF_SUMMARY_RECORDS_HAS_MULTIPLE_ITEMS'),
    IFF(NUMBER_OF_SUMMARY_RECORDS[0] is null, null, IFF(NUMBER_OF_SUMMARY_RECORDS[0]::string REGEXP '\\d+', null, 'NUMBER_OF_SUMMARY_RECORDS_NOT_INTEGER')),
    IFF(NUMBER_OF_BLOCKS_IN_FILE is not null AND ARRAY_SIZE(NUMBER_OF_BLOCKS_IN_FILE) >= 1, null, 'NUMBER_OF_BLOCKS_IN_FILE_REQUIRED'),
    IFF(NUMBER_OF_BLOCKS_IN_FILE is null OR ARRAY_SIZE(NUMBER_OF_BLOCKS_IN_FILE) <= 1, null, 'NUMBER_OF_BLOCKS_IN_FILE_HAS_MULTIPLE_ITEMS'),
    IFF(NUMBER_OF_BLOCKS_IN_FILE[0] is null, null, IFF(NUMBER_OF_BLOCKS_IN_FILE[0]::string REGEXP '\\d+', null, 'NUMBER_OF_BLOCKS_IN_FILE_NOT_INTEGER')),
    IFF(NUMBER_OF_BLOCKS_IN_REPORT is null OR ARRAY_SIZE(NUMBER_OF_BLOCKS_IN_REPORT) <= 1, null, 'NUMBER_OF_BLOCKS_IN_REPORT_HAS_MULTIPLE_ITEMS'),
    IFF(NUMBER_OF_BLOCKS_IN_REPORT[0] is null, null, IFF(NUMBER_OF_BLOCKS_IN_REPORT[0]::string REGEXP '\\d+', null, 'NUMBER_OF_BLOCKS_IN_REPORT_NOT_INTEGER'))
  )
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_12.FOOT;


CREATE OR REPLACE VIEW SY01_01_VALIDATION (
  ASSET_ID,
  LINE_INDEX,
  RECORD_TYPE,
  VIOLATIONS
) AS SELECT
  ASSET_ID,
  LINE_INDEX,
  'SY01.01',
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, 'RECORD_TYPE_REQUIRED'),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, 'RECORD_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('SY01.01'), null, 'RECORD_TYPE_NOT_ALLOWED_VALUE')),
    IFF(SUMMARY_RECORD_ID is not null AND ARRAY_SIZE(SUMMARY_RECORD_ID) >= 1, null, 'SUMMARY_RECORD_ID_REQUIRED'),
    IFF(SUMMARY_RECORD_ID is null OR ARRAY_SIZE(SUMMARY_RECORD_ID) <= 1, null, 'SUMMARY_RECORD_ID_HAS_MULTIPLE_ITEMS'),
    IFF(DISTRIBUTION_CHANNEL is null OR ARRAY_SIZE(DISTRIBUTION_CHANNEL) <= 1, null, 'DISTRIBUTION_CHANNEL_HAS_MULTIPLE_ITEMS'),
    IFF(DISTRIBUTION_CHANNEL_DPID is null OR ARRAY_SIZE(DISTRIBUTION_CHANNEL_DPID) <= 1, null, 'DISTRIBUTION_CHANNEL_DPID_HAS_MULTIPLE_ITEMS'),
    IFF(DISTRIBUTION_CHANNEL_DPID[0] is null, null, IFF(DISTRIBUTION_CHANNEL_DPID[0]::string REGEXP 'PADPIDA[0-9A-Za-z]{11}', null, 'DISTRIBUTION_CHANNEL_DPID_NOT_ALLOWED_PATTERN')),
    IFF(COMMERCIAL_MODEL is not null AND ARRAY_SIZE(COMMERCIAL_MODEL) >= 1, null, 'COMMERCIAL_MODEL_REQUIRED'),
    IFF(COMMERCIAL_MODEL is null OR ARRAY_SIZE(COMMERCIAL_MODEL) <= 1, null, 'COMMERCIAL_MODEL_HAS_MULTIPLE_ITEMS'),
    IFF(COMMERCIAL_MODEL[0] is null, null, IFF(is_commercial_model(COMMERCIAL_MODEL[0]::string), null, 'COMMERCIAL_MODEL_NOT_ALLOWED_VALUE')),
    IFF(USE_TYPE is not null AND ARRAY_SIZE(USE_TYPE) >= 1, null, 'USE_TYPE_REQUIRED'),
    IFF(USE_TYPE is null OR ARRAY_SIZE(USE_TYPE) <= 1, null, 'USE_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(USE_TYPE[0] is null, null, IFF(is_use_type(USE_TYPE[0]::string), null, 'USE_TYPE_NOT_ALLOWED_VALUE')),
    IFF(TERRITORY is not null AND ARRAY_SIZE(TERRITORY) >= 1, null, 'TERRITORY_REQUIRED'),
    IFF(TERRITORY is null OR ARRAY_SIZE(TERRITORY) <= 1, null, 'TERRITORY_HAS_MULTIPLE_ITEMS'),
    IFF(TERRITORY[0] is null, null, IFF(is_territory(TERRITORY[0]::string), null, 'TERRITORY_NOT_ALLOWED_VALUE')),
    IFF(SERVICE_DESCRIPTION is null OR ARRAY_SIZE(SERVICE_DESCRIPTION) <= 1, null, 'SERVICE_DESCRIPTION_HAS_MULTIPLE_ITEMS'),
    IFF(USAGES is not null AND ARRAY_SIZE(USAGES) >= 1, null, 'USAGES_REQUIRED'),
    IFF(USAGES is null OR ARRAY_SIZE(USAGES) <= 1, null, 'USAGES_HAS_MULTIPLE_ITEMS'),
    IFF(USAGES[0] is null, null, IFF(USAGES[0]::string REGEXP '\\d+', null, 'USAGES_NOT_INTEGER')),
    IFF(SUBSCRIBERS is null OR ARRAY_SIZE(SUBSCRIBERS) <= 1, null, 'SUBSCRIBERS_HAS_MULTIPLE_ITEMS'),
    IFF(SUBSCRIBERS[0] is null, null, IFF(SUBSCRIBERS[0]::string REGEXP '\\d+(\.\\d+)?', null, 'SUBSCRIBERS_NOT_DECIMAL')),
    IFF(CURRENCY_OF_REPORTING is not null AND ARRAY_SIZE(CURRENCY_OF_REPORTING) >= 1, null, 'CURRENCY_OF_REPORTING_REQUIRED'),
    IFF(CURRENCY_OF_REPORTING is null OR ARRAY_SIZE(CURRENCY_OF_REPORTING) <= 1, null, 'CURRENCY_OF_REPORTING_HAS_MULTIPLE_ITEMS'),
    IFF(CURRENCY_OF_REPORTING[0] is null, null, IFF(is_currency(CURRENCY_OF_REPORTING[0]::string), null, 'CURRENCY_OF_REPORTING_NOT_ALLOWED_VALUE')),
    IFF(NET_REVENUE is not null AND ARRAY_SIZE(NET_REVENUE) >= 1, null, 'NET_REVENUE_REQUIRED'),
    IFF(NET_REVENUE is null OR ARRAY_SIZE(NET_REVENUE) <= 1, null, 'NET_REVENUE_HAS_MULTIPLE_ITEMS'),
    IFF(NET_REVENUE[0] is null, null, IFF(NET_REVENUE[0]::string REGEXP '\\d+(\.\\d+)?', null, 'NET_REVENUE_NOT_DECIMAL')),
    IFF(INDIRECT_NET_REVENUE is null OR ARRAY_SIZE(INDIRECT_NET_REVENUE) <= 1, null, 'INDIRECT_NET_REVENUE_HAS_MULTIPLE_ITEMS'),
    IFF(INDIRECT_NET_REVENUE[0] is null, null, IFF(INDIRECT_NET_REVENUE[0]::string REGEXP '\\d+(\.\\d+)?', null, 'INDIRECT_NET_REVENUE_NOT_DECIMAL')),
    IFF(CURRENCY_OF_TRANSACTION is null OR ARRAY_SIZE(CURRENCY_OF_TRANSACTION) <= 1, null, 'CURRENCY_OF_TRANSACTION_HAS_MULTIPLE_ITEMS'),
    IFF(CURRENCY_OF_TRANSACTION[0] is null, null, IFF(is_currency(CURRENCY_OF_TRANSACTION[0]::string), null, 'CURRENCY_OF_TRANSACTION_NOT_ALLOWED_VALUE')),
    IFF(EXCHANGE_RATE is null OR ARRAY_SIZE(EXCHANGE_RATE) <= 1, null, 'EXCHANGE_RATE_HAS_MULTIPLE_ITEMS'),
    IFF(EXCHANGE_RATE[0] is null, null, IFF(EXCHANGE_RATE[0]::string REGEXP '\\d+(\.\\d+)?', null, 'EXCHANGE_RATE_NOT_DECIMAL'))
  )
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_12.SY01_01;


CREATE OR REPLACE VIEW SY02_02_VALIDATION (
  ASSET_ID,
  LINE_INDEX,
  RECORD_TYPE,
  VIOLATIONS
) AS SELECT
  ASSET_ID,
  LINE_INDEX,
  'SY02.02',
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, 'RECORD_TYPE_REQUIRED'),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, 'RECORD_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('SY02.02'), null, 'RECORD_TYPE_NOT_ALLOWED_VALUE')),
    IFF(SUMMARY_RECORD_ID is not null AND ARRAY_SIZE(SUMMARY_RECORD_ID) >= 1, null, 'SUMMARY_RECORD_ID_REQUIRED'),
    IFF(SUMMARY_RECORD_ID is null OR ARRAY_SIZE(SUMMARY_RECORD_ID) <= 1, null, 'SUMMARY_RECORD_ID_HAS_MULTIPLE_ITEMS'),
    IFF(DISTRIBUTION_CHANNEL is null OR ARRAY_SIZE(DISTRIBUTION_CHANNEL) <= 1, null, 'DISTRIBUTION_CHANNEL_HAS_MULTIPLE_ITEMS'),
    IFF(DISTRIBUTION_CHANNEL_DPID is null OR ARRAY_SIZE(DISTRIBUTION_CHANNEL_DPID) <= 1, null, 'DISTRIBUTION_CHANNEL_DPID_HAS_MULTIPLE_ITEMS'),
    IFF(DISTRIBUTION_CHANNEL_DPID[0] is null, null, IFF(DISTRIBUTION_CHANNEL_DPID[0]::string REGEXP 'PADPIDA[0-9A-Za-z]{11}', null, 'DISTRIBUTION_CHANNEL_DPID_NOT_ALLOWED_PATTERN')),
    IFF(COMMERCIAL_MODEL is not null AND ARRAY_SIZE(COMMERCIAL_MODEL) >= 1, null, 'COMMERCIAL_MODEL_REQUIRED'),
    IFF(COMMERCIAL_MODEL is null OR ARRAY_SIZE(COMMERCIAL_MODEL) <= 1, null, 'COMMERCIAL_MODEL_HAS_MULTIPLE_ITEMS'),
    IFF(COMMERCIAL_MODEL[0] is null, null, IFF(is_commercial_model(COMMERCIAL_MODEL[0]::string), null, 'COMMERCIAL_MODEL_NOT_ALLOWED_VALUE')),
    IFF(USE_TYPE is not null AND ARRAY_SIZE(USE_TYPE) >= 1, null, 'USE_TYPE_REQUIRED'),
    IFF(USE_TYPE is null OR ARRAY_SIZE(USE_TYPE) <= 1, null, 'USE_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(USE_TYPE[0] is null, null, IFF(is_use_type(USE_TYPE[0]::string), null, 'USE_TYPE_NOT_ALLOWED_VALUE')),
    IFF(TERRITORY is not null AND ARRAY_SIZE(TERRITORY) >= 1, null, 'TERRITORY_REQUIRED'),
    IFF(TERRITORY is null OR ARRAY_SIZE(TERRITORY) <= 1, null, 'TERRITORY_HAS_MULTIPLE_ITEMS'),
    IFF(TERRITORY[0] is null, null, IFF(is_territory(TERRITORY[0]::string), null, 'TERRITORY_NOT_ALLOWED_VALUE')),
    IFF(SERVICE_DESCRIPTION is not null AND ARRAY_SIZE(SERVICE_DESCRIPTION) >= 1, null, 'SERVICE_DESCRIPTION_REQUIRED'),
    IFF(SERVICE_DESCRIPTION is null OR ARRAY_SIZE(SERVICE_DESCRIPTION) <= 1, null, 'SERVICE_DESCRIPTION_HAS_MULTIPLE_ITEMS'),
    IFF(USAGES is not null AND ARRAY_SIZE(USAGES) >= 1, null, 'USAGES_REQUIRED'),
    IFF(USAGES is null OR ARRAY_SIZE(USAGES) <= 1, null, 'USAGES_HAS_MULTIPLE_ITEMS'),
    IFF(USAGES[0] is null, null, IFF(USAGES[0]::string REGEXP '\\d+', null, 'USAGES_NOT_INTEGER')),
    IFF(USERS is null OR ARRAY_SIZE(USERS) <= 1, null, 'USERS_HAS_MULTIPLE_ITEMS'),
    IFF(USERS[0] is null, null, IFF(USERS[0]::string REGEXP '\\d+', null, 'USERS_NOT_INTEGER')),
    IFF(CURRENCY_OF_REPORTING is not null AND ARRAY_SIZE(CURRENCY_OF_REPORTING) >= 1, null, 'CURRENCY_OF_REPORTING_REQUIRED'),
    IFF(CURRENCY_OF_REPORTING is null OR ARRAY_SIZE(CURRENCY_OF_REPORTING) <= 1, null, 'CURRENCY_OF_REPORTING_HAS_MULTIPLE_ITEMS'),
    IFF(CURRENCY_OF_REPORTING[0] is null, null, IFF(is_currency(CURRENCY_OF_REPORTING[0]::string), null, 'CURRENCY_OF_REPORTING_NOT_ALLOWED_VALUE')),
    IFF(NET_REVENUE is not null AND ARRAY_SIZE(NET_REVENUE) >= 1, null, 'NET_REVENUE_REQUIRED'),
    IFF(NET_REVENUE is null OR ARRAY_SIZE(NET_REVENUE) <= 1, null, 'NET_REVENUE_HAS_MULTIPLE_ITEMS'),
    IFF(NET_REVENUE[0] is null, null, IFF(NET_REVENUE[0]::string REGEXP '\\d+(\.\\d+)?', null, 'NET_REVENUE_NOT_DECIMAL')),
    IFF(RIGHTS_CONTROLLER is null OR ARRAY_SIZE(RIGHTS_CONTROLLER) <= 1, null, 'RIGHTS_CONTROLLER_HAS_MULTIPLE_ITEMS'),
    IFF(RIGHTS_CONTROLLER_PARTY_ID is null OR ARRAY_SIZE(RIGHTS_CONTROLLER_PARTY_ID) <= 1, null, 'RIGHTS_CONTROLLER_PARTY_ID_HAS_MULTIPLE_ITEMS'),
    IFF(RIGHTS_CONTROLLER_PARTY_ID[0] is null, null, IFF(RIGHTS_CONTROLLER_PARTY_ID[0]::string REGEXP 'INSI::\\d{16}', null, 'RIGHTS_CONTROLLER_PARTY_ID_NOT_ALLOWED_PATTERN')),
    IFF(ALLOCATED_NET_REVENUE is null OR ARRAY_SIZE(ALLOCATED_NET_REVENUE) <= 1, null, 'ALLOCATED_NET_REVENUE_HAS_MULTIPLE_ITEMS'),
    IFF(ALLOCATED_NET_REVENUE[0] is null, null, IFF(ALLOCATED_NET_REVENUE[0]::string REGEXP '\\d+(\.\\d+)?', null, 'ALLOCATED_NET_REVENUE_NOT_DECIMAL')),
    IFF(RIGHTS_TYPE is null OR ARRAY_SIZE(RIGHTS_TYPE) <= 1, null, 'RIGHTS_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(RIGHTS_TYPE[0] is null, null, IFF(is_right_type(RIGHTS_TYPE[0]::string), null, 'RIGHTS_TYPE_NOT_ALLOWED_VALUE')),
    IFF(CONTENT_CATEGORY is not null AND ARRAY_SIZE(CONTENT_CATEGORY) >= 1, null, 'CONTENT_CATEGORY_REQUIRED'),
    IFF(CONTENT_CATEGORY is null OR ARRAY_SIZE(CONTENT_CATEGORY) <= 1, null, 'CONTENT_CATEGORY_HAS_MULTIPLE_ITEMS'),
    IFF(CURRENCY_OF_TRANSACTION is null OR ARRAY_SIZE(CURRENCY_OF_TRANSACTION) <= 1, null, 'CURRENCY_OF_TRANSACTION_HAS_MULTIPLE_ITEMS'),
    IFF(CURRENCY_OF_TRANSACTION[0] is null, null, IFF(is_currency(CURRENCY_OF_TRANSACTION[0]::string), null, 'CURRENCY_OF_TRANSACTION_NOT_ALLOWED_VALUE')),
    IFF(EXCHANGE_RATE is null OR ARRAY_SIZE(EXCHANGE_RATE) <= 1, null, 'EXCHANGE_RATE_HAS_MULTIPLE_ITEMS'),
    IFF(EXCHANGE_RATE[0] is null, null, IFF(EXCHANGE_RATE[0]::string REGEXP '\\d+(\.\\d+)?', null, 'EXCHANGE_RATE_NOT_DECIMAL')),
    IFF(RIGHTS_TYPE_PERCENTAGE is null OR ARRAY_SIZE(RIGHTS_TYPE_PERCENTAGE) <= 1, null, 'RIGHTS_TYPE_PERCENTAGE_HAS_MULTIPLE_ITEMS'),
    IFF(RIGHTS_TYPE_PERCENTAGE[0] is null, null, IFF(RIGHTS_TYPE_PERCENTAGE[0]::string REGEXP '\\d+(\.\\d+)?', null, 'RIGHTS_TYPE_PERCENTAGE_NOT_DECIMAL'))
  )
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_12.SY02_02;


CREATE OR REPLACE VIEW SY04_01_VALIDATION (
  ASSET_ID,
  LINE_INDEX,
  RECORD_TYPE,
  VIOLATIONS
) AS SELECT
  ASSET_ID,
  LINE_INDEX,
  'SY04.01',
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, 'RECORD_TYPE_REQUIRED'),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, 'RECORD_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('SY04.01'), null, 'RECORD_TYPE_NOT_ALLOWED_VALUE')),
    IFF(SUMMARY_RECORD_ID is not null AND ARRAY_SIZE(SUMMARY_RECORD_ID) >= 1, null, 'SUMMARY_RECORD_ID_REQUIRED'),
    IFF(SUMMARY_RECORD_ID is null OR ARRAY_SIZE(SUMMARY_RECORD_ID) <= 1, null, 'SUMMARY_RECORD_ID_HAS_MULTIPLE_ITEMS'),
    IFF(DISTRIBUTION_CHANNEL is null OR ARRAY_SIZE(DISTRIBUTION_CHANNEL) <= 1, null, 'DISTRIBUTION_CHANNEL_HAS_MULTIPLE_ITEMS'),
    IFF(DISTRIBUTION_CHANNEL_DPID is null OR ARRAY_SIZE(DISTRIBUTION_CHANNEL_DPID) <= 1, null, 'DISTRIBUTION_CHANNEL_DPID_HAS_MULTIPLE_ITEMS'),
    IFF(DISTRIBUTION_CHANNEL_DPID[0] is null, null, IFF(DISTRIBUTION_CHANNEL_DPID[0]::string REGEXP 'PADPIDA[0-9A-Za-z]{11}', null, 'DISTRIBUTION_CHANNEL_DPID_NOT_ALLOWED_PATTERN')),
    IFF(COMMERCIAL_MODEL is not null AND ARRAY_SIZE(COMMERCIAL_MODEL) >= 1, null, 'COMMERCIAL_MODEL_REQUIRED'),
    IFF(COMMERCIAL_MODEL is null OR ARRAY_SIZE(COMMERCIAL_MODEL) <= 1, null, 'COMMERCIAL_MODEL_HAS_MULTIPLE_ITEMS'),
    IFF(COMMERCIAL_MODEL[0] is null, null, IFF(is_commercial_model(COMMERCIAL_MODEL[0]::string), null, 'COMMERCIAL_MODEL_NOT_ALLOWED_VALUE')),
    IFF(USE_TYPE is not null AND ARRAY_SIZE(USE_TYPE) >= 1, null, 'USE_TYPE_REQUIRED'),
    IFF(USE_TYPE is null OR ARRAY_SIZE(USE_TYPE) <= 1, null, 'USE_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(USE_TYPE[0] is null, null, IFF(is_use_type(USE_TYPE[0]::string), null, 'USE_TYPE_NOT_ALLOWED_VALUE')),
    IFF(TERRITORY is not null AND ARRAY_SIZE(TERRITORY) >= 1, null, 'TERRITORY_REQUIRED'),
    IFF(TERRITORY is null OR ARRAY_SIZE(TERRITORY) <= 1, null, 'TERRITORY_HAS_MULTIPLE_ITEMS'),
    IFF(TERRITORY[0] is null, null, IFF(is_territory(TERRITORY[0]::string), null, 'TERRITORY_NOT_ALLOWED_VALUE')),
    IFF(SERVICE_DESCRIPTION is not null AND ARRAY_SIZE(SERVICE_DESCRIPTION) >= 1, null, 'SERVICE_DESCRIPTION_REQUIRED'),
    IFF(SERVICE_DESCRIPTION is null OR ARRAY_SIZE(SERVICE_DESCRIPTION) <= 1, null, 'SERVICE_DESCRIPTION_HAS_MULTIPLE_ITEMS'),
    IFF(SUBSCRIBER_TYPE is not null AND ARRAY_SIZE(SUBSCRIBER_TYPE) >= 1, null, 'SUBSCRIBER_TYPE_REQUIRED'),
    IFF(SUBSCRIBER_TYPE is null OR ARRAY_SIZE(SUBSCRIBER_TYPE) <= 1, null, 'SUBSCRIBER_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(SUBSCRIBERS is not null AND ARRAY_SIZE(SUBSCRIBERS) >= 1, null, 'SUBSCRIBERS_REQUIRED'),
    IFF(SUBSCRIBERS is null OR ARRAY_SIZE(SUBSCRIBERS) <= 1, null, 'SUBSCRIBERS_HAS_MULTIPLE_ITEMS'),
    IFF(SUBSCRIBERS[0] is null, null, IFF(SUBSCRIBERS[0]::string REGEXP '\\d+(\.\\d+)?', null, 'SUBSCRIBERS_NOT_DECIMAL')),
    IFF(SUB_PERIOD_START_DATE is null OR ARRAY_SIZE(SUB_PERIOD_START_DATE) <= 1, null, 'SUB_PERIOD_START_DATE_HAS_MULTIPLE_ITEMS'),
    IFF(SUB_PERIOD_START_DATE[0] is null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_START_DATE[0]::string, 'YYYY-MM-DD') is not null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_START_DATE[0]::string, 'YYYY-MM') is not null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_START_DATE[0]::string, 'YYYY') is not null, null, 'SUB_PERIOD_START_DATE_NOT_DATE')))),
    IFF(SUB_PERIOD_END_DATE is null OR ARRAY_SIZE(SUB_PERIOD_END_DATE) <= 1, null, 'SUB_PERIOD_END_DATE_HAS_MULTIPLE_ITEMS'),
    IFF(SUB_PERIOD_END_DATE[0] is null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_END_DATE[0]::string, 'YYYY-MM-DD') is not null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_END_DATE[0]::string, 'YYYY-MM') is not null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_END_DATE[0]::string, 'YYYY') is not null, null, 'SUB_PERIOD_END_DATE_NOT_DATE')))),
    IFF(USAGES_IN_SUB_PERIOD is null OR ARRAY_SIZE(USAGES_IN_SUB_PERIOD) <= 1, null, 'USAGES_IN_SUB_PERIOD_HAS_MULTIPLE_ITEMS'),
    IFF(USAGES_IN_SUB_PERIOD[0] is null, null, IFF(USAGES_IN_SUB_PERIOD[0]::string REGEXP '\\d+', null, 'USAGES_IN_SUB_PERIOD_NOT_INTEGER')),
    IFF(USAGES_IN_REPORTING_PERIOD is null OR ARRAY_SIZE(USAGES_IN_REPORTING_PERIOD) <= 1, null, 'USAGES_IN_REPORTING_PERIOD_HAS_MULTIPLE_ITEMS'),
    IFF(USAGES_IN_REPORTING_PERIOD[0] is null, null, IFF(USAGES_IN_REPORTING_PERIOD[0]::string REGEXP '\\d+', null, 'USAGES_IN_REPORTING_PERIOD_NOT_INTEGER')),
    IFF(CURRENCY_OF_REPORTING is not null AND ARRAY_SIZE(CURRENCY_OF_REPORTING) >= 1, null, 'CURRENCY_OF_REPORTING_REQUIRED'),
    IFF(CURRENCY_OF_REPORTING is null OR ARRAY_SIZE(CURRENCY_OF_REPORTING) <= 1, null, 'CURRENCY_OF_REPORTING_HAS_MULTIPLE_ITEMS'),
    IFF(CURRENCY_OF_REPORTING[0] is null, null, IFF(is_currency(CURRENCY_OF_REPORTING[0]::string), null, 'CURRENCY_OF_REPORTING_NOT_ALLOWED_VALUE')),
    IFF(CURRENCY_OF_TRANSACTION is null OR ARRAY_SIZE(CURRENCY_OF_TRANSACTION) <= 1, null, 'CURRENCY_OF_TRANSACTION_HAS_MULTIPLE_ITEMS'),
    IFF(CURRENCY_OF_TRANSACTION[0] is null, null, IFF(is_currency(CURRENCY_OF_TRANSACTION[0]::string), null, 'CURRENCY_OF_TRANSACTION_NOT_ALLOWED_VALUE')),
    IFF(EXCHANGE_RATE is null OR ARRAY_SIZE(EXCHANGE_RATE) <= 1, null, 'EXCHANGE_RATE_HAS_MULTIPLE_ITEMS'),
    IFF(EXCHANGE_RATE[0] is null, null, IFF(EXCHANGE_RATE[0]::string REGEXP '\\d+(\.\\d+)?', null, 'EXCHANGE_RATE_NOT_DECIMAL')),
    IFF(CONSUMER_PAID_UNIT_PRICE is not null AND ARRAY_SIZE(CONSUMER_PAID_UNIT_PRICE) >= 1, null, 'CONSUMER_PAID_UNIT_PRICE_REQUIRED'),
    IFF(CONSUMER_PAID_UNIT_PRICE is null OR ARRAY_SIZE(CONSUMER_PAID_UNIT_PRICE) <= 1, null, 'CONSUMER_PAID_UNIT_PRICE_HAS_MULTIPLE_ITEMS'),
    IFF(CONSUMER_PAID_UNIT_PRICE[0] is null, null, IFF(CONSUMER_PAID_UNIT_PRICE[0]::string REGEXP '\\d+(\.\\d+)?', null, 'CONSUMER_PAID_UNIT_PRICE_NOT_DECIMAL')),
    IFF(NET_REVENUE is not null AND ARRAY_SIZE(NET_REVENUE) >= 1, null, 'NET_REVENUE_REQUIRED'),
    IFF(NET_REVENUE is null OR ARRAY_SIZE(NET_REVENUE) <= 1, null, 'NET_REVENUE_HAS_MULTIPLE_ITEMS'),
    IFF(NET_REVENUE[0] is null, null, IFF(NET_REVENUE[0]::string REGEXP '\\d+(\.\\d+)?', null, 'NET_REVENUE_NOT_DECIMAL')),
    IFF(MUSIC_USAGE_PERCENTAGE is null OR ARRAY_SIZE(MUSIC_USAGE_PERCENTAGE) <= 1, null, 'MUSIC_USAGE_PERCENTAGE_HAS_MULTIPLE_ITEMS'),
    IFF(MUSIC_USAGE_PERCENTAGE[0] is null, null, IFF(MUSIC_USAGE_PERCENTAGE[0]::string REGEXP '\\d+(\.\\d+)?', null, 'MUSIC_USAGE_PERCENTAGE_NOT_DECIMAL')),
    IFF(MUSIC_USAGE_PERCENTAGE[0] is null, null, IFF(MUSIC_USAGE_PERCENTAGE[0]::number <= 100, null, 'MUSIC_USAGE_PERCENTAGE_GREATER_THAN_MAX_SIZE'))
  )
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_12.SY04_01;


CREATE OR REPLACE VIEW SY05_02_VALIDATION (
  ASSET_ID,
  LINE_INDEX,
  RECORD_TYPE,
  VIOLATIONS
) AS SELECT
  ASSET_ID,
  LINE_INDEX,
  'SY05.02',
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, 'RECORD_TYPE_REQUIRED'),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, 'RECORD_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('SY05.02'), null, 'RECORD_TYPE_NOT_ALLOWED_VALUE')),
    IFF(SUMMARY_RECORD_ID is not null AND ARRAY_SIZE(SUMMARY_RECORD_ID) >= 1, null, 'SUMMARY_RECORD_ID_REQUIRED'),
    IFF(SUMMARY_RECORD_ID is null OR ARRAY_SIZE(SUMMARY_RECORD_ID) <= 1, null, 'SUMMARY_RECORD_ID_HAS_MULTIPLE_ITEMS'),
    IFF(DISTRIBUTION_CHANNEL is null OR ARRAY_SIZE(DISTRIBUTION_CHANNEL) <= 1, null, 'DISTRIBUTION_CHANNEL_HAS_MULTIPLE_ITEMS'),
    IFF(DISTRIBUTION_CHANNEL_DPID is null OR ARRAY_SIZE(DISTRIBUTION_CHANNEL_DPID) <= 1, null, 'DISTRIBUTION_CHANNEL_DPID_HAS_MULTIPLE_ITEMS'),
    IFF(DISTRIBUTION_CHANNEL_DPID[0] is null, null, IFF(DISTRIBUTION_CHANNEL_DPID[0]::string REGEXP 'PADPIDA[0-9A-Za-z]{11}', null, 'DISTRIBUTION_CHANNEL_DPID_NOT_ALLOWED_PATTERN')),
    IFF(COMMERCIAL_MODEL is not null AND ARRAY_SIZE(COMMERCIAL_MODEL) >= 1, null, 'COMMERCIAL_MODEL_REQUIRED'),
    IFF(COMMERCIAL_MODEL is null OR ARRAY_SIZE(COMMERCIAL_MODEL) <= 1, null, 'COMMERCIAL_MODEL_HAS_MULTIPLE_ITEMS'),
    IFF(COMMERCIAL_MODEL[0] is null, null, IFF(is_commercial_model(COMMERCIAL_MODEL[0]::string), null, 'COMMERCIAL_MODEL_NOT_ALLOWED_VALUE')),
    IFF(USE_TYPE is not null AND ARRAY_SIZE(USE_TYPE) >= 1, null, 'USE_TYPE_REQUIRED'),
    IFF(USE_TYPE is null OR ARRAY_SIZE(USE_TYPE) <= 1, null, 'USE_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(USE_TYPE[0] is null, null, IFF(is_use_type(USE_TYPE[0]::string), null, 'USE_TYPE_NOT_ALLOWED_VALUE')),
    IFF(TERRITORY is not null AND ARRAY_SIZE(TERRITORY) >= 1, null, 'TERRITORY_REQUIRED'),
    IFF(TERRITORY is null OR ARRAY_SIZE(TERRITORY) <= 1, null, 'TERRITORY_HAS_MULTIPLE_ITEMS'),
    IFF(TERRITORY[0] is null, null, IFF(is_territory(TERRITORY[0]::string), null, 'TERRITORY_NOT_ALLOWED_VALUE')),
    IFF(SERVICE_DESCRIPTION is null OR ARRAY_SIZE(SERVICE_DESCRIPTION) <= 1, null, 'SERVICE_DESCRIPTION_HAS_MULTIPLE_ITEMS'),
    IFF(RIGHTS_CONTROLLER is null OR ARRAY_SIZE(RIGHTS_CONTROLLER) <= 1, null, 'RIGHTS_CONTROLLER_HAS_MULTIPLE_ITEMS'),
    IFF(RIGHTS_CONTROLLER_PARTY_ID is null OR ARRAY_SIZE(RIGHTS_CONTROLLER_PARTY_ID) <= 1, null, 'RIGHTS_CONTROLLER_PARTY_ID_HAS_MULTIPLE_ITEMS'),
    IFF(RIGHTS_CONTROLLER_PARTY_ID[0] is null, null, IFF(RIGHTS_CONTROLLER_PARTY_ID[0]::string REGEXP 'INSI::\\d{16}', null, 'RIGHTS_CONTROLLER_PARTY_ID_NOT_ALLOWED_PATTERN')),
    IFF(RIGHTS_TYPE is not null AND ARRAY_SIZE(RIGHTS_TYPE) >= 1, null, 'RIGHTS_TYPE_REQUIRED'),
    IFF(RIGHTS_TYPE is null OR ARRAY_SIZE(RIGHTS_TYPE) <= 1, null, 'RIGHTS_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(RIGHTS_TYPE[0] is null, null, IFF(is_right_type(RIGHTS_TYPE[0]::string), null, 'RIGHTS_TYPE_NOT_ALLOWED_VALUE')),
    IFF(TOTAL_USAGES is null OR ARRAY_SIZE(TOTAL_USAGES) <= 1, null, 'TOTAL_USAGES_HAS_MULTIPLE_ITEMS'),
    IFF(TOTAL_USAGES[0] is null, null, IFF(TOTAL_USAGES[0]::string REGEXP '\\d+', null, 'TOTAL_USAGES_NOT_INTEGER')),
    IFF(MUSIC_USAGE_RATIO is null OR ARRAY_SIZE(MUSIC_USAGE_RATIO) <= 1, null, 'MUSIC_USAGE_RATIO_HAS_MULTIPLE_ITEMS'),
    IFF(MUSIC_USAGE_RATIO[0] is null, null, IFF(MUSIC_USAGE_RATIO[0]::string REGEXP '\\d+(\.\\d+)?', null, 'MUSIC_USAGE_RATIO_NOT_DECIMAL')),
    IFF(ALLOCATED_REVENUE is null OR ARRAY_SIZE(ALLOCATED_REVENUE) <= 1, null, 'ALLOCATED_REVENUE_HAS_MULTIPLE_ITEMS'),
    IFF(ALLOCATED_REVENUE[0] is null, null, IFF(ALLOCATED_REVENUE[0]::string REGEXP '\\d+(\.\\d+)?', null, 'ALLOCATED_REVENUE_NOT_DECIMAL')),
    IFF(RIGHTS_CONTROLLER_MARKET_SHARE is null OR ARRAY_SIZE(RIGHTS_CONTROLLER_MARKET_SHARE) <= 1, null, 'RIGHTS_CONTROLLER_MARKET_SHARE_HAS_MULTIPLE_ITEMS'),
    IFF(RIGHTS_CONTROLLER_MARKET_SHARE[0] is null, null, IFF(RIGHTS_CONTROLLER_MARKET_SHARE[0]::string REGEXP '\\d+(\.\\d+)?', null, 'RIGHTS_CONTROLLER_MARKET_SHARE_NOT_DECIMAL')),
    IFF(CURRENCY is null OR ARRAY_SIZE(CURRENCY) <= 1, null, 'CURRENCY_HAS_MULTIPLE_ITEMS'),
    IFF(CURRENCY[0] is null, null, IFF(is_currency(CURRENCY[0]::string), null, 'CURRENCY_NOT_ALLOWED_VALUE')),
    IFF(EXCHANGE_RATE_BASE_CURRENCY is null OR ARRAY_SIZE(EXCHANGE_RATE_BASE_CURRENCY) <= 1, null, 'EXCHANGE_RATE_BASE_CURRENCY_HAS_MULTIPLE_ITEMS'),
    IFF(EXCHANGE_RATE_BASE_CURRENCY[0] is null, null, IFF(is_currency(EXCHANGE_RATE_BASE_CURRENCY[0]::string), null, 'EXCHANGE_RATE_BASE_CURRENCY_NOT_ALLOWED_VALUE')),
    IFF(EXCHANGE_RATE is null OR ARRAY_SIZE(EXCHANGE_RATE) <= 1, null, 'EXCHANGE_RATE_HAS_MULTIPLE_ITEMS'),
    IFF(EXCHANGE_RATE[0] is null, null, IFF(EXCHANGE_RATE[0]::string REGEXP '\\d+(\.\\d+)?', null, 'EXCHANGE_RATE_NOT_DECIMAL')),
    IFF(SUBSCRIBER_TYPE is null OR ARRAY_SIZE(SUBSCRIBER_TYPE) <= 1, null, 'SUBSCRIBER_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(SUB_PERIOD_START_DATE is null OR ARRAY_SIZE(SUB_PERIOD_START_DATE) <= 1, null, 'SUB_PERIOD_START_DATE_HAS_MULTIPLE_ITEMS'),
    IFF(SUB_PERIOD_START_DATE[0] is null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_START_DATE[0]::string, 'YYYY-MM-DD') is not null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_START_DATE[0]::string, 'YYYY-MM') is not null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_START_DATE[0]::string, 'YYYY') is not null, null, 'SUB_PERIOD_START_DATE_NOT_DATE')))),
    IFF(SUB_PERIOD_END_DATE is null OR ARRAY_SIZE(SUB_PERIOD_END_DATE) <= 1, null, 'SUB_PERIOD_END_DATE_HAS_MULTIPLE_ITEMS'),
    IFF(SUB_PERIOD_END_DATE[0] is null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_END_DATE[0]::string, 'YYYY-MM-DD') is not null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_END_DATE[0]::string, 'YYYY-MM') is not null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_END_DATE[0]::string, 'YYYY') is not null, null, 'SUB_PERIOD_END_DATE_NOT_DATE')))),
    IFF(CONTENT_CATEGORY is not null AND ARRAY_SIZE(CONTENT_CATEGORY) >= 1, null, 'CONTENT_CATEGORY_REQUIRED'),
    IFF(CONTENT_CATEGORY is null OR ARRAY_SIZE(CONTENT_CATEGORY) <= 1, null, 'CONTENT_CATEGORY_HAS_MULTIPLE_ITEMS'),
    IFF(RIGHTS_TYPE_PERCENTAGE is null OR ARRAY_SIZE(RIGHTS_TYPE_PERCENTAGE) <= 1, null, 'RIGHTS_TYPE_PERCENTAGE_HAS_MULTIPLE_ITEMS'),
    IFF(RIGHTS_TYPE_PERCENTAGE[0] is null, null, IFF(RIGHTS_TYPE_PERCENTAGE[0]::string REGEXP '\\d+(\.\\d+)?', null, 'RIGHTS_TYPE_PERCENTAGE_NOT_DECIMAL'))
  )
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_12.SY05_02;


CREATE OR REPLACE VIEW RE01_VALIDATION (
  ASSET_ID,
  LINE_INDEX,
  RECORD_TYPE,
  VIOLATIONS
) AS SELECT
  ASSET_ID,
  LINE_INDEX,
  'RE01',
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, 'RECORD_TYPE_REQUIRED'),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, 'RECORD_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('RE01'), null, 'RECORD_TYPE_NOT_ALLOWED_VALUE')),
    IFF(BLOCK_ID is not null AND ARRAY_SIZE(BLOCK_ID) >= 1, null, 'BLOCK_ID_REQUIRED'),
    IFF(BLOCK_ID is null OR ARRAY_SIZE(BLOCK_ID) <= 1, null, 'BLOCK_ID_HAS_MULTIPLE_ITEMS'),
    IFF(RELEASE_REFERENCE is not null AND ARRAY_SIZE(RELEASE_REFERENCE) >= 1, null, 'RELEASE_REFERENCE_REQUIRED'),
    IFF(RELEASE_REFERENCE is null OR ARRAY_SIZE(RELEASE_REFERENCE) <= 1, null, 'RELEASE_REFERENCE_HAS_MULTIPLE_ITEMS'),
    IFF(DSP_RELEASE_ID is not null AND ARRAY_SIZE(DSP_RELEASE_ID) >= 1, null, 'DSP_RELEASE_ID_REQUIRED'),
    IFF(DSP_RELEASE_ID is null OR ARRAY_SIZE(DSP_RELEASE_ID) <= 1, null, 'DSP_RELEASE_ID_HAS_MULTIPLE_ITEMS'),
    IFF(CATALOG_NUMBER is null OR ARRAY_SIZE(CATALOG_NUMBER) <= 1, null, 'CATALOG_NUMBER_HAS_MULTIPLE_ITEMS'),
    IFF(ICPN is null OR ARRAY_SIZE(ICPN) <= 1, null, 'ICPN_HAS_MULTIPLE_ITEMS'),
    IFF(ICPN[0] is null, null, IFF(ICPN[0]::string REGEXP '\\d{12,14}', null, 'ICPN_NOT_ALLOWED_PATTERN')),
    IFF(DISPLAY_ARTIST_NAME is not null AND ARRAY_SIZE(DISPLAY_ARTIST_NAME) >= 1, null, 'DISPLAY_ARTIST_NAME_REQUIRED'),
    IFF(DISPLAY_ARTIST_NAME is null OR ARRAY_SIZE(DISPLAY_ARTIST_NAME) <= 1, null, 'DISPLAY_ARTIST_NAME_HAS_MULTIPLE_ITEMS'),
    IFF(DISPLAY_ARTIST_PARTY_ID is null OR ARRAY_SIZE(DISPLAY_ARTIST_PARTY_ID) <= 1, null, 'DISPLAY_ARTIST_PARTY_ID_HAS_MULTIPLE_ITEMS'),
    IFF(DISPLAY_ARTIST_PARTY_ID[0] is null, null, IFF(DISPLAY_ARTIST_PARTY_ID[0]::string REGEXP 'INSI::\\d{16}', null, 'DISPLAY_ARTIST_PARTY_ID_NOT_ALLOWED_PATTERN')),
    IFF(TITLE is not null AND ARRAY_SIZE(TITLE) >= 1, null, 'TITLE_REQUIRED'),
    IFF(TITLE is null OR ARRAY_SIZE(TITLE) <= 1, null, 'TITLE_HAS_MULTIPLE_ITEMS'),
    IFF(SUB_TITLE is null OR ARRAY_SIZE(SUB_TITLE) <= 1, null, 'SUB_TITLE_HAS_MULTIPLE_ITEMS'),
    IFF(RELEASE_TYPE is null OR ARRAY_SIZE(RELEASE_TYPE) <= 1, null, 'RELEASE_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(RELEASE_TYPE[0] is null, null, IFF(is_release_type(RELEASE_TYPE[0]::string), null, 'RELEASE_TYPE_NOT_ALLOWED_VALUE')),
    IFF(LABEL is null OR ARRAY_SIZE(LABEL) <= 1, null, 'LABEL_HAS_MULTIPLE_ITEMS'),
    IFF(P_LINE is null OR ARRAY_SIZE(P_LINE) <= 1, null, 'P_LINE_HAS_MULTIPLE_ITEMS'),
    IFF(DATA_PROVIDER is null OR ARRAY_SIZE(DATA_PROVIDER) <= 1, null, 'DATA_PROVIDER_HAS_MULTIPLE_ITEMS')
  )
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_12.RE01;


CREATE OR REPLACE VIEW RE02_VALIDATION (
  ASSET_ID,
  LINE_INDEX,
  RECORD_TYPE,
  VIOLATIONS
) AS SELECT
  ASSET_ID,
  LINE_INDEX,
  'RE02',
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, 'RECORD_TYPE_REQUIRED'),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, 'RECORD_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('RE02'), null, 'RECORD_TYPE_NOT_ALLOWED_VALUE')),
    IFF(BLOCK_ID is not null AND ARRAY_SIZE(BLOCK_ID) >= 1, null, 'BLOCK_ID_REQUIRED'),
    IFF(BLOCK_ID is null OR ARRAY_SIZE(BLOCK_ID) <= 1, null, 'BLOCK_ID_HAS_MULTIPLE_ITEMS'),
    IFF(RELEASE_REFERENCE is not null AND ARRAY_SIZE(RELEASE_REFERENCE) >= 1, null, 'RELEASE_REFERENCE_REQUIRED'),
    IFF(RELEASE_REFERENCE is null OR ARRAY_SIZE(RELEASE_REFERENCE) <= 1, null, 'RELEASE_REFERENCE_HAS_MULTIPLE_ITEMS'),
    IFF(DSP_SUB_RELEASE_ID is not null AND ARRAY_SIZE(DSP_SUB_RELEASE_ID) >= 1, null, 'DSP_SUB_RELEASE_ID_REQUIRED'),
    IFF(DSP_SUB_RELEASE_ID is null OR ARRAY_SIZE(DSP_SUB_RELEASE_ID) <= 1, null, 'DSP_SUB_RELEASE_ID_HAS_MULTIPLE_ITEMS'),
    IFF(USED_RESOURCES is not null AND ARRAY_SIZE(USED_RESOURCES) >= 1, null, 'USED_RESOURCES_REQUIRED')
  )
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_12.RE02;


CREATE OR REPLACE VIEW AS01_01_VALIDATION (
  ASSET_ID,
  LINE_INDEX,
  RECORD_TYPE,
  VIOLATIONS
) AS SELECT
  ASSET_ID,
  LINE_INDEX,
  'AS01.01',
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, 'RECORD_TYPE_REQUIRED'),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, 'RECORD_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('AS01.01'), null, 'RECORD_TYPE_NOT_ALLOWED_VALUE')),
    IFF(BLOCK_ID is not null AND ARRAY_SIZE(BLOCK_ID) >= 1, null, 'BLOCK_ID_REQUIRED'),
    IFF(BLOCK_ID is null OR ARRAY_SIZE(BLOCK_ID) <= 1, null, 'BLOCK_ID_HAS_MULTIPLE_ITEMS'),
    IFF(RESOURCE_REFERENCE is not null AND ARRAY_SIZE(RESOURCE_REFERENCE) >= 1, null, 'RESOURCE_REFERENCE_REQUIRED'),
    IFF(RESOURCE_REFERENCE is null OR ARRAY_SIZE(RESOURCE_REFERENCE) <= 1, null, 'RESOURCE_REFERENCE_HAS_MULTIPLE_ITEMS'),
    IFF(DSP_RESOURCE_ID is not null AND ARRAY_SIZE(DSP_RESOURCE_ID) >= 1, null, 'DSP_RESOURCE_ID_REQUIRED'),
    IFF(DSP_RESOURCE_ID is null OR ARRAY_SIZE(DSP_RESOURCE_ID) <= 1, null, 'DSP_RESOURCE_ID_HAS_MULTIPLE_ITEMS'),
    IFF(ISRC is null OR ARRAY_SIZE(ISRC) <= 1, null, 'ISRC_HAS_MULTIPLE_ITEMS'),
    IFF(ISRC[0] is null, null, IFF(ISRC[0]::string REGEXP '[A-Za-z]{2}-?[0-9A-Za-z]{3}-?\\d{2}-?\\d{5}', null, 'ISRC_NOT_ALLOWED_PATTERN')),
    IFF(TITLE is not null AND ARRAY_SIZE(TITLE) >= 1, null, 'TITLE_REQUIRED'),
    IFF(TITLE is null OR ARRAY_SIZE(TITLE) <= 1, null, 'TITLE_HAS_MULTIPLE_ITEMS'),
    IFF(SUB_TITLE is null OR ARRAY_SIZE(SUB_TITLE) <= 1, null, 'SUB_TITLE_HAS_MULTIPLE_ITEMS'),
    IFF(DISPLAY_ARTIST_NAME is null OR ARRAY_SIZE(DISPLAY_ARTIST_NAME) <= 1, null, 'DISPLAY_ARTIST_NAME_HAS_MULTIPLE_ITEMS'),
    IFF(DISPLAY_ARTIST_PARTY_ID is null OR ARRAY_SIZE(DISPLAY_ARTIST_PARTY_ID) <= 1, null, 'DISPLAY_ARTIST_PARTY_ID_HAS_MULTIPLE_ITEMS'),
    IFF(DISPLAY_ARTIST_PARTY_ID[0] is null, null, IFF(DISPLAY_ARTIST_PARTY_ID[0]::string REGEXP 'INSI::\\d{16}', null, 'DISPLAY_ARTIST_PARTY_ID_NOT_ALLOWED_PATTERN')),
    IFF(DURATION is null OR ARRAY_SIZE(DURATION) <= 1, null, 'DURATION_HAS_MULTIPLE_ITEMS'),
    IFF(DURATION[0] is null, null, IFF(DURATION[0]::string REGEXP 'PT((\\d+H)?\\d+M)?\\d+(\.\\d+)?S', null, 'DURATION_NOT_ALLOWED_PATTERN')),
    IFF(RESOURCE_TYPE is not null AND ARRAY_SIZE(RESOURCE_TYPE) >= 1, null, 'RESOURCE_TYPE_REQUIRED'),
    IFF(RESOURCE_TYPE is null OR ARRAY_SIZE(RESOURCE_TYPE) <= 1, null, 'RESOURCE_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(RESOURCE_TYPE[0] is null, null, IFF(is_resource_type(RESOURCE_TYPE[0]::string), null, 'RESOURCE_TYPE_NOT_ALLOWED_VALUE')),
    IFF(IS_MASTER_RECORDING is null OR ARRAY_SIZE(IS_MASTER_RECORDING) <= 1, null, 'IS_MASTER_RECORDING_HAS_MULTIPLE_ITEMS'),
    IFF(IS_MASTER_RECORDING[0] is null, null, IFF(RLIKE(IS_MASTER_RECORDING[0]::string, '(true|false|yes|no|y|n|0|1)', 'i'), null, 'IS_MASTER_RECORDING_NOT_BOOLEAN'))
  )
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_12.AS01_01;


CREATE OR REPLACE VIEW AS02_02_VALIDATION (
  ASSET_ID,
  LINE_INDEX,
  RECORD_TYPE,
  VIOLATIONS
) AS SELECT
  ASSET_ID,
  LINE_INDEX,
  'AS02.02',
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, 'RECORD_TYPE_REQUIRED'),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, 'RECORD_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('AS02.02'), null, 'RECORD_TYPE_NOT_ALLOWED_VALUE')),
    IFF(BLOCK_ID is not null AND ARRAY_SIZE(BLOCK_ID) >= 1, null, 'BLOCK_ID_REQUIRED'),
    IFF(BLOCK_ID is null OR ARRAY_SIZE(BLOCK_ID) <= 1, null, 'BLOCK_ID_HAS_MULTIPLE_ITEMS'),
    IFF(RESOURCE_REFERENCE is not null AND ARRAY_SIZE(RESOURCE_REFERENCE) >= 1, null, 'RESOURCE_REFERENCE_REQUIRED'),
    IFF(RESOURCE_REFERENCE is null OR ARRAY_SIZE(RESOURCE_REFERENCE) <= 1, null, 'RESOURCE_REFERENCE_HAS_MULTIPLE_ITEMS'),
    IFF(DSP_RESOURCE_ID is not null AND ARRAY_SIZE(DSP_RESOURCE_ID) >= 1, null, 'DSP_RESOURCE_ID_REQUIRED'),
    IFF(DSP_RESOURCE_ID is null OR ARRAY_SIZE(DSP_RESOURCE_ID) <= 1, null, 'DSP_RESOURCE_ID_HAS_MULTIPLE_ITEMS'),
    IFF(ISRC is null OR ARRAY_SIZE(ISRC) <= 1, null, 'ISRC_HAS_MULTIPLE_ITEMS'),
    IFF(ISRC[0] is null, null, IFF(ISRC[0]::string REGEXP '[A-Za-z]{2}-?[0-9A-Za-z]{3}-?\\d{2}-?\\d{5}', null, 'ISRC_NOT_ALLOWED_PATTERN')),
    IFF(TITLE is not null AND ARRAY_SIZE(TITLE) >= 1, null, 'TITLE_REQUIRED'),
    IFF(TITLE is null OR ARRAY_SIZE(TITLE) <= 1, null, 'TITLE_HAS_MULTIPLE_ITEMS'),
    IFF(SUB_TITLE is null OR ARRAY_SIZE(SUB_TITLE) <= 1, null, 'SUB_TITLE_HAS_MULTIPLE_ITEMS'),
    IFF(DISPLAY_ARTIST_NAME is null OR ARRAY_SIZE(DISPLAY_ARTIST_NAME) <= 1, null, 'DISPLAY_ARTIST_NAME_HAS_MULTIPLE_ITEMS'),
    IFF(DISPLAY_ARTIST_PARTY_ID is null OR ARRAY_SIZE(DISPLAY_ARTIST_PARTY_ID) <= 1, null, 'DISPLAY_ARTIST_PARTY_ID_HAS_MULTIPLE_ITEMS'),
    IFF(DISPLAY_ARTIST_PARTY_ID[0] is null, null, IFF(DISPLAY_ARTIST_PARTY_ID[0]::string REGEXP 'INSI::\\d{16}', null, 'DISPLAY_ARTIST_PARTY_ID_NOT_ALLOWED_PATTERN')),
    IFF(DURATION is null OR ARRAY_SIZE(DURATION) <= 1, null, 'DURATION_HAS_MULTIPLE_ITEMS'),
    IFF(DURATION[0] is null, null, IFF(DURATION[0]::string REGEXP 'PT((\\d+H)?\\d+M)?\\d+(\.\\d+)?S', null, 'DURATION_NOT_ALLOWED_PATTERN')),
    IFF(RESOURCE_TYPE is not null AND ARRAY_SIZE(RESOURCE_TYPE) >= 1, null, 'RESOURCE_TYPE_REQUIRED'),
    IFF(RESOURCE_TYPE is null OR ARRAY_SIZE(RESOURCE_TYPE) <= 1, null, 'RESOURCE_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(RESOURCE_TYPE[0] is null, null, IFF(is_resource_type(RESOURCE_TYPE[0]::string), null, 'RESOURCE_TYPE_NOT_ALLOWED_VALUE')),
    IFF(ISWC is null OR ARRAY_SIZE(ISWC) <= 1, null, 'ISWC_HAS_MULTIPLE_ITEMS'),
    IFF(ISWC[0] is null, null, IFF(ISWC[0]::string REGEXP 'T\\d{10}', null, 'ISWC_NOT_ALLOWED_PATTERN')),
    IFF(PROPRIETARY_WORK_ID is null OR ARRAY_SIZE(PROPRIETARY_WORK_ID) <= 1, null, 'PROPRIETARY_WORK_ID_HAS_MULTIPLE_ITEMS'),
    IFF(PROPRIETARY_WORK_ID[0] is null, null, IFF(PROPRIETARY_WORK_ID[0]::string REGEXP '\.+::\.+', null, 'PROPRIETARY_WORK_ID_NOT_ALLOWED_PATTERN')),
    IFF(IS_MASTER_RECORDING is null OR ARRAY_SIZE(IS_MASTER_RECORDING) <= 1, null, 'IS_MASTER_RECORDING_HAS_MULTIPLE_ITEMS'),
    IFF(IS_MASTER_RECORDING[0] is null, null, IFF(RLIKE(IS_MASTER_RECORDING[0]::string, '(true|false|yes|no|y|n|0|1)', 'i'), null, 'IS_MASTER_RECORDING_NOT_BOOLEAN'))
  )
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_12.AS02_02;


CREATE OR REPLACE VIEW MW01_01_VALIDATION (
  ASSET_ID,
  LINE_INDEX,
  RECORD_TYPE,
  VIOLATIONS
) AS SELECT
  ASSET_ID,
  LINE_INDEX,
  'MW01.01',
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, 'RECORD_TYPE_REQUIRED'),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, 'RECORD_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('MW01.01'), null, 'RECORD_TYPE_NOT_ALLOWED_VALUE')),
    IFF(BLOCK_ID is not null AND ARRAY_SIZE(BLOCK_ID) >= 1, null, 'BLOCK_ID_REQUIRED'),
    IFF(BLOCK_ID is null OR ARRAY_SIZE(BLOCK_ID) <= 1, null, 'BLOCK_ID_HAS_MULTIPLE_ITEMS'),
    IFF(DSP_WORK_ID is not null AND ARRAY_SIZE(DSP_WORK_ID) >= 1, null, 'DSP_WORK_ID_REQUIRED'),
    IFF(DSP_WORK_ID is null OR ARRAY_SIZE(DSP_WORK_ID) <= 1, null, 'DSP_WORK_ID_HAS_MULTIPLE_ITEMS'),
    IFF(ISWC is null OR ARRAY_SIZE(ISWC) <= 1, null, 'ISWC_HAS_MULTIPLE_ITEMS'),
    IFF(ISWC[0] is null, null, IFF(ISWC[0]::string REGEXP '[A-Za-z]{2}[0-9A-Za-z]{3}\\d{7}', null, 'ISWC_NOT_ALLOWED_PATTERN')),
    IFF(TITLE is not null AND ARRAY_SIZE(TITLE) >= 1, null, 'TITLE_REQUIRED'),
    IFF(TITLE is null OR ARRAY_SIZE(TITLE) <= 1, null, 'TITLE_HAS_MULTIPLE_ITEMS'),
    IFF(SUB_TITLE is null OR ARRAY_SIZE(SUB_TITLE) <= 1, null, 'SUB_TITLE_HAS_MULTIPLE_ITEMS'),
    IFF(DATA_PROVIDER is null OR ARRAY_SIZE(DATA_PROVIDER) <= 1, null, 'DATA_PROVIDER_HAS_MULTIPLE_ITEMS'),
    IFF(PROPRIETARY_WORK_ID is null OR ARRAY_SIZE(PROPRIETARY_WORK_ID) <= 1, null, 'PROPRIETARY_WORK_ID_HAS_MULTIPLE_ITEMS'),
    IFF(PROPRIETARY_WORK_ID[0] is null, null, IFF(PROPRIETARY_WORK_ID[0]::string REGEXP '\.+::\.+', null, 'PROPRIETARY_WORK_ID_NOT_ALLOWED_PATTERN'))
  )
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_12.MW01_01;


CREATE OR REPLACE VIEW SU01_VALIDATION (
  ASSET_ID,
  LINE_INDEX,
  RECORD_TYPE,
  VIOLATIONS
) AS SELECT
  ASSET_ID,
  LINE_INDEX,
  'SU01',
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, 'RECORD_TYPE_REQUIRED'),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, 'RECORD_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('SU01'), null, 'RECORD_TYPE_NOT_ALLOWED_VALUE')),
    IFF(BLOCK_ID is not null AND ARRAY_SIZE(BLOCK_ID) >= 1, null, 'BLOCK_ID_REQUIRED'),
    IFF(BLOCK_ID is null OR ARRAY_SIZE(BLOCK_ID) <= 1, null, 'BLOCK_ID_HAS_MULTIPLE_ITEMS'),
    IFF(SUMMARY_RECORD_ID is not null AND ARRAY_SIZE(SUMMARY_RECORD_ID) >= 1, null, 'SUMMARY_RECORD_ID_REQUIRED'),
    IFF(SUMMARY_RECORD_ID is null OR ARRAY_SIZE(SUMMARY_RECORD_ID) <= 1, null, 'SUMMARY_RECORD_ID_HAS_MULTIPLE_ITEMS'),
    IFF(SALES_TRANSACTION_ID is not null AND ARRAY_SIZE(SALES_TRANSACTION_ID) >= 1, null, 'SALES_TRANSACTION_ID_REQUIRED'),
    IFF(SALES_TRANSACTION_ID is null OR ARRAY_SIZE(SALES_TRANSACTION_ID) <= 1, null, 'SALES_TRANSACTION_ID_HAS_MULTIPLE_ITEMS'),
    IFF(TRANSACTED_RELEASE is null OR ARRAY_SIZE(TRANSACTED_RELEASE) <= 1, null, 'TRANSACTED_RELEASE_HAS_MULTIPLE_ITEMS'),
    IFF(TRANSACTED_RESOURCE is null OR ARRAY_SIZE(TRANSACTED_RESOURCE) <= 1, null, 'TRANSACTED_RESOURCE_HAS_MULTIPLE_ITEMS'),
    IFF(IS_ROYALTY_BEARING is not null AND ARRAY_SIZE(IS_ROYALTY_BEARING) >= 1, null, 'IS_ROYALTY_BEARING_REQUIRED'),
    IFF(IS_ROYALTY_BEARING is null OR ARRAY_SIZE(IS_ROYALTY_BEARING) <= 1, null, 'IS_ROYALTY_BEARING_HAS_MULTIPLE_ITEMS'),
    IFF(IS_ROYALTY_BEARING[0] is null, null, IFF(RLIKE(IS_ROYALTY_BEARING[0]::string, '(true|false|yes|no|y|n|0|1)', 'i'), null, 'IS_ROYALTY_BEARING_NOT_BOOLEAN')),
    IFF(SALES_UPGRADE is not null AND ARRAY_SIZE(SALES_UPGRADE) >= 1, null, 'SALES_UPGRADE_REQUIRED'),
    IFF(SALES_UPGRADE is null OR ARRAY_SIZE(SALES_UPGRADE) <= 1, null, 'SALES_UPGRADE_HAS_MULTIPLE_ITEMS'),
    IFF(SALES_UPGRADE[0] is null, null, IFF(RLIKE(SALES_UPGRADE[0]::string, '(true|false|yes|no|y|n|0|1)', 'i'), null, 'SALES_UPGRADE_NOT_BOOLEAN')),
    IFF(USAGES is not null AND ARRAY_SIZE(USAGES) >= 1, null, 'USAGES_REQUIRED'),
    IFF(USAGES is null OR ARRAY_SIZE(USAGES) <= 1, null, 'USAGES_HAS_MULTIPLE_ITEMS'),
    IFF(USAGES[0] is null, null, IFF(USAGES[0]::string REGEXP '\\d+', null, 'USAGES_NOT_INTEGER')),
    IFF(RETURNS is not null AND ARRAY_SIZE(RETURNS) >= 1, null, 'RETURNS_REQUIRED'),
    IFF(RETURNS is null OR ARRAY_SIZE(RETURNS) <= 1, null, 'RETURNS_HAS_MULTIPLE_ITEMS'),
    IFF(RETURNS[0] is null, null, IFF(RETURNS[0]::string REGEXP '\\d+', null, 'RETURNS_NOT_INTEGER')),
    IFF(PRICE_CONSUMER_PAID_EXC_SALES_TAX is null OR ARRAY_SIZE(PRICE_CONSUMER_PAID_EXC_SALES_TAX) <= 1, null, 'PRICE_CONSUMER_PAID_EXC_SALES_TAX_HAS_MULTIPLE_ITEMS'),
    IFF(PRICE_CONSUMER_PAID_EXC_SALES_TAX[0] is null, null, IFF(PRICE_CONSUMER_PAID_EXC_SALES_TAX[0]::string REGEXP '\\d+(\.\\d+)?', null, 'PRICE_CONSUMER_PAID_EXC_SALES_TAX_NOT_DECIMAL')),
    IFF(PROMOTIONAL_ACTIVITY is null OR ARRAY_SIZE(PROMOTIONAL_ACTIVITY) <= 1, null, 'PROMOTIONAL_ACTIVITY_HAS_MULTIPLE_ITEMS')
  )
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_12.SU01;


CREATE OR REPLACE VIEW SU02_VALIDATION (
  ASSET_ID,
  LINE_INDEX,
  RECORD_TYPE,
  VIOLATIONS
) AS SELECT
  ASSET_ID,
  LINE_INDEX,
  'SU02',
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, 'RECORD_TYPE_REQUIRED'),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, 'RECORD_TYPE_HAS_MULTIPLE_ITEMS'),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('SU02'), null, 'RECORD_TYPE_NOT_ALLOWED_VALUE')),
    IFF(BLOCK_ID is not null AND ARRAY_SIZE(BLOCK_ID) >= 1, null, 'BLOCK_ID_REQUIRED'),
    IFF(BLOCK_ID is null OR ARRAY_SIZE(BLOCK_ID) <= 1, null, 'BLOCK_ID_HAS_MULTIPLE_ITEMS'),
    IFF(SUMMARY_RECORD_ID is not null AND ARRAY_SIZE(SUMMARY_RECORD_ID) >= 1, null, 'SUMMARY_RECORD_ID_REQUIRED'),
    IFF(SUMMARY_RECORD_ID is null OR ARRAY_SIZE(SUMMARY_RECORD_ID) <= 1, null, 'SUMMARY_RECORD_ID_HAS_MULTIPLE_ITEMS'),
    IFF(SALES_TRANSACTION_ID is not null AND ARRAY_SIZE(SALES_TRANSACTION_ID) >= 1, null, 'SALES_TRANSACTION_ID_REQUIRED'),
    IFF(SALES_TRANSACTION_ID is null OR ARRAY_SIZE(SALES_TRANSACTION_ID) <= 1, null, 'SALES_TRANSACTION_ID_HAS_MULTIPLE_ITEMS'),
    IFF(TRANSACTED_RELEASE is null OR ARRAY_SIZE(TRANSACTED_RELEASE) <= 1, null, 'TRANSACTED_RELEASE_HAS_MULTIPLE_ITEMS'),
    IFF(TRANSACTED_RESOURCE is null OR ARRAY_SIZE(TRANSACTED_RESOURCE) <= 1, null, 'TRANSACTED_RESOURCE_HAS_MULTIPLE_ITEMS'),
    IFF(IS_ROYALTY_BEARING is null OR ARRAY_SIZE(IS_ROYALTY_BEARING) <= 1, null, 'IS_ROYALTY_BEARING_HAS_MULTIPLE_ITEMS'),
    IFF(IS_ROYALTY_BEARING[0] is null, null, IFF(RLIKE(IS_ROYALTY_BEARING[0]::string, '(true|false|yes|no|y|n|0|1)', 'i'), null, 'IS_ROYALTY_BEARING_NOT_BOOLEAN')),
    IFF(NUMBER_OF_STREAMS is not null AND ARRAY_SIZE(NUMBER_OF_STREAMS) >= 1, null, 'NUMBER_OF_STREAMS_REQUIRED'),
    IFF(NUMBER_OF_STREAMS is null OR ARRAY_SIZE(NUMBER_OF_STREAMS) <= 1, null, 'NUMBER_OF_STREAMS_HAS_MULTIPLE_ITEMS'),
    IFF(NUMBER_OF_STREAMS[0] is null, null, IFF(NUMBER_OF_STREAMS[0]::string REGEXP '\\d+(\.\\d+)?', null, 'NUMBER_OF_STREAMS_NOT_DECIMAL')),
    IFF(PRICE_CONSUMER_PAID_EXC_SALES_TAX is null OR ARRAY_SIZE(PRICE_CONSUMER_PAID_EXC_SALES_TAX) <= 1, null, 'PRICE_CONSUMER_PAID_EXC_SALES_TAX_HAS_MULTIPLE_ITEMS'),
    IFF(PRICE_CONSUMER_PAID_EXC_SALES_TAX[0] is null, null, IFF(PRICE_CONSUMER_PAID_EXC_SALES_TAX[0]::string REGEXP '\\d+(\.\\d+)?', null, 'PRICE_CONSUMER_PAID_EXC_SALES_TAX_NOT_DECIMAL')),
    IFF(PROMOTIONAL_ACTIVITY is null OR ARRAY_SIZE(PROMOTIONAL_ACTIVITY) <= 1, null, 'PROMOTIONAL_ACTIVITY_HAS_MULTIPLE_ITEMS')
  )
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_12.SU02;


CREATE OR REPLACE VIEW RECORD_VALIDATION (
  ASSET_ID,
  LINE_INDEX,
  RECORD_TYPE,
  VIOLATIONS
) AS
SELECT ASSET_ID, LINE_INDEX, RECORD_TYPE, VIOLATIONS FROM HEAD_VALIDATION WHERE ARRAY_SIZE(VIOLATIONS) > 0
UNION
SELECT ASSET_ID, LINE_INDEX, RECORD_TYPE, VIOLATIONS FROM FOOT_VALIDATION WHERE ARRAY_SIZE(VIOLATIONS) > 0
UNION
SELECT ASSET_ID, LINE_INDEX, RECORD_TYPE, VIOLATIONS FROM SY01_01_VALIDATION WHERE ARRAY_SIZE(VIOLATIONS) > 0
UNION
SELECT ASSET_ID, LINE_INDEX, RECORD_TYPE, VIOLATIONS FROM SY02_02_VALIDATION WHERE ARRAY_SIZE(VIOLATIONS) > 0
UNION
SELECT ASSET_ID, LINE_INDEX, RECORD_TYPE, VIOLATIONS FROM SY04_01_VALIDATION WHERE ARRAY_SIZE(VIOLATIONS) > 0
UNION
SELECT ASSET_ID, LINE_INDEX, RECORD_TYPE, VIOLATIONS FROM SY05_02_VALIDATION WHERE ARRAY_SIZE(VIOLATIONS) > 0
UNION
SELECT ASSET_ID, LINE_INDEX, RECORD_TYPE, VIOLATIONS FROM RE01_VALIDATION WHERE ARRAY_SIZE(VIOLATIONS) > 0
UNION
SELECT ASSET_ID, LINE_INDEX, RECORD_TYPE, VIOLATIONS FROM RE02_VALIDATION WHERE ARRAY_SIZE(VIOLATIONS) > 0
UNION
SELECT ASSET_ID, LINE_INDEX, RECORD_TYPE, VIOLATIONS FROM AS01_01_VALIDATION WHERE ARRAY_SIZE(VIOLATIONS) > 0
UNION
SELECT ASSET_ID, LINE_INDEX, RECORD_TYPE, VIOLATIONS FROM AS02_02_VALIDATION WHERE ARRAY_SIZE(VIOLATIONS) > 0
UNION
SELECT ASSET_ID, LINE_INDEX, RECORD_TYPE, VIOLATIONS FROM MW01_01_VALIDATION WHERE ARRAY_SIZE(VIOLATIONS) > 0
UNION
SELECT ASSET_ID, LINE_INDEX, RECORD_TYPE, VIOLATIONS FROM SU01_VALIDATION WHERE ARRAY_SIZE(VIOLATIONS) > 0
UNION
SELECT ASSET_ID, LINE_INDEX, RECORD_TYPE, VIOLATIONS FROM SU02_VALIDATION WHERE ARRAY_SIZE(VIOLATIONS) > 0;


