use database %ENV%_DDEX_DSR;

CREATE OR REPLACE SCHEMA BASIC_AUDIO_PROFILE;

use schema BASIC_AUDIO_PROFILE;

CREATE OR REPLACE VIEW MESSAGE (
  ASSET_ID,
  LINE_INDEX,
  RECORD_TYPE,
  MESSAGE_ID,
  MESSAGE_VERSION,
  MESSAGE_CREATED_DATE_TIME,
  PROFILE,
  PROFILE_VERSION,
  FILE_NUMBER,
  NUMBER_OF_FILES,
  USAGE_START_DATE,
  USAGE_END_DATE,
  SERVICE_DESCRIPTION,
  SENDER_NAME,
  SENDER_PARTY_ID,
  RECIPIENT_NAME,
  RECIPIENT_PARTY_ID,
  REPRESENTED_REPERTOIRE
) AS
SELECT
    ASSET_ID,
    LINE_INDEX,
    RECORD_TYPE,
    MESSAGE_ID,
    MESSAGE_VERSION,
    MESSAGE_CREATED_DATE_TIME,
    PROFILE,
    PROFILE_VERSION,
    FILE_NUMBER,
    NUMBER_OF_FILES,
    USAGE_START_DATE,
    USAGE_END_DATE,
    SERVICE_DESCRIPTION,
    SENDER_NAME,
    SENDER_PARTY_ID,
    RECIPIENT_NAME,
    RECIPIENT_PARTY_ID,
    REPRESENTED_REPERTOIRE
FROM TYPED_BAP_MRB_11.HEAD
UNION ALL
SELECT
    ASSET_ID,
    LINE_INDEX,
    RECORD_TYPE,
    MESSAGE_ID,
    MESSAGE_VERSION,
    MESSAGE_CREATED_DATE_TIME,
    PROFILE,
    PROFILE_VERSION,
    FILE_NUMBER,
    NUMBER_OF_FILES,
    USAGE_START_DATE,
    USAGE_END_DATE,
    SERVICE_DESCRIPTION,
    SENDER_NAME,
    SENDER_PARTY_ID,
    RECIPIENT_NAME,
    RECIPIENT_PARTY_ID,
    REPRESENTED_REPERTOIRE
FROM TYPED_BAP_MRB_12.HEAD
UNION ALL
SELECT
    ASSET_ID,
    LINE_INDEX,
    RECORD_TYPE,
    MESSAGE_ID,
    MESSAGE_VERSION,
    MESSAGE_CREATED_DATE_TIME,
    PROFILE,
    PROFILE_VERSION,
    FILE_NUMBER,
    NUMBER_OF_FILES,
    USAGE_START_DATE,
    USAGE_END_DATE,
    SERVICE_DESCRIPTION,
    SENDER_NAME,
    SENDER_PARTY_ID,
    RECIPIENT_NAME,
    RECIPIENT_PARTY_ID,
    REPRESENTED_REPERTOIRE
FROM TYPED_BAP_MRB_13.HEAD;

-- SY01* ONLY
CREATE OR REPLACE VIEW SUMMARY (
  ASSET_ID,
  LINE_INDEX,
  RECORD_TYPE,
  SUMMARY_RECORD_ID,
  DISTRIBUTION_CHANNEL,
  DISTRIBUTION_CHANNEL_DPID,
  COMMERCIAL_MODEL,
  USE_TYPE,
  TERRITORY,
  SERVICE_DESCRIPTION,
  TOTAL_USAGES,
  SUBSCRIBERS,
  CURRENCY_OF_REPORTING,
  NET_REVENUE,
  INDIRECT_VALUE,
  CURRENCY_OF_TRANSACTION,
  EXCHANGE_RATE
) AS
SELECT
    ASSET_ID,
    LINE_INDEX,
    RECORD_TYPE,
    SUMMARY_RECORD_ID,
    DISTRIBUTION_CHANNEL,
    DISTRIBUTION_CHANNEL_DPID,
    COMMERCIAL_MODEL,
    USE_TYPE,
    TERRITORY,
    SERVICE_DESCRIPTION,
    USAGES,
    SUBSCRIBERS,
    CURRENCY_OF_REPORTING,
    NET_REVENUE,
    INDIRECT_NET_REVENUE,
    NULL,
    NULL
FROM TYPED_BAP_MRB_11.SY01
UNION ALL
SELECT
    ASSET_ID,
    LINE_INDEX,
    RECORD_TYPE,
    SUMMARY_RECORD_ID,
    DISTRIBUTION_CHANNEL,
    DISTRIBUTION_CHANNEL_DPID,
    COMMERCIAL_MODEL,
    USE_TYPE,
    TERRITORY,
    SERVICE_DESCRIPTION,
    USAGES,
    SUBSCRIBERS,
    CURRENCY_OF_REPORTING,
    NET_REVENUE,
    INDIRECT_NET_REVENUE,
    CURRENCY_OF_TRANSACTION,
    EXCHANGE_RATE
FROM TYPED_BAP_MRB_12.SY01_01
UNION ALL
SELECT
    ASSET_ID,
    LINE_INDEX,
    RECORD_TYPE,
    SUMMARY_RECORD_ID,
    DISTRIBUTION_CHANNEL,
    DISTRIBUTION_CHANNEL_DPID,
    COMMERCIAL_MODEL,
    USE_TYPE,
    TERRITORY,
    SERVICE_DESCRIPTION,
    TOTAL_USAGES,
    SUBSCRIBERS,
    CURRENCY_OF_REPORTING,
    NET_REVENUE,
    INDIRECT_VALUE,
    CURRENCY_OF_TRANSACTION,
    EXCHANGE_RATE
FROM TYPED_BAP_MRB_13.SY01_02;

-- AS02* ONLY
CREATE OR REPLACE VIEW RESOURCE (
  ASSET_ID,
  LINE_INDEX,
  RECORD_TYPE,
  BLOCK_ID,
  RESOURCE_REFERENCE,
  DSP_RESOURCE_ID,
  RESOURCE_ISRC,
  RESOURCE_TITLE,
  RESOURCE_SUB_TITLE,
  RESOURCE_DISPLAY_ARTIST_NAME,
  RESOURCE_DISPLAY_ARTIST_PARTY_ID,
  RESOURCE_DURATION,
  RESOURCE_TYPE,
  IS_MASTER_RECORDING,
  IS_SUBJECT_TO_OWNERSHIP_CONFLICT,
  LAST_CONFLICT_CHECK
) AS
SELECT
    ASSET_ID,
    LINE_INDEX,
    RECORD_TYPE,
    BLOCK_ID,
    RESOURCE_REFERENCE,
    DSP_RESOURCE_ID,
    ISRC,
    TITLE,
    SUB_TITLE,
    DISPLAY_ARTIST_NAME,
    DISPLAY_ARTIST_PARTY_ID,
    DURATION,
    RESOURCE_TYPE,
    NULL,
    NULL,
    NULL
FROM TYPED_BAP_MRB_11.AS02_01
UNION ALL
SELECT
    ASSET_ID,
    LINE_INDEX,
    RECORD_TYPE,
    BLOCK_ID,
    RESOURCE_REFERENCE,
    DSP_RESOURCE_ID,
    ISRC,
    TITLE,
    SUB_TITLE,
    DISPLAY_ARTIST_NAME,
    DISPLAY_ARTIST_PARTY_ID,
    DURATION,
    RESOURCE_TYPE,
    IS_MASTER_RECORDING,
    NULL,
    NULL
FROM TYPED_BAP_MRB_12.AS02_02
UNION ALL
SELECT
    ASSET_ID,
    LINE_INDEX,
    RECORD_TYPE,
    BLOCK_ID,
    RESOURCE_REFERENCE,
    DSP_RESOURCE_ID,
    RESOURCE_ISRC,
    RESOURCE_TITLE,
    RESOURCE_SUB_TITLE,
    RESOURCE_DISPLAY_ARTIST_NAME,
    RESOURCE_DISPLAY_ARTIST_PARTY_ID,
    RESOURCE_DURATION,
    RESOURCE_TYPE,
    IS_MASTER_RECORDING,
    IS_SUBJECT_TO_OWNERSHIP_CONFLICT,
    LAST_CONFLICT_CHECK
FROM TYPED_BAP_MRB_13.AS02_03;

-- RE01* ONLY
CREATE OR REPLACE VIEW RELEASE (
  ASSET_ID,
  LINE_INDEX,
  RECORD_TYPE,
  BLOCK_ID,
  RELEASE_REFERENCE,
  DSP_RELEASE_ID,
  PROPRIETARY_RELEASE_ID,
  RELEASE_CATALOG_NUMBER,
  RELEASE_ICPN,
  RELEASE_DISPLAY_ARTIST_NAME,
  RELEASE_DISPLAY_ARTIST_PARTY_ID,
  RELEASE_TITLE,
  RELEASE_SUB_TITLE,
  RELEASE_TYPE,
  RELEASE_LABEL_NAME,
  RELEASE_P_LINE,
  DATA_PROVIDER_NAME,
  RELEASE_DATE
) AS
SELECT
    ASSET_ID,
    LINE_INDEX,
    RECORD_TYPE,
    BLOCK_ID,
    RELEASE_REFERENCE,
    DSP_RELEASE_ID,
    PROPRIETARY_RELEASE_ID,
    CATALOG_NUMBER,
    ICPN,
    DISPLAY_ARTIST_NAME,
    DISPLAY_ARTIST_PARTY_ID,
    TITLE,
    SUB_TITLE,
    RELEASE_TYPE,
    LABEL,
    P_LINE,
    DATA_PROVIDER,
    NULL
FROM TYPED_BAP_MRB_11.RE01
UNION ALL
SELECT
    ASSET_ID,
    LINE_INDEX,
    RECORD_TYPE,
    BLOCK_ID,
    RELEASE_REFERENCE,
    DSP_RELEASE_ID,
    PROPRIETARY_RELEASE_ID,
    CATALOG_NUMBER,
    ICPN,
    DISPLAY_ARTIST_NAME,
    DISPLAY_ARTIST_PARTY_ID,
    TITLE,
    SUB_TITLE,
    RELEASE_TYPE,
    LABEL,
    P_LINE,
    DATA_PROVIDER,
    NULL
FROM TYPED_BAP_MRB_12.RE01
UNION ALL
SELECT
    ASSET_ID,
    LINE_INDEX,
    RECORD_TYPE,
    BLOCK_ID,
    RELEASE_REFERENCE,
    DSP_RELEASE_ID,
    PROPRIETARY_RELEASE_ID,
    RELEASE_CATALOG_NUMBER,
    RELEASE_ICPN,
    RELEASE_DISPLAY_ARTIST_NAME,
    RELEASE_DISPLAY_ARTIST_PARTY_ID,
    RELEASE_TITLE,
    RELEASE_SUB_TITLE,
    RELEASE_TYPE,
    RELEASE_LABEL_NAME,
    RELEASE_P_LINE,
    DATA_PROVIDER_NAME,
    RELEASE_DATE
FROM TYPED_BAP_MRB_13.RE01_02;

-- AS02* ONLY
CREATE OR REPLACE VIEW MUSICAL_WORK (
  ASSET_ID,
  LINE_INDEX,
  RECORD_TYPE,
  BLOCK_ID,
  DSP_MUSICAL_WORK_ID,
  MUSICAL_WORK_ISWC,
  MUSICAL_WORK_TITLE,
  MUSICAL_WORK_SUB_TITLE,
  MUSICAL_WORK_COMPOSER_AUTHOR_NAME,
  MUSICAL_WORK_COMPOSER_AUTHOR_PARTY_ID,
  MUSICAL_WORK_ARRANGER_NAME,
  MUSICAL_WORK_ARRANGER_PARTY_ID,
  MUSIC_PUBLISHER_NAME,
  MUSIC_PUBLISHER_PARTY_ID,
  MUSICAL_WORK_CONTRIBUTOR_NAME,
  MUSICAL_WORK_CONTRIBUTOR_PARTY_ID,
  DATA_PROVIDER_NAME,
  PROPRIETARY_MUSICAL_WORK_ID,
  RESOURCE_REFERENCE,
  PARENT_LICENSOR_DATA_RECORD_ID,
  PARENT_MASTERLIST_ID
) AS
SELECT
    ASSET_ID,
    LINE_INDEX,
    RECORD_TYPE,
    BLOCK_ID,
    NULL,
    ISWC,
    NULL,
    NULL,
    COMPOSER_AUTHOR,
    COMPOSER_AUTHOR_PARTY_ID,
    ARRANGER,
    ARRANGER_PARTY_ID,
    MUSIC_PUBLISHER,
    MUSIC_PUBLISHER_PARTY_ID,
    WORK_CONTRIBUTOR,
    WORK_CONTRIBUTOR_PARTY_ID,
    NULL,
    ARRAY_CONSTRUCT_COMPACT(PROPRIETARY_WORK_ID),
    RESOURCE_REFERENCE,
    NULL,
    NULL
FROM TYPED_BAP_MRB_11.AS02_01
UNION ALL
SELECT
    ASSET_ID,
    LINE_INDEX,
    RECORD_TYPE,
    BLOCK_ID,
    NULL,
    ISWC,
    NULL,
    NULL,
    COMPOSER_AUTHOR,
    COMPOSER_AUTHOR_PARTY_ID,
    ARRANGER,
    ARRANGER_PARTY_ID,
    MUSIC_PUBLISHER,
    MUSIC_PUBLISHER_PARTY_ID,
    WORK_CONTRIBUTOR,
    WORK_CONTRIBUTOR_PARTY_ID,
    NULL,
    ARRAY_CONSTRUCT_COMPACT(PROPRIETARY_WORK_ID),
    RESOURCE_REFERENCE,
    NULL,
    NULL
FROM TYPED_BAP_MRB_12.AS02_02
UNION ALL
SELECT
    ASSET_ID,
    LINE_INDEX,
    RECORD_TYPE,
    BLOCK_ID,
    NULL,
    MUSICAL_WORK_ISWC,
    NULL,
    NULL,
    MUSICAL_WORK_COMPOSER_AUTHOR_NAME,
    MUSICAL_WORK_COMPOSER_AUTHOR_PARTY_ID,
    MUSICAL_WORK_ARRANGER_NAME,
    MUSICAL_WORK_ARRANGER_PARTY_ID,
    MUSIC_PUBLISHER_NAME,
    MUSIC_PUBLISHER_PARTY_ID,
    MUSICAL_WORK_CONTRIBUTOR_NAME,
    MUSICAL_WORK_CONTRIBUTOR_PARTY_ID,
    NULL,
    PROPRIETARY_MUSICAL_WORK_ID,
    RESOURCE_REFERENCE,
    NULL,
    NULL
FROM TYPED_BAP_MRB_13.AS02_03;

-- SU02* ONLY
CREATE OR REPLACE VIEW SALE_USAGE (
  ASSET_ID,
  LINE_INDEX,
  RECORD_TYPE,
  BLOCK_ID,
  SUMMARY_RECORD_ID,
  SALES_TRANSACTION_ID,
  TRANSACTED_RELEASE,
  TRANSACTED_RESOURCE,
  IS_ROYALTY_BEARING,
  NUMBER_OF_STREAMS,
  PRICE_CONSUMER_PAID_EXC_SALES_TAX,
  PROMOTIONAL_ACTIVITY,
  USE_TYPE
) AS
SELECT
    ASSET_ID,
    LINE_INDEX,
    RECORD_TYPE,
    BLOCK_ID,
    SUMMARY_RECORD_ID,
    SALES_TRANSACTION_ID,
    TRANSACTED_RELEASE,
    TRANSACTED_RESOURCE,
    IS_ROYALTY_BEARING,
    NUMBER_OF_STREAMS,
    PRICE_CONSUMER_PAID_EXC_SALES_TAX,
    PROMOTIONAL_ACTIVITY,
    NULL
FROM TYPED_BAP_MRB_11.SU02
UNION ALL
SELECT
    ASSET_ID,
    LINE_INDEX,
    RECORD_TYPE,
    BLOCK_ID,
    SUMMARY_RECORD_ID,
    SALES_TRANSACTION_ID,
    TRANSACTED_RELEASE,
    TRANSACTED_RESOURCE,
    IS_ROYALTY_BEARING,
    NUMBER_OF_STREAMS,
    PRICE_CONSUMER_PAID_EXC_SALES_TAX,
    PROMOTIONAL_ACTIVITY,
    NULL
FROM TYPED_BAP_MRB_12.SU02
UNION ALL
SELECT
    ASSET_ID,
    LINE_INDEX,
    RECORD_TYPE,
    BLOCK_ID,
    SUMMARY_RECORD_ID,
    SALES_TRANSACTION_ID,
    TRANSACTED_RELEASE,
    TRANSACTED_RESOURCE,
    IS_ROYALTY_BEARING,
    NUMBER_OF_STREAMS,
    PRICE_CONSUMER_PAID_EXC_SALES_TAX,
    PROMOTIONAL_ACTIVITY,
    USE_TYPE
FROM TYPED_BAP_MRB_13.SU02_02;