use schema UNTYPED_BAP_MRB_11;

CREATE OR REPLACE TABLE HEAD (
  ASSET_ID  VARCHAR,
  LINE_INDEX VARCHAR,
  RECORD_TYPE ARRAY,
  MESSAGE_VERSION ARRAY,
  PROFILE ARRAY,
  PROFILE_VERSION ARRAY,
  MESSAGE_ID ARRAY,
  MESSAGE_CREATED_DATE_TIME ARRAY,
  FILE_NUMBER ARRAY,
  NUMBER_OF_FILES ARRAY,
  USAGE_START_DATE ARRAY,
  USAGE_END_DATE ARRAY,
  SENDER_PARTY_ID ARRAY,
  SENDER_NAME ARRAY,
  SERVICE_DESCRIPTION ARRAY,
  RECIPIENT_PARTY_ID ARRAY,
  RECIPIENT_NAME ARRAY,
  REPRESENTED_REPERTOIRE ARRAY,
  UNEXPECTED_DATA ARRAY);


CREATE OR REPLACE TABLE FOOT (
  ASSET_ID  VARCHAR,
  LINE_INDEX VARCHAR,
  RECORD_TYPE ARRAY,
  NUMBER_OF_LINES_IN_FILE ARRAY,
  NUMBER_OF_LINES_IN_REPORT ARRAY,
  NUMBER_OF_SUMMARY_RECORDS ARRAY,
  NUMBER_OF_BLOCKS_IN_FILE ARRAY,
  NUMBER_OF_BLOCKS_IN_REPORT ARRAY,
  UNEXPECTED_DATA ARRAY);


CREATE OR REPLACE TABLE SY01 (
  ASSET_ID  VARCHAR,
  LINE_INDEX VARCHAR,
  RECORD_TYPE ARRAY,
  SUMMARY_RECORD_ID ARRAY,
  DISTRIBUTION_CHANNEL ARRAY,
  DISTRIBUTION_CHANNEL_DPID ARRAY,
  COMMERCIAL_MODEL ARRAY,
  USE_TYPE ARRAY,
  TERRITORY ARRAY,
  SERVICE_DESCRIPTION ARRAY,
  USAGES ARRAY,
  SUBSCRIBERS ARRAY,
  CURRENCY_OF_REPORTING ARRAY,
  NET_REVENUE ARRAY,
  INDIRECT_NET_REVENUE ARRAY,
  UNEXPECTED_DATA ARRAY);


CREATE OR REPLACE TABLE SY02_01 (
  ASSET_ID  VARCHAR,
  LINE_INDEX VARCHAR,
  RECORD_TYPE ARRAY,
  SUMMARY_RECORD_ID ARRAY,
  DISTRIBUTION_CHANNEL ARRAY,
  DISTRIBUTION_CHANNEL_DPID ARRAY,
  COMMERCIAL_MODEL ARRAY,
  USE_TYPE ARRAY,
  TERRITORY ARRAY,
  SERVICE_DESCRIPTION ARRAY,
  USAGES ARRAY,
  USERS ARRAY,
  CURRENCY_OF_REPORTING ARRAY,
  NET_REVENUE ARRAY,
  RIGHTS_CONTROLLER ARRAY,
  RIGHTS_CONTROLLER_PARTY_ID ARRAY,
  ALLOCATED_USAGES ARRAY,
  ALLOCATED_REVENUE ARRAY,
  ALLOCATED_NET_REVENUE ARRAY,
  RIGHTS_TYPE ARRAY,
  UNEXPECTED_DATA ARRAY);


CREATE OR REPLACE TABLE SY04 (
  ASSET_ID  VARCHAR,
  LINE_INDEX VARCHAR,
  RECORD_TYPE ARRAY,
  SUMMARY_RECORD_ID ARRAY,
  DISTRIBUTION_CHANNEL ARRAY,
  DISTRIBUTION_CHANNEL_DPID ARRAY,
  COMMERCIAL_MODEL ARRAY,
  USE_TYPE ARRAY,
  TERRITORY ARRAY,
  SERVICE_DESCRIPTION ARRAY,
  SUBSCRIBER_TYPE ARRAY,
  SUBSCRIBERS ARRAY,
  SUB_PERIOD_START_DATE ARRAY,
  SUB_PERIOD_END_DATE ARRAY,
  USAGES_IN_SUB_PERIOD ARRAY,
  USAGES_IN_REPORTING_PERIOD ARRAY,
  CURRENCY_OF_REPORTING ARRAY,
  CURRENCY_OF_TRANSACTION ARRAY,
  EXCHANGE_RATE ARRAY,
  CONSUMER_PAID_UNIT_PRICE ARRAY,
  NET_REVENUE ARRAY,
  UNEXPECTED_DATA ARRAY);


CREATE OR REPLACE TABLE SY05 (
  ASSET_ID  VARCHAR,
  LINE_INDEX VARCHAR,
  RECORD_TYPE ARRAY,
  SUMMARY_RECORD_ID ARRAY,
  DISTRIBUTION_CHANNEL ARRAY,
  DISTRIBUTION_CHANNEL_DPID ARRAY,
  COMMERCIAL_MODEL ARRAY,
  USE_TYPE ARRAY,
  TERRITORY ARRAY,
  SERVICE_DESCRIPTION ARRAY,
  RIGHTS_CONTROLLER ARRAY,
  RIGHTS_CONTROLLER_PARTY_ID ARRAY,
  RIGHTS_TYPE ARRAY,
  TOTAL_USAGES ARRAY,
  ALLOCATED_USAGES ARRAY,
  MUSIC_USAGE_RATIO ARRAY,
  ALLOCATED_NET_REVENUE ARRAY,
  ALLOCATED_REVENUE ARRAY,
  RIGHTS_CONTROLLER_MARKET_SHARE ARRAY,
  UNEXPECTED_DATA ARRAY);


CREATE OR REPLACE TABLE RE01 (
  ASSET_ID  VARCHAR,
  LINE_INDEX VARCHAR,
  RECORD_TYPE ARRAY,
  BLOCK_ID ARRAY,
  RELEASE_REFERENCE ARRAY,
  DSP_RELEASE_ID ARRAY,
  PROPRIETARY_RELEASE_ID ARRAY,
  CATALOG_NUMBER ARRAY,
  ICPN ARRAY,
  DISPLAY_ARTIST_NAME ARRAY,
  DISPLAY_ARTIST_PARTY_ID ARRAY,
  TITLE ARRAY,
  SUB_TITLE ARRAY,
  RELEASE_TYPE ARRAY,
  LABEL ARRAY,
  P_LINE ARRAY,
  DATA_PROVIDER ARRAY,
  UNEXPECTED_DATA ARRAY);


CREATE OR REPLACE TABLE RE02 (
  ASSET_ID  VARCHAR,
  LINE_INDEX VARCHAR,
  RECORD_TYPE ARRAY,
  BLOCK_ID ARRAY,
  RELEASE_REFERENCE ARRAY,
  DSP_SUB_RELEASE_ID ARRAY,
  PROPRIETARY_SUB_RELEASE_ID ARRAY,
  USED_RESOURCES ARRAY,
  UNEXPECTED_DATA ARRAY);


CREATE OR REPLACE TABLE AS01 (
  ASSET_ID  VARCHAR,
  LINE_INDEX VARCHAR,
  RECORD_TYPE ARRAY,
  BLOCK_ID ARRAY,
  RESOURCE_REFERENCE ARRAY,
  DSP_RESOURCE_ID ARRAY,
  ISRC ARRAY,
  TITLE ARRAY,
  SUB_TITLE ARRAY,
  DISPLAY_ARTIST_NAME ARRAY,
  DISPLAY_ARTIST_PARTY_ID ARRAY,
  DURATION ARRAY,
  RESOURCE_TYPE ARRAY,
  UNEXPECTED_DATA ARRAY);


CREATE OR REPLACE TABLE AS02_01 (
  ASSET_ID  VARCHAR,
  LINE_INDEX VARCHAR,
  RECORD_TYPE ARRAY,
  BLOCK_ID ARRAY,
  RESOURCE_REFERENCE ARRAY,
  DSP_RESOURCE_ID ARRAY,
  ISRC ARRAY,
  TITLE ARRAY,
  SUB_TITLE ARRAY,
  DISPLAY_ARTIST_NAME ARRAY,
  DISPLAY_ARTIST_PARTY_ID ARRAY,
  DURATION ARRAY,
  RESOURCE_TYPE ARRAY,
  ISWC ARRAY,
  COMPOSER_AUTHOR ARRAY,
  COMPOSER_AUTHOR_PARTY_ID ARRAY,
  ARRANGER ARRAY,
  ARRANGER_PARTY_ID ARRAY,
  MUSIC_PUBLISHER ARRAY,
  MUSIC_PUBLISHER_PARTY_ID ARRAY,
  WORK_CONTRIBUTOR ARRAY,
  WORK_CONTRIBUTOR_PARTY_ID ARRAY,
  PROPRIETARY_WORK_ID ARRAY,
  UNEXPECTED_DATA ARRAY);


CREATE OR REPLACE TABLE MW01_01 (
  ASSET_ID  VARCHAR,
  LINE_INDEX VARCHAR,
  RECORD_TYPE ARRAY,
  BLOCK_ID ARRAY,
  DSP_WORK_ID ARRAY,
  ISWC ARRAY,
  TITLE ARRAY,
  SUB_TITLE ARRAY,
  COMPOSER_AUTHOR ARRAY,
  COMPOSER_AUTHOR_PARTY_ID ARRAY,
  ARRANGER ARRAY,
  ARRANGER_PARTY_ID ARRAY,
  MUSIC_PUBLISHER ARRAY,
  MUSIC_PUBLISHER_PARTY_ID ARRAY,
  WORK_CONTRIBUTOR ARRAY,
  WORK_CONTRIBUTOR_PARTY_ID ARRAY,
  DATA_PROVIDER ARRAY,
  PROPRIETARY_WORK_ID ARRAY,
  UNEXPECTED_DATA ARRAY);


CREATE OR REPLACE TABLE SU01 (
  ASSET_ID  VARCHAR,
  LINE_INDEX VARCHAR,
  RECORD_TYPE ARRAY,
  BLOCK_ID ARRAY,
  SUMMARY_RECORD_ID ARRAY,
  SALES_TRANSACTION_ID ARRAY,
  TRANSACTED_RELEASE ARRAY,
  TRANSACTED_RESOURCE ARRAY,
  IS_ROYALTY_BEARING ARRAY,
  SALES_UPGRADE ARRAY,
  USAGES ARRAY,
  RETURNS ARRAY,
  PRICE_CONSUMER_PAID_EXC_SALES_TAX ARRAY,
  PROMOTIONAL_ACTIVITY ARRAY,
  UNEXPECTED_DATA ARRAY);


CREATE OR REPLACE TABLE SU02 (
  ASSET_ID  VARCHAR,
  LINE_INDEX VARCHAR,
  RECORD_TYPE ARRAY,
  BLOCK_ID ARRAY,
  SUMMARY_RECORD_ID ARRAY,
  SALES_TRANSACTION_ID ARRAY,
  TRANSACTED_RELEASE ARRAY,
  TRANSACTED_RESOURCE ARRAY,
  IS_ROYALTY_BEARING ARRAY,
  NUMBER_OF_STREAMS ARRAY,
  PRICE_CONSUMER_PAID_EXC_SALES_TAX ARRAY,
  PROMOTIONAL_ACTIVITY ARRAY,
  UNEXPECTED_DATA ARRAY);


CREATE OR REPLACE TABLE UNEXPECTED_RECORD (
  ASSET_ID  VARCHAR,
  LINE_INDEX VARCHAR,
  UNEXPECTED_DATA ARRAY);


