create or replace procedure insert_violations(ASSET_IDS ARRAY)
  returns boolean
  language javascript
  EXECUTE AS CALLER
  as     
  $$
    
var assets = "'" + ASSET_IDS.join("','") + "'";
var useSchema = snowflake.execute({sqlText: 'use schema %ENV%_DDEX_DSR.VALIDATION_BAP_MRB_11'});


var insertViolations_HEAD = snowflake.execute({sqlText: `INSERT INTO VIOLATION (
  ASSET_ID,
  ASSET_PART,
  VIOLATION,
  VIOLATION_DETAIL
) 
WITH
v as (SELECT
  ASSET_ID,
  LINE_INDEX,
  'HEAD' as RECORD_TYPE,
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('HEAD'), null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(MESSAGE_VERSION is not null AND ARRAY_SIZE(MESSAGE_VERSION) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'MESSAGE_VERSION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', MESSAGE_VERSION, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(MESSAGE_VERSION is null OR ARRAY_SIZE(MESSAGE_VERSION) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'MESSAGE_VERSION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', MESSAGE_VERSION, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(MESSAGE_VERSION[0] is null, null, IFF(MESSAGE_VERSION[0]::string REGEXP 'dsrf(\\/30|(\\/\\\\d+(\\.\\\\d+){0,2}){3})', null, OBJECT_CONSTRUCT('FIELD', 'MESSAGE_VERSION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', MESSAGE_VERSION, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(PROFILE is not null AND ARRAY_SIZE(PROFILE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'PROFILE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', PROFILE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(PROFILE is null OR ARRAY_SIZE(PROFILE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'PROFILE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', PROFILE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(PROFILE[0] is null, null, IFF(PROFILE[0]::string REGEXP 'Basic\\\\s*Audio\\\\s*Profile', null, OBJECT_CONSTRUCT('FIELD', 'PROFILE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', PROFILE, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(PROFILE_VERSION is not null AND ARRAY_SIZE(PROFILE_VERSION) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'PROFILE_VERSION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', PROFILE_VERSION, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(PROFILE_VERSION is null OR ARRAY_SIZE(PROFILE_VERSION) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'PROFILE_VERSION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', PROFILE_VERSION, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(PROFILE_VERSION[0] is null, null, IFF(PROFILE_VERSION[0]::string IN ('1.1'), null, OBJECT_CONSTRUCT('FIELD', 'PROFILE_VERSION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', PROFILE_VERSION, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(MESSAGE_ID is not null AND ARRAY_SIZE(MESSAGE_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'MESSAGE_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', MESSAGE_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(MESSAGE_ID is null OR ARRAY_SIZE(MESSAGE_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'MESSAGE_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', MESSAGE_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(MESSAGE_CREATED_DATE_TIME is not null AND ARRAY_SIZE(MESSAGE_CREATED_DATE_TIME) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'MESSAGE_CREATED_DATE_TIME', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', MESSAGE_CREATED_DATE_TIME, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(MESSAGE_CREATED_DATE_TIME is null OR ARRAY_SIZE(MESSAGE_CREATED_DATE_TIME) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'MESSAGE_CREATED_DATE_TIME', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', MESSAGE_CREATED_DATE_TIME, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(MESSAGE_CREATED_DATE_TIME[0] is null, null, 
      IFF(TRY_TO_TIMESTAMP(MESSAGE_CREATED_DATE_TIME[0]::string, 'YYYY-MM-DDTHH24:MI:SSZ') is not null, null, OBJECT_CONSTRUCT('FIELD', 'MESSAGE_CREATED_DATE_TIME', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', MESSAGE_CREATED_DATE_TIME, 'VIOLATION_TYPE', 'NOT_DATETIME'))),
    IFF(FILE_NUMBER is not null AND ARRAY_SIZE(FILE_NUMBER) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'FILE_NUMBER', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', FILE_NUMBER, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(FILE_NUMBER is null OR ARRAY_SIZE(FILE_NUMBER) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'FILE_NUMBER', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', FILE_NUMBER, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(FILE_NUMBER[0] is null, null, IFF(FILE_NUMBER[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'FILE_NUMBER', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', FILE_NUMBER, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(FILE_NUMBER[0] is null, null, IFF(FILE_NUMBER[0]::number >= 1, null, OBJECT_CONSTRUCT('FIELD', 'FILE_NUMBER', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', FILE_NUMBER, 'VIOLATION_TYPE', 'LESS_THAN_MIN_SIZE'))),
    IFF(NUMBER_OF_FILES is not null AND ARRAY_SIZE(NUMBER_OF_FILES) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_FILES', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', NUMBER_OF_FILES, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(NUMBER_OF_FILES is null OR ARRAY_SIZE(NUMBER_OF_FILES) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_FILES', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', NUMBER_OF_FILES, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(NUMBER_OF_FILES[0] is null, null, IFF(NUMBER_OF_FILES[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_FILES', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', NUMBER_OF_FILES, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(NUMBER_OF_FILES[0] is null, null, IFF(NUMBER_OF_FILES[0]::number >= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_FILES', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', NUMBER_OF_FILES, 'VIOLATION_TYPE', 'LESS_THAN_MIN_SIZE'))),
    IFF(USAGE_START_DATE is not null AND ARRAY_SIZE(USAGE_START_DATE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'USAGE_START_DATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', USAGE_START_DATE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(USAGE_START_DATE is null OR ARRAY_SIZE(USAGE_START_DATE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'USAGE_START_DATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', USAGE_START_DATE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(USAGE_START_DATE[0] is null, null, 
      IFF(TRY_TO_DATE(USAGE_START_DATE[0]::string, 'YYYY-MM-DD') is not null, null, 
      IFF(TRY_TO_DATE(USAGE_START_DATE[0]::string, 'YYYY-MM') is not null, null, 
      IFF(TRY_TO_DATE(USAGE_START_DATE[0]::string, 'YYYY') is not null, null, OBJECT_CONSTRUCT('FIELD', 'USAGE_START_DATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', USAGE_START_DATE, 'VIOLATION_TYPE', 'NOT_DATE'))))),
    IFF(USAGE_END_DATE is not null AND ARRAY_SIZE(USAGE_END_DATE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'USAGE_END_DATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', USAGE_END_DATE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(USAGE_END_DATE is null OR ARRAY_SIZE(USAGE_END_DATE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'USAGE_END_DATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', USAGE_END_DATE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(USAGE_END_DATE[0] is null, null, 
      IFF(TRY_TO_DATE(USAGE_END_DATE[0]::string, 'YYYY-MM-DD') is not null, null, 
      IFF(TRY_TO_DATE(USAGE_END_DATE[0]::string, 'YYYY-MM') is not null, null, 
      IFF(TRY_TO_DATE(USAGE_END_DATE[0]::string, 'YYYY') is not null, null, OBJECT_CONSTRUCT('FIELD', 'USAGE_END_DATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', USAGE_END_DATE, 'VIOLATION_TYPE', 'NOT_DATE'))))),
    IFF(SENDER_PARTY_ID is not null AND ARRAY_SIZE(SENDER_PARTY_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'SENDER_PARTY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', SENDER_PARTY_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(SENDER_PARTY_ID is null OR ARRAY_SIZE(SENDER_PARTY_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SENDER_PARTY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', SENDER_PARTY_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SENDER_PARTY_ID[0] is null, null, IFF(SENDER_PARTY_ID[0]::string REGEXP 'PADPIDA[0-9A-Za-z]{11}', null, OBJECT_CONSTRUCT('FIELD', 'SENDER_PARTY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', SENDER_PARTY_ID, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(SENDER_NAME is not null AND ARRAY_SIZE(SENDER_NAME) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'SENDER_NAME', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', SENDER_NAME, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(SENDER_NAME is null OR ARRAY_SIZE(SENDER_NAME) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SENDER_NAME', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', SENDER_NAME, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SERVICE_DESCRIPTION is null OR ARRAY_SIZE(SERVICE_DESCRIPTION) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SERVICE_DESCRIPTION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', SERVICE_DESCRIPTION, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECIPIENT_PARTY_ID is null OR ARRAY_SIZE(RECIPIENT_PARTY_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECIPIENT_PARTY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', RECIPIENT_PARTY_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECIPIENT_PARTY_ID[0] is null, null, IFF(RECIPIENT_PARTY_ID[0]::string REGEXP 'PADPIDA[0-9A-Za-z]{11}', null, OBJECT_CONSTRUCT('FIELD', 'RECIPIENT_PARTY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', RECIPIENT_PARTY_ID, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(RECIPIENT_NAME is null OR ARRAY_SIZE(RECIPIENT_NAME) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECIPIENT_NAME', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'HEAD', 'FIELD_VALUE', RECIPIENT_NAME, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS'))
  ) as VIOLATION_DETAILS
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_11.HEAD
where asset_id in (${assets}))
select asset_id, line_index::varchar as asset_part, concat_ws('::', RECORD_TYPE, GET_PATH(value, 'FIELD')::varchar, GET_PATH(value, 'VIOLATION_TYPE')::varchar) violation, value as violation_details from v, table(flatten(input => v.VIOLATION_DETAILS));`});


var insertViolations_FOOT = snowflake.execute({sqlText: `INSERT INTO VIOLATION (
  ASSET_ID,
  ASSET_PART,
  VIOLATION,
  VIOLATION_DETAIL
) 
WITH
v as (SELECT
  ASSET_ID,
  LINE_INDEX,
  'FOOT' as RECORD_TYPE,
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('FOOT'), null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(NUMBER_OF_LINES_IN_FILE is not null AND ARRAY_SIZE(NUMBER_OF_LINES_IN_FILE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_LINES_IN_FILE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_LINES_IN_FILE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(NUMBER_OF_LINES_IN_FILE is null OR ARRAY_SIZE(NUMBER_OF_LINES_IN_FILE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_LINES_IN_FILE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_LINES_IN_FILE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(NUMBER_OF_LINES_IN_FILE[0] is null, null, IFF(NUMBER_OF_LINES_IN_FILE[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_LINES_IN_FILE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_LINES_IN_FILE, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(NUMBER_OF_LINES_IN_REPORT is null OR ARRAY_SIZE(NUMBER_OF_LINES_IN_REPORT) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_LINES_IN_REPORT', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_LINES_IN_REPORT, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(NUMBER_OF_LINES_IN_REPORT[0] is null, null, IFF(NUMBER_OF_LINES_IN_REPORT[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_LINES_IN_REPORT', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_LINES_IN_REPORT, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(NUMBER_OF_SUMMARY_RECORDS is not null AND ARRAY_SIZE(NUMBER_OF_SUMMARY_RECORDS) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_SUMMARY_RECORDS', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_SUMMARY_RECORDS, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(NUMBER_OF_SUMMARY_RECORDS is null OR ARRAY_SIZE(NUMBER_OF_SUMMARY_RECORDS) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_SUMMARY_RECORDS', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_SUMMARY_RECORDS, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(NUMBER_OF_SUMMARY_RECORDS[0] is null, null, IFF(NUMBER_OF_SUMMARY_RECORDS[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_SUMMARY_RECORDS', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_SUMMARY_RECORDS, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(NUMBER_OF_BLOCKS_IN_FILE is not null AND ARRAY_SIZE(NUMBER_OF_BLOCKS_IN_FILE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_BLOCKS_IN_FILE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_BLOCKS_IN_FILE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(NUMBER_OF_BLOCKS_IN_FILE is null OR ARRAY_SIZE(NUMBER_OF_BLOCKS_IN_FILE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_BLOCKS_IN_FILE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_BLOCKS_IN_FILE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(NUMBER_OF_BLOCKS_IN_FILE[0] is null, null, IFF(NUMBER_OF_BLOCKS_IN_FILE[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_BLOCKS_IN_FILE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_BLOCKS_IN_FILE, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(NUMBER_OF_BLOCKS_IN_REPORT is null OR ARRAY_SIZE(NUMBER_OF_BLOCKS_IN_REPORT) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_BLOCKS_IN_REPORT', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_BLOCKS_IN_REPORT, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(NUMBER_OF_BLOCKS_IN_REPORT[0] is null, null, IFF(NUMBER_OF_BLOCKS_IN_REPORT[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_BLOCKS_IN_REPORT', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'FOOT', 'FIELD_VALUE', NUMBER_OF_BLOCKS_IN_REPORT, 'VIOLATION_TYPE', 'NOT_INTEGER')))
  ) as VIOLATION_DETAILS
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_11.FOOT
where asset_id in (${assets}))
select asset_id, line_index::varchar as asset_part, concat_ws('::', RECORD_TYPE, GET_PATH(value, 'FIELD')::varchar, GET_PATH(value, 'VIOLATION_TYPE')::varchar) violation, value as violation_details from v, table(flatten(input => v.VIOLATION_DETAILS));`});


var insertViolations_SY01 = snowflake.execute({sqlText: `INSERT INTO VIOLATION (
  ASSET_ID,
  ASSET_PART,
  VIOLATION,
  VIOLATION_DETAIL
) 
WITH
v as (SELECT
  ASSET_ID,
  LINE_INDEX,
  'SY01' as RECORD_TYPE,
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('SY01'), null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(SUMMARY_RECORD_ID is not null AND ARRAY_SIZE(SUMMARY_RECORD_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUMMARY_RECORD_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', SUMMARY_RECORD_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(SUMMARY_RECORD_ID is null OR ARRAY_SIZE(SUMMARY_RECORD_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUMMARY_RECORD_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', SUMMARY_RECORD_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISTRIBUTION_CHANNEL is null OR ARRAY_SIZE(DISTRIBUTION_CHANNEL) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DISTRIBUTION_CHANNEL', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', DISTRIBUTION_CHANNEL, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISTRIBUTION_CHANNEL_DPID is null OR ARRAY_SIZE(DISTRIBUTION_CHANNEL_DPID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DISTRIBUTION_CHANNEL_DPID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', DISTRIBUTION_CHANNEL_DPID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISTRIBUTION_CHANNEL_DPID[0] is null, null, IFF(DISTRIBUTION_CHANNEL_DPID[0]::string REGEXP 'PADPIDA[0-9A-Za-z]{11}', null, OBJECT_CONSTRUCT('FIELD', 'DISTRIBUTION_CHANNEL_DPID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', DISTRIBUTION_CHANNEL_DPID, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(COMMERCIAL_MODEL is not null AND ARRAY_SIZE(COMMERCIAL_MODEL) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'COMMERCIAL_MODEL', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', COMMERCIAL_MODEL, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(COMMERCIAL_MODEL is null OR ARRAY_SIZE(COMMERCIAL_MODEL) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'COMMERCIAL_MODEL', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', COMMERCIAL_MODEL, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(COMMERCIAL_MODEL[0] is null, null, IFF(is_commercial_model(COMMERCIAL_MODEL[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'COMMERCIAL_MODEL', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', COMMERCIAL_MODEL, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(USE_TYPE is not null AND ARRAY_SIZE(USE_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'USE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', USE_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(USE_TYPE is null OR ARRAY_SIZE(USE_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'USE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', USE_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(USE_TYPE[0] is null, null, IFF(is_use_type(USE_TYPE[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'USE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', USE_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(TERRITORY is not null AND ARRAY_SIZE(TERRITORY) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'TERRITORY', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', TERRITORY, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(TERRITORY is null OR ARRAY_SIZE(TERRITORY) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'TERRITORY', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', TERRITORY, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(TERRITORY[0] is null, null, IFF(is_territory(TERRITORY[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'TERRITORY', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', TERRITORY, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(SERVICE_DESCRIPTION is null OR ARRAY_SIZE(SERVICE_DESCRIPTION) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SERVICE_DESCRIPTION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', SERVICE_DESCRIPTION, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(USAGES is not null AND ARRAY_SIZE(USAGES) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'USAGES', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', USAGES, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(USAGES is null OR ARRAY_SIZE(USAGES) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'USAGES', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', USAGES, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(USAGES[0] is null, null, IFF(USAGES[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'USAGES', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', USAGES, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(SUBSCRIBERS is null OR ARRAY_SIZE(SUBSCRIBERS) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUBSCRIBERS', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', SUBSCRIBERS, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SUBSCRIBERS[0] is null, null, IFF(SUBSCRIBERS[0]::string REGEXP '\\\\d+(\\.\\\\d+)?', null, OBJECT_CONSTRUCT('FIELD', 'SUBSCRIBERS', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', SUBSCRIBERS, 'VIOLATION_TYPE', 'NOT_DECIMAL'))),
    IFF(CURRENCY_OF_REPORTING is not null AND ARRAY_SIZE(CURRENCY_OF_REPORTING) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'CURRENCY_OF_REPORTING', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', CURRENCY_OF_REPORTING, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(CURRENCY_OF_REPORTING is null OR ARRAY_SIZE(CURRENCY_OF_REPORTING) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'CURRENCY_OF_REPORTING', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', CURRENCY_OF_REPORTING, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(CURRENCY_OF_REPORTING[0] is null, null, IFF(is_currency(CURRENCY_OF_REPORTING[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'CURRENCY_OF_REPORTING', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', CURRENCY_OF_REPORTING, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(NET_REVENUE is not null AND ARRAY_SIZE(NET_REVENUE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'NET_REVENUE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', NET_REVENUE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(NET_REVENUE is null OR ARRAY_SIZE(NET_REVENUE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'NET_REVENUE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', NET_REVENUE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(NET_REVENUE[0] is null, null, IFF(NET_REVENUE[0]::string REGEXP '\\\\d+(\\.\\\\d+)?', null, OBJECT_CONSTRUCT('FIELD', 'NET_REVENUE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', NET_REVENUE, 'VIOLATION_TYPE', 'NOT_DECIMAL'))),
    IFF(INDIRECT_NET_REVENUE is null OR ARRAY_SIZE(INDIRECT_NET_REVENUE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'INDIRECT_NET_REVENUE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', INDIRECT_NET_REVENUE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(INDIRECT_NET_REVENUE[0] is null, null, IFF(INDIRECT_NET_REVENUE[0]::string REGEXP '\\\\d+(\\.\\\\d+)?', null, OBJECT_CONSTRUCT('FIELD', 'INDIRECT_NET_REVENUE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY01', 'FIELD_VALUE', INDIRECT_NET_REVENUE, 'VIOLATION_TYPE', 'NOT_DECIMAL')))
  ) as VIOLATION_DETAILS
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_11.SY01
where asset_id in (${assets}))
select asset_id, line_index::varchar as asset_part, concat_ws('::', RECORD_TYPE, GET_PATH(value, 'FIELD')::varchar, GET_PATH(value, 'VIOLATION_TYPE')::varchar) violation, value as violation_details from v, table(flatten(input => v.VIOLATION_DETAILS));`});


var insertViolations_SY02_01 = snowflake.execute({sqlText: `INSERT INTO VIOLATION (
  ASSET_ID,
  ASSET_PART,
  VIOLATION,
  VIOLATION_DETAIL
) 
WITH
v as (SELECT
  ASSET_ID,
  LINE_INDEX,
  'SY02.01' as RECORD_TYPE,
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('SY02.01'), null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(SUMMARY_RECORD_ID is not null AND ARRAY_SIZE(SUMMARY_RECORD_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUMMARY_RECORD_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', SUMMARY_RECORD_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(SUMMARY_RECORD_ID is null OR ARRAY_SIZE(SUMMARY_RECORD_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUMMARY_RECORD_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', SUMMARY_RECORD_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISTRIBUTION_CHANNEL is null OR ARRAY_SIZE(DISTRIBUTION_CHANNEL) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DISTRIBUTION_CHANNEL', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', DISTRIBUTION_CHANNEL, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISTRIBUTION_CHANNEL_DPID is null OR ARRAY_SIZE(DISTRIBUTION_CHANNEL_DPID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DISTRIBUTION_CHANNEL_DPID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', DISTRIBUTION_CHANNEL_DPID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISTRIBUTION_CHANNEL_DPID[0] is null, null, IFF(DISTRIBUTION_CHANNEL_DPID[0]::string REGEXP 'PADPIDA[0-9A-Za-z]{11}', null, OBJECT_CONSTRUCT('FIELD', 'DISTRIBUTION_CHANNEL_DPID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', DISTRIBUTION_CHANNEL_DPID, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(COMMERCIAL_MODEL is not null AND ARRAY_SIZE(COMMERCIAL_MODEL) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'COMMERCIAL_MODEL', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', COMMERCIAL_MODEL, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(COMMERCIAL_MODEL is null OR ARRAY_SIZE(COMMERCIAL_MODEL) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'COMMERCIAL_MODEL', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', COMMERCIAL_MODEL, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(COMMERCIAL_MODEL[0] is null, null, IFF(is_commercial_model(COMMERCIAL_MODEL[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'COMMERCIAL_MODEL', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', COMMERCIAL_MODEL, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(USE_TYPE is not null AND ARRAY_SIZE(USE_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'USE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', USE_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(USE_TYPE is null OR ARRAY_SIZE(USE_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'USE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', USE_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(USE_TYPE[0] is null, null, IFF(is_use_type(USE_TYPE[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'USE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', USE_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(TERRITORY is not null AND ARRAY_SIZE(TERRITORY) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'TERRITORY', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', TERRITORY, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(TERRITORY is null OR ARRAY_SIZE(TERRITORY) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'TERRITORY', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', TERRITORY, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(TERRITORY[0] is null, null, IFF(is_territory(TERRITORY[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'TERRITORY', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', TERRITORY, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(SERVICE_DESCRIPTION is not null AND ARRAY_SIZE(SERVICE_DESCRIPTION) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'SERVICE_DESCRIPTION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', SERVICE_DESCRIPTION, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(SERVICE_DESCRIPTION is null OR ARRAY_SIZE(SERVICE_DESCRIPTION) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SERVICE_DESCRIPTION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', SERVICE_DESCRIPTION, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(USAGES is not null AND ARRAY_SIZE(USAGES) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'USAGES', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', USAGES, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(USAGES is null OR ARRAY_SIZE(USAGES) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'USAGES', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', USAGES, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(USAGES[0] is null, null, IFF(USAGES[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'USAGES', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', USAGES, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(USERS is null OR ARRAY_SIZE(USERS) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'USERS', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', USERS, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(USERS[0] is null, null, IFF(USERS[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'USERS', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', USERS, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(CURRENCY_OF_REPORTING is not null AND ARRAY_SIZE(CURRENCY_OF_REPORTING) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'CURRENCY_OF_REPORTING', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', CURRENCY_OF_REPORTING, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(CURRENCY_OF_REPORTING is null OR ARRAY_SIZE(CURRENCY_OF_REPORTING) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'CURRENCY_OF_REPORTING', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', CURRENCY_OF_REPORTING, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(CURRENCY_OF_REPORTING[0] is null, null, IFF(is_currency(CURRENCY_OF_REPORTING[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'CURRENCY_OF_REPORTING', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', CURRENCY_OF_REPORTING, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(NET_REVENUE is not null AND ARRAY_SIZE(NET_REVENUE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'NET_REVENUE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', NET_REVENUE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(NET_REVENUE is null OR ARRAY_SIZE(NET_REVENUE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'NET_REVENUE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', NET_REVENUE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(NET_REVENUE[0] is null, null, IFF(NET_REVENUE[0]::string REGEXP '\\\\d+(\\.\\\\d+)?', null, OBJECT_CONSTRUCT('FIELD', 'NET_REVENUE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', NET_REVENUE, 'VIOLATION_TYPE', 'NOT_DECIMAL'))),
    IFF(RIGHTS_CONTROLLER is null OR ARRAY_SIZE(RIGHTS_CONTROLLER) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RIGHTS_CONTROLLER', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', RIGHTS_CONTROLLER, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RIGHTS_CONTROLLER_PARTY_ID is null OR ARRAY_SIZE(RIGHTS_CONTROLLER_PARTY_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RIGHTS_CONTROLLER_PARTY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', RIGHTS_CONTROLLER_PARTY_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RIGHTS_CONTROLLER_PARTY_ID[0] is null, null, IFF(RIGHTS_CONTROLLER_PARTY_ID[0]::string REGEXP 'INSI::\\\\d{16}', null, OBJECT_CONSTRUCT('FIELD', 'RIGHTS_CONTROLLER_PARTY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', RIGHTS_CONTROLLER_PARTY_ID, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(ALLOCATED_NET_REVENUE is null OR ARRAY_SIZE(ALLOCATED_NET_REVENUE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'ALLOCATED_NET_REVENUE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', ALLOCATED_NET_REVENUE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(ALLOCATED_NET_REVENUE[0] is null, null, IFF(ALLOCATED_NET_REVENUE[0]::string REGEXP '\\\\d+(\\.\\\\d+)?', null, OBJECT_CONSTRUCT('FIELD', 'ALLOCATED_NET_REVENUE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', ALLOCATED_NET_REVENUE, 'VIOLATION_TYPE', 'NOT_DECIMAL'))),
    IFF(RIGHTS_TYPE is null OR ARRAY_SIZE(RIGHTS_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RIGHTS_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', RIGHTS_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RIGHTS_TYPE[0] is null, null, IFF(is_right_type(RIGHTS_TYPE[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'RIGHTS_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY02.01', 'FIELD_VALUE', RIGHTS_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE')))
  ) as VIOLATION_DETAILS
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_11.SY02_01
where asset_id in (${assets}))
select asset_id, line_index::varchar as asset_part, concat_ws('::', RECORD_TYPE, GET_PATH(value, 'FIELD')::varchar, GET_PATH(value, 'VIOLATION_TYPE')::varchar) violation, value as violation_details from v, table(flatten(input => v.VIOLATION_DETAILS));`});


var insertViolations_SY04 = snowflake.execute({sqlText: `INSERT INTO VIOLATION (
  ASSET_ID,
  ASSET_PART,
  VIOLATION,
  VIOLATION_DETAIL
) 
WITH
v as (SELECT
  ASSET_ID,
  LINE_INDEX,
  'SY04' as RECORD_TYPE,
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('SY04'), null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(SUMMARY_RECORD_ID is not null AND ARRAY_SIZE(SUMMARY_RECORD_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUMMARY_RECORD_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', SUMMARY_RECORD_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(SUMMARY_RECORD_ID is null OR ARRAY_SIZE(SUMMARY_RECORD_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUMMARY_RECORD_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', SUMMARY_RECORD_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISTRIBUTION_CHANNEL is null OR ARRAY_SIZE(DISTRIBUTION_CHANNEL) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DISTRIBUTION_CHANNEL', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', DISTRIBUTION_CHANNEL, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISTRIBUTION_CHANNEL_DPID is null OR ARRAY_SIZE(DISTRIBUTION_CHANNEL_DPID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DISTRIBUTION_CHANNEL_DPID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', DISTRIBUTION_CHANNEL_DPID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISTRIBUTION_CHANNEL_DPID[0] is null, null, IFF(DISTRIBUTION_CHANNEL_DPID[0]::string REGEXP 'PADPIDA[0-9A-Za-z]{11}', null, OBJECT_CONSTRUCT('FIELD', 'DISTRIBUTION_CHANNEL_DPID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', DISTRIBUTION_CHANNEL_DPID, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(COMMERCIAL_MODEL is not null AND ARRAY_SIZE(COMMERCIAL_MODEL) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'COMMERCIAL_MODEL', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', COMMERCIAL_MODEL, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(COMMERCIAL_MODEL is null OR ARRAY_SIZE(COMMERCIAL_MODEL) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'COMMERCIAL_MODEL', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', COMMERCIAL_MODEL, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(COMMERCIAL_MODEL[0] is null, null, IFF(is_commercial_model(COMMERCIAL_MODEL[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'COMMERCIAL_MODEL', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', COMMERCIAL_MODEL, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(USE_TYPE is not null AND ARRAY_SIZE(USE_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'USE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', USE_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(USE_TYPE is null OR ARRAY_SIZE(USE_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'USE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', USE_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(USE_TYPE[0] is null, null, IFF(is_use_type(USE_TYPE[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'USE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', USE_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(TERRITORY is not null AND ARRAY_SIZE(TERRITORY) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'TERRITORY', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', TERRITORY, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(TERRITORY is null OR ARRAY_SIZE(TERRITORY) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'TERRITORY', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', TERRITORY, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(TERRITORY[0] is null, null, IFF(is_territory(TERRITORY[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'TERRITORY', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', TERRITORY, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(SERVICE_DESCRIPTION is not null AND ARRAY_SIZE(SERVICE_DESCRIPTION) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'SERVICE_DESCRIPTION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', SERVICE_DESCRIPTION, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(SERVICE_DESCRIPTION is null OR ARRAY_SIZE(SERVICE_DESCRIPTION) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SERVICE_DESCRIPTION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', SERVICE_DESCRIPTION, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SUBSCRIBER_TYPE is not null AND ARRAY_SIZE(SUBSCRIBER_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUBSCRIBER_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', SUBSCRIBER_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(SUBSCRIBER_TYPE is null OR ARRAY_SIZE(SUBSCRIBER_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUBSCRIBER_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', SUBSCRIBER_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SUBSCRIBERS is not null AND ARRAY_SIZE(SUBSCRIBERS) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUBSCRIBERS', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', SUBSCRIBERS, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(SUBSCRIBERS is null OR ARRAY_SIZE(SUBSCRIBERS) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUBSCRIBERS', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', SUBSCRIBERS, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SUBSCRIBERS[0] is null, null, IFF(SUBSCRIBERS[0]::string REGEXP '\\\\d+(\\.\\\\d+)?', null, OBJECT_CONSTRUCT('FIELD', 'SUBSCRIBERS', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', SUBSCRIBERS, 'VIOLATION_TYPE', 'NOT_DECIMAL'))),
    IFF(SUB_PERIOD_START_DATE is null OR ARRAY_SIZE(SUB_PERIOD_START_DATE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUB_PERIOD_START_DATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', SUB_PERIOD_START_DATE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SUB_PERIOD_START_DATE[0] is null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_START_DATE[0]::string, 'YYYY-MM-DD') is not null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_START_DATE[0]::string, 'YYYY-MM') is not null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_START_DATE[0]::string, 'YYYY') is not null, null, OBJECT_CONSTRUCT('FIELD', 'SUB_PERIOD_START_DATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', SUB_PERIOD_START_DATE, 'VIOLATION_TYPE', 'NOT_DATE'))))),
    IFF(SUB_PERIOD_END_DATE is null OR ARRAY_SIZE(SUB_PERIOD_END_DATE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUB_PERIOD_END_DATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', SUB_PERIOD_END_DATE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SUB_PERIOD_END_DATE[0] is null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_END_DATE[0]::string, 'YYYY-MM-DD') is not null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_END_DATE[0]::string, 'YYYY-MM') is not null, null, 
      IFF(TRY_TO_DATE(SUB_PERIOD_END_DATE[0]::string, 'YYYY') is not null, null, OBJECT_CONSTRUCT('FIELD', 'SUB_PERIOD_END_DATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', SUB_PERIOD_END_DATE, 'VIOLATION_TYPE', 'NOT_DATE'))))),
    IFF(USAGES_IN_SUB_PERIOD is null OR ARRAY_SIZE(USAGES_IN_SUB_PERIOD) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'USAGES_IN_SUB_PERIOD', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', USAGES_IN_SUB_PERIOD, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(USAGES_IN_SUB_PERIOD[0] is null, null, IFF(USAGES_IN_SUB_PERIOD[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'USAGES_IN_SUB_PERIOD', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', USAGES_IN_SUB_PERIOD, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(USAGES_IN_REPORTING_PERIOD is null OR ARRAY_SIZE(USAGES_IN_REPORTING_PERIOD) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'USAGES_IN_REPORTING_PERIOD', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', USAGES_IN_REPORTING_PERIOD, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(USAGES_IN_REPORTING_PERIOD[0] is null, null, IFF(USAGES_IN_REPORTING_PERIOD[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'USAGES_IN_REPORTING_PERIOD', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', USAGES_IN_REPORTING_PERIOD, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(CURRENCY_OF_REPORTING is not null AND ARRAY_SIZE(CURRENCY_OF_REPORTING) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'CURRENCY_OF_REPORTING', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', CURRENCY_OF_REPORTING, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(CURRENCY_OF_REPORTING is null OR ARRAY_SIZE(CURRENCY_OF_REPORTING) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'CURRENCY_OF_REPORTING', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', CURRENCY_OF_REPORTING, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(CURRENCY_OF_REPORTING[0] is null, null, IFF(is_currency(CURRENCY_OF_REPORTING[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'CURRENCY_OF_REPORTING', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', CURRENCY_OF_REPORTING, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(CURRENCY_OF_TRANSACTION is null OR ARRAY_SIZE(CURRENCY_OF_TRANSACTION) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'CURRENCY_OF_TRANSACTION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', CURRENCY_OF_TRANSACTION, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(CURRENCY_OF_TRANSACTION[0] is null, null, IFF(is_currency(CURRENCY_OF_TRANSACTION[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'CURRENCY_OF_TRANSACTION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', CURRENCY_OF_TRANSACTION, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(EXCHANGE_RATE is null OR ARRAY_SIZE(EXCHANGE_RATE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'EXCHANGE_RATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', EXCHANGE_RATE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(EXCHANGE_RATE[0] is null, null, IFF(EXCHANGE_RATE[0]::string REGEXP '\\\\d+(\\.\\\\d+)?', null, OBJECT_CONSTRUCT('FIELD', 'EXCHANGE_RATE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', EXCHANGE_RATE, 'VIOLATION_TYPE', 'NOT_DECIMAL'))),
    IFF(CONSUMER_PAID_UNIT_PRICE is not null AND ARRAY_SIZE(CONSUMER_PAID_UNIT_PRICE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'CONSUMER_PAID_UNIT_PRICE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', CONSUMER_PAID_UNIT_PRICE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(CONSUMER_PAID_UNIT_PRICE is null OR ARRAY_SIZE(CONSUMER_PAID_UNIT_PRICE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'CONSUMER_PAID_UNIT_PRICE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', CONSUMER_PAID_UNIT_PRICE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(CONSUMER_PAID_UNIT_PRICE[0] is null, null, IFF(CONSUMER_PAID_UNIT_PRICE[0]::string REGEXP '\\\\d+(\\.\\\\d+)?', null, OBJECT_CONSTRUCT('FIELD', 'CONSUMER_PAID_UNIT_PRICE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', CONSUMER_PAID_UNIT_PRICE, 'VIOLATION_TYPE', 'NOT_DECIMAL'))),
    IFF(NET_REVENUE is not null AND ARRAY_SIZE(NET_REVENUE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'NET_REVENUE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', NET_REVENUE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(NET_REVENUE is null OR ARRAY_SIZE(NET_REVENUE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'NET_REVENUE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', NET_REVENUE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(NET_REVENUE[0] is null, null, IFF(NET_REVENUE[0]::string REGEXP '\\\\d+(\\.\\\\d+)?', null, OBJECT_CONSTRUCT('FIELD', 'NET_REVENUE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY04', 'FIELD_VALUE', NET_REVENUE, 'VIOLATION_TYPE', 'NOT_DECIMAL')))
  ) as VIOLATION_DETAILS
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_11.SY04
where asset_id in (${assets}))
select asset_id, line_index::varchar as asset_part, concat_ws('::', RECORD_TYPE, GET_PATH(value, 'FIELD')::varchar, GET_PATH(value, 'VIOLATION_TYPE')::varchar) violation, value as violation_details from v, table(flatten(input => v.VIOLATION_DETAILS));`});


var insertViolations_SY05 = snowflake.execute({sqlText: `INSERT INTO VIOLATION (
  ASSET_ID,
  ASSET_PART,
  VIOLATION,
  VIOLATION_DETAIL
) 
WITH
v as (SELECT
  ASSET_ID,
  LINE_INDEX,
  'SY05' as RECORD_TYPE,
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('SY05'), null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(SUMMARY_RECORD_ID is not null AND ARRAY_SIZE(SUMMARY_RECORD_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUMMARY_RECORD_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', SUMMARY_RECORD_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(SUMMARY_RECORD_ID is null OR ARRAY_SIZE(SUMMARY_RECORD_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUMMARY_RECORD_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', SUMMARY_RECORD_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISTRIBUTION_CHANNEL is null OR ARRAY_SIZE(DISTRIBUTION_CHANNEL) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DISTRIBUTION_CHANNEL', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', DISTRIBUTION_CHANNEL, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISTRIBUTION_CHANNEL_DPID is null OR ARRAY_SIZE(DISTRIBUTION_CHANNEL_DPID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DISTRIBUTION_CHANNEL_DPID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', DISTRIBUTION_CHANNEL_DPID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISTRIBUTION_CHANNEL_DPID[0] is null, null, IFF(DISTRIBUTION_CHANNEL_DPID[0]::string REGEXP 'PADPIDA[0-9A-Za-z]{11}', null, OBJECT_CONSTRUCT('FIELD', 'DISTRIBUTION_CHANNEL_DPID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', DISTRIBUTION_CHANNEL_DPID, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(COMMERCIAL_MODEL is not null AND ARRAY_SIZE(COMMERCIAL_MODEL) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'COMMERCIAL_MODEL', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', COMMERCIAL_MODEL, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(COMMERCIAL_MODEL is null OR ARRAY_SIZE(COMMERCIAL_MODEL) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'COMMERCIAL_MODEL', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', COMMERCIAL_MODEL, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(COMMERCIAL_MODEL[0] is null, null, IFF(is_commercial_model(COMMERCIAL_MODEL[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'COMMERCIAL_MODEL', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', COMMERCIAL_MODEL, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(USE_TYPE is not null AND ARRAY_SIZE(USE_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'USE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', USE_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(USE_TYPE is null OR ARRAY_SIZE(USE_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'USE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', USE_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(USE_TYPE[0] is null, null, IFF(is_use_type(USE_TYPE[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'USE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', USE_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(TERRITORY is not null AND ARRAY_SIZE(TERRITORY) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'TERRITORY', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', TERRITORY, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(TERRITORY is null OR ARRAY_SIZE(TERRITORY) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'TERRITORY', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', TERRITORY, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(TERRITORY[0] is null, null, IFF(is_territory(TERRITORY[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'TERRITORY', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', TERRITORY, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(SERVICE_DESCRIPTION is null OR ARRAY_SIZE(SERVICE_DESCRIPTION) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SERVICE_DESCRIPTION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', SERVICE_DESCRIPTION, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RIGHTS_CONTROLLER is null OR ARRAY_SIZE(RIGHTS_CONTROLLER) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RIGHTS_CONTROLLER', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', RIGHTS_CONTROLLER, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RIGHTS_CONTROLLER_PARTY_ID is null OR ARRAY_SIZE(RIGHTS_CONTROLLER_PARTY_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RIGHTS_CONTROLLER_PARTY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', RIGHTS_CONTROLLER_PARTY_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RIGHTS_CONTROLLER_PARTY_ID[0] is null, null, IFF(RIGHTS_CONTROLLER_PARTY_ID[0]::string REGEXP 'INSI::\\\\d{16}', null, OBJECT_CONSTRUCT('FIELD', 'RIGHTS_CONTROLLER_PARTY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', RIGHTS_CONTROLLER_PARTY_ID, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(RIGHTS_TYPE is not null AND ARRAY_SIZE(RIGHTS_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RIGHTS_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', RIGHTS_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RIGHTS_TYPE is null OR ARRAY_SIZE(RIGHTS_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RIGHTS_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', RIGHTS_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RIGHTS_TYPE[0] is null, null, IFF(is_right_type(RIGHTS_TYPE[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'RIGHTS_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', RIGHTS_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(TOTAL_USAGES is null OR ARRAY_SIZE(TOTAL_USAGES) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'TOTAL_USAGES', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', TOTAL_USAGES, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(TOTAL_USAGES[0] is null, null, IFF(TOTAL_USAGES[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'TOTAL_USAGES', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', TOTAL_USAGES, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(MUSIC_USAGE_RATIO is null OR ARRAY_SIZE(MUSIC_USAGE_RATIO) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'MUSIC_USAGE_RATIO', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', MUSIC_USAGE_RATIO, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(MUSIC_USAGE_RATIO[0] is null, null, IFF(MUSIC_USAGE_RATIO[0]::string REGEXP '\\\\d+(\\.\\\\d+)?', null, OBJECT_CONSTRUCT('FIELD', 'MUSIC_USAGE_RATIO', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', MUSIC_USAGE_RATIO, 'VIOLATION_TYPE', 'NOT_DECIMAL'))),
    IFF(ALLOCATED_REVENUE is null OR ARRAY_SIZE(ALLOCATED_REVENUE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'ALLOCATED_REVENUE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', ALLOCATED_REVENUE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(ALLOCATED_REVENUE[0] is null, null, IFF(ALLOCATED_REVENUE[0]::string REGEXP '\\\\d+(\\.\\\\d+)?', null, OBJECT_CONSTRUCT('FIELD', 'ALLOCATED_REVENUE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', ALLOCATED_REVENUE, 'VIOLATION_TYPE', 'NOT_DECIMAL'))),
    IFF(RIGHTS_CONTROLLER_MARKET_SHARE is null OR ARRAY_SIZE(RIGHTS_CONTROLLER_MARKET_SHARE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RIGHTS_CONTROLLER_MARKET_SHARE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', RIGHTS_CONTROLLER_MARKET_SHARE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RIGHTS_CONTROLLER_MARKET_SHARE[0] is null, null, IFF(RIGHTS_CONTROLLER_MARKET_SHARE[0]::string REGEXP '\\\\d+(\\.\\\\d+)?', null, OBJECT_CONSTRUCT('FIELD', 'RIGHTS_CONTROLLER_MARKET_SHARE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SY05', 'FIELD_VALUE', RIGHTS_CONTROLLER_MARKET_SHARE, 'VIOLATION_TYPE', 'NOT_DECIMAL')))
  ) as VIOLATION_DETAILS
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_11.SY05
where asset_id in (${assets}))
select asset_id, line_index::varchar as asset_part, concat_ws('::', RECORD_TYPE, GET_PATH(value, 'FIELD')::varchar, GET_PATH(value, 'VIOLATION_TYPE')::varchar) violation, value as violation_details from v, table(flatten(input => v.VIOLATION_DETAILS));`});


var insertViolations_RE01 = snowflake.execute({sqlText: `INSERT INTO VIOLATION (
  ASSET_ID,
  ASSET_PART,
  VIOLATION,
  VIOLATION_DETAIL
) 
WITH
v as (SELECT
  ASSET_ID,
  LINE_INDEX,
  'RE01' as RECORD_TYPE,
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('RE01'), null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(BLOCK_ID is not null AND ARRAY_SIZE(BLOCK_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'BLOCK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', BLOCK_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(BLOCK_ID is null OR ARRAY_SIZE(BLOCK_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'BLOCK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', BLOCK_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RELEASE_REFERENCE is not null AND ARRAY_SIZE(RELEASE_REFERENCE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RELEASE_REFERENCE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', RELEASE_REFERENCE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RELEASE_REFERENCE is null OR ARRAY_SIZE(RELEASE_REFERENCE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RELEASE_REFERENCE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', RELEASE_REFERENCE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DSP_RELEASE_ID is not null AND ARRAY_SIZE(DSP_RELEASE_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'DSP_RELEASE_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', DSP_RELEASE_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(DSP_RELEASE_ID is null OR ARRAY_SIZE(DSP_RELEASE_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DSP_RELEASE_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', DSP_RELEASE_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(CATALOG_NUMBER is null OR ARRAY_SIZE(CATALOG_NUMBER) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'CATALOG_NUMBER', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', CATALOG_NUMBER, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(ICPN is null OR ARRAY_SIZE(ICPN) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'ICPN', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', ICPN, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(ICPN[0] is null, null, IFF(ICPN[0]::string REGEXP '\\\\d{12,14}', null, OBJECT_CONSTRUCT('FIELD', 'ICPN', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', ICPN, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(DISPLAY_ARTIST_NAME is not null AND ARRAY_SIZE(DISPLAY_ARTIST_NAME) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'DISPLAY_ARTIST_NAME', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', DISPLAY_ARTIST_NAME, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(DISPLAY_ARTIST_NAME is null OR ARRAY_SIZE(DISPLAY_ARTIST_NAME) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DISPLAY_ARTIST_NAME', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', DISPLAY_ARTIST_NAME, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISPLAY_ARTIST_PARTY_ID is null OR ARRAY_SIZE(DISPLAY_ARTIST_PARTY_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DISPLAY_ARTIST_PARTY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', DISPLAY_ARTIST_PARTY_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISPLAY_ARTIST_PARTY_ID[0] is null, null, IFF(DISPLAY_ARTIST_PARTY_ID[0]::string REGEXP 'INSI::\\\\d{16}', null, OBJECT_CONSTRUCT('FIELD', 'DISPLAY_ARTIST_PARTY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', DISPLAY_ARTIST_PARTY_ID, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(TITLE is not null AND ARRAY_SIZE(TITLE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'TITLE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', TITLE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(TITLE is null OR ARRAY_SIZE(TITLE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'TITLE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', TITLE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SUB_TITLE is null OR ARRAY_SIZE(SUB_TITLE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUB_TITLE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', SUB_TITLE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RELEASE_TYPE is null OR ARRAY_SIZE(RELEASE_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RELEASE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', RELEASE_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RELEASE_TYPE[0] is null, null, IFF(is_release_type(RELEASE_TYPE[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'RELEASE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', RELEASE_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(LABEL is null OR ARRAY_SIZE(LABEL) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'LABEL', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', LABEL, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(P_LINE is null OR ARRAY_SIZE(P_LINE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'P_LINE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', P_LINE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DATA_PROVIDER is null OR ARRAY_SIZE(DATA_PROVIDER) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DATA_PROVIDER', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE01', 'FIELD_VALUE', DATA_PROVIDER, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS'))
  ) as VIOLATION_DETAILS
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_11.RE01
where asset_id in (${assets}))
select asset_id, line_index::varchar as asset_part, concat_ws('::', RECORD_TYPE, GET_PATH(value, 'FIELD')::varchar, GET_PATH(value, 'VIOLATION_TYPE')::varchar) violation, value as violation_details from v, table(flatten(input => v.VIOLATION_DETAILS));`});


var insertViolations_RE02 = snowflake.execute({sqlText: `INSERT INTO VIOLATION (
  ASSET_ID,
  ASSET_PART,
  VIOLATION,
  VIOLATION_DETAIL
) 
WITH
v as (SELECT
  ASSET_ID,
  LINE_INDEX,
  'RE02' as RECORD_TYPE,
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE02', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE02', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('RE02'), null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE02', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(BLOCK_ID is not null AND ARRAY_SIZE(BLOCK_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'BLOCK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE02', 'FIELD_VALUE', BLOCK_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(BLOCK_ID is null OR ARRAY_SIZE(BLOCK_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'BLOCK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE02', 'FIELD_VALUE', BLOCK_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RELEASE_REFERENCE is not null AND ARRAY_SIZE(RELEASE_REFERENCE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RELEASE_REFERENCE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE02', 'FIELD_VALUE', RELEASE_REFERENCE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RELEASE_REFERENCE is null OR ARRAY_SIZE(RELEASE_REFERENCE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RELEASE_REFERENCE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE02', 'FIELD_VALUE', RELEASE_REFERENCE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DSP_SUB_RELEASE_ID is not null AND ARRAY_SIZE(DSP_SUB_RELEASE_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'DSP_SUB_RELEASE_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE02', 'FIELD_VALUE', DSP_SUB_RELEASE_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(DSP_SUB_RELEASE_ID is null OR ARRAY_SIZE(DSP_SUB_RELEASE_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DSP_SUB_RELEASE_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE02', 'FIELD_VALUE', DSP_SUB_RELEASE_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(USED_RESOURCES is not null AND ARRAY_SIZE(USED_RESOURCES) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'USED_RESOURCES', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'RE02', 'FIELD_VALUE', USED_RESOURCES, 'VIOLATION_TYPE', 'REQUIRED'))
  ) as VIOLATION_DETAILS
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_11.RE02
where asset_id in (${assets}))
select asset_id, line_index::varchar as asset_part, concat_ws('::', RECORD_TYPE, GET_PATH(value, 'FIELD')::varchar, GET_PATH(value, 'VIOLATION_TYPE')::varchar) violation, value as violation_details from v, table(flatten(input => v.VIOLATION_DETAILS));`});


var insertViolations_AS01 = snowflake.execute({sqlText: `INSERT INTO VIOLATION (
  ASSET_ID,
  ASSET_PART,
  VIOLATION,
  VIOLATION_DETAIL
) 
WITH
v as (SELECT
  ASSET_ID,
  LINE_INDEX,
  'AS01' as RECORD_TYPE,
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('AS01'), null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(BLOCK_ID is not null AND ARRAY_SIZE(BLOCK_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'BLOCK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS01', 'FIELD_VALUE', BLOCK_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(BLOCK_ID is null OR ARRAY_SIZE(BLOCK_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'BLOCK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS01', 'FIELD_VALUE', BLOCK_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RESOURCE_REFERENCE is not null AND ARRAY_SIZE(RESOURCE_REFERENCE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RESOURCE_REFERENCE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS01', 'FIELD_VALUE', RESOURCE_REFERENCE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RESOURCE_REFERENCE is null OR ARRAY_SIZE(RESOURCE_REFERENCE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RESOURCE_REFERENCE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS01', 'FIELD_VALUE', RESOURCE_REFERENCE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DSP_RESOURCE_ID is not null AND ARRAY_SIZE(DSP_RESOURCE_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'DSP_RESOURCE_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS01', 'FIELD_VALUE', DSP_RESOURCE_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(DSP_RESOURCE_ID is null OR ARRAY_SIZE(DSP_RESOURCE_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DSP_RESOURCE_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS01', 'FIELD_VALUE', DSP_RESOURCE_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(ISRC is null OR ARRAY_SIZE(ISRC) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'ISRC', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS01', 'FIELD_VALUE', ISRC, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(ISRC[0] is null, null, IFF(ISRC[0]::string REGEXP '[A-Za-z]{2}-?[0-9A-Za-z]{3}-?\\\\d{2}-?\\\\d{5}', null, OBJECT_CONSTRUCT('FIELD', 'ISRC', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS01', 'FIELD_VALUE', ISRC, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(TITLE is not null AND ARRAY_SIZE(TITLE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'TITLE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS01', 'FIELD_VALUE', TITLE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(TITLE is null OR ARRAY_SIZE(TITLE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'TITLE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS01', 'FIELD_VALUE', TITLE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SUB_TITLE is null OR ARRAY_SIZE(SUB_TITLE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUB_TITLE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS01', 'FIELD_VALUE', SUB_TITLE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISPLAY_ARTIST_NAME is null OR ARRAY_SIZE(DISPLAY_ARTIST_NAME) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DISPLAY_ARTIST_NAME', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS01', 'FIELD_VALUE', DISPLAY_ARTIST_NAME, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISPLAY_ARTIST_PARTY_ID is null OR ARRAY_SIZE(DISPLAY_ARTIST_PARTY_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DISPLAY_ARTIST_PARTY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS01', 'FIELD_VALUE', DISPLAY_ARTIST_PARTY_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISPLAY_ARTIST_PARTY_ID[0] is null, null, IFF(DISPLAY_ARTIST_PARTY_ID[0]::string REGEXP 'INSI::\\\\d{16}', null, OBJECT_CONSTRUCT('FIELD', 'DISPLAY_ARTIST_PARTY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS01', 'FIELD_VALUE', DISPLAY_ARTIST_PARTY_ID, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(DURATION is null OR ARRAY_SIZE(DURATION) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DURATION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS01', 'FIELD_VALUE', DURATION, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DURATION[0] is null, null, IFF(DURATION[0]::string REGEXP 'PT((\\\\d+H)?\\\\d+M)?\\\\d+(\\.\\\\d+)?S', null, OBJECT_CONSTRUCT('FIELD', 'DURATION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS01', 'FIELD_VALUE', DURATION, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(RESOURCE_TYPE is not null AND ARRAY_SIZE(RESOURCE_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RESOURCE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS01', 'FIELD_VALUE', RESOURCE_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RESOURCE_TYPE is null OR ARRAY_SIZE(RESOURCE_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RESOURCE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS01', 'FIELD_VALUE', RESOURCE_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RESOURCE_TYPE[0] is null, null, IFF(is_resource_type(RESOURCE_TYPE[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'RESOURCE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS01', 'FIELD_VALUE', RESOURCE_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE')))
  ) as VIOLATION_DETAILS
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_11.AS01
where asset_id in (${assets}))
select asset_id, line_index::varchar as asset_part, concat_ws('::', RECORD_TYPE, GET_PATH(value, 'FIELD')::varchar, GET_PATH(value, 'VIOLATION_TYPE')::varchar) violation, value as violation_details from v, table(flatten(input => v.VIOLATION_DETAILS));`});


var insertViolations_AS02_01 = snowflake.execute({sqlText: `INSERT INTO VIOLATION (
  ASSET_ID,
  ASSET_PART,
  VIOLATION,
  VIOLATION_DETAIL
) 
WITH
v as (SELECT
  ASSET_ID,
  LINE_INDEX,
  'AS02.01' as RECORD_TYPE,
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('AS02.01'), null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(BLOCK_ID is not null AND ARRAY_SIZE(BLOCK_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'BLOCK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', BLOCK_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(BLOCK_ID is null OR ARRAY_SIZE(BLOCK_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'BLOCK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', BLOCK_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RESOURCE_REFERENCE is not null AND ARRAY_SIZE(RESOURCE_REFERENCE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RESOURCE_REFERENCE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', RESOURCE_REFERENCE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RESOURCE_REFERENCE is null OR ARRAY_SIZE(RESOURCE_REFERENCE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RESOURCE_REFERENCE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', RESOURCE_REFERENCE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DSP_RESOURCE_ID is not null AND ARRAY_SIZE(DSP_RESOURCE_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'DSP_RESOURCE_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', DSP_RESOURCE_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(DSP_RESOURCE_ID is null OR ARRAY_SIZE(DSP_RESOURCE_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DSP_RESOURCE_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', DSP_RESOURCE_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(ISRC is null OR ARRAY_SIZE(ISRC) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'ISRC', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', ISRC, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(ISRC[0] is null, null, IFF(ISRC[0]::string REGEXP '[A-Za-z]{2}-?[0-9A-Za-z]{3}-?\\\\d{2}-?\\\\d{5}', null, OBJECT_CONSTRUCT('FIELD', 'ISRC', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', ISRC, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(TITLE is not null AND ARRAY_SIZE(TITLE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'TITLE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', TITLE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(TITLE is null OR ARRAY_SIZE(TITLE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'TITLE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', TITLE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SUB_TITLE is null OR ARRAY_SIZE(SUB_TITLE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUB_TITLE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', SUB_TITLE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISPLAY_ARTIST_NAME is null OR ARRAY_SIZE(DISPLAY_ARTIST_NAME) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DISPLAY_ARTIST_NAME', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', DISPLAY_ARTIST_NAME, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISPLAY_ARTIST_PARTY_ID is null OR ARRAY_SIZE(DISPLAY_ARTIST_PARTY_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DISPLAY_ARTIST_PARTY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', DISPLAY_ARTIST_PARTY_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DISPLAY_ARTIST_PARTY_ID[0] is null, null, IFF(DISPLAY_ARTIST_PARTY_ID[0]::string REGEXP 'INSI::\\\\d{16}', null, OBJECT_CONSTRUCT('FIELD', 'DISPLAY_ARTIST_PARTY_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', DISPLAY_ARTIST_PARTY_ID, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(DURATION is null OR ARRAY_SIZE(DURATION) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DURATION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', DURATION, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DURATION[0] is null, null, IFF(DURATION[0]::string REGEXP 'PT((\\\\d+H)?\\\\d+M)?\\\\d+(\\.\\\\d+)?S', null, OBJECT_CONSTRUCT('FIELD', 'DURATION', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', DURATION, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(RESOURCE_TYPE is not null AND ARRAY_SIZE(RESOURCE_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RESOURCE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', RESOURCE_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RESOURCE_TYPE is null OR ARRAY_SIZE(RESOURCE_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RESOURCE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', RESOURCE_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RESOURCE_TYPE[0] is null, null, IFF(is_resource_type(RESOURCE_TYPE[0]::string), null, OBJECT_CONSTRUCT('FIELD', 'RESOURCE_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', RESOURCE_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(ISWC is null OR ARRAY_SIZE(ISWC) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'ISWC', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', ISWC, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(ISWC[0] is null, null, IFF(ISWC[0]::string REGEXP 'T\\\\d{10}', null, OBJECT_CONSTRUCT('FIELD', 'ISWC', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', ISWC, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(PROPRIETARY_WORK_ID is null OR ARRAY_SIZE(PROPRIETARY_WORK_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'PROPRIETARY_WORK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', PROPRIETARY_WORK_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(PROPRIETARY_WORK_ID[0] is null, null, IFF(PROPRIETARY_WORK_ID[0]::string REGEXP '\\.+::\\.+', null, OBJECT_CONSTRUCT('FIELD', 'PROPRIETARY_WORK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'AS02.01', 'FIELD_VALUE', PROPRIETARY_WORK_ID, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN')))
  ) as VIOLATION_DETAILS
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_11.AS02_01
where asset_id in (${assets}))
select asset_id, line_index::varchar as asset_part, concat_ws('::', RECORD_TYPE, GET_PATH(value, 'FIELD')::varchar, GET_PATH(value, 'VIOLATION_TYPE')::varchar) violation, value as violation_details from v, table(flatten(input => v.VIOLATION_DETAILS));`});


var insertViolations_MW01_01 = snowflake.execute({sqlText: `INSERT INTO VIOLATION (
  ASSET_ID,
  ASSET_PART,
  VIOLATION,
  VIOLATION_DETAIL
) 
WITH
v as (SELECT
  ASSET_ID,
  LINE_INDEX,
  'MW01.01' as RECORD_TYPE,
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'MW01.01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'MW01.01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('MW01.01'), null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'MW01.01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(BLOCK_ID is not null AND ARRAY_SIZE(BLOCK_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'BLOCK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'MW01.01', 'FIELD_VALUE', BLOCK_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(BLOCK_ID is null OR ARRAY_SIZE(BLOCK_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'BLOCK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'MW01.01', 'FIELD_VALUE', BLOCK_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DSP_WORK_ID is not null AND ARRAY_SIZE(DSP_WORK_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'DSP_WORK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'MW01.01', 'FIELD_VALUE', DSP_WORK_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(DSP_WORK_ID is null OR ARRAY_SIZE(DSP_WORK_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DSP_WORK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'MW01.01', 'FIELD_VALUE', DSP_WORK_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(ISWC is null OR ARRAY_SIZE(ISWC) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'ISWC', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'MW01.01', 'FIELD_VALUE', ISWC, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(ISWC[0] is null, null, IFF(ISWC[0]::string REGEXP '[A-Za-z]{2}[0-9A-Za-z]{3}\\\\d{7}', null, OBJECT_CONSTRUCT('FIELD', 'ISWC', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'MW01.01', 'FIELD_VALUE', ISWC, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN'))),
    IFF(TITLE is not null AND ARRAY_SIZE(TITLE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'TITLE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'MW01.01', 'FIELD_VALUE', TITLE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(TITLE is null OR ARRAY_SIZE(TITLE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'TITLE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'MW01.01', 'FIELD_VALUE', TITLE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SUB_TITLE is null OR ARRAY_SIZE(SUB_TITLE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUB_TITLE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'MW01.01', 'FIELD_VALUE', SUB_TITLE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(DATA_PROVIDER is null OR ARRAY_SIZE(DATA_PROVIDER) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'DATA_PROVIDER', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'MW01.01', 'FIELD_VALUE', DATA_PROVIDER, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(PROPRIETARY_WORK_ID is null OR ARRAY_SIZE(PROPRIETARY_WORK_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'PROPRIETARY_WORK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'MW01.01', 'FIELD_VALUE', PROPRIETARY_WORK_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(PROPRIETARY_WORK_ID[0] is null, null, IFF(PROPRIETARY_WORK_ID[0]::string REGEXP '\\.+::\\.+', null, OBJECT_CONSTRUCT('FIELD', 'PROPRIETARY_WORK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'MW01.01', 'FIELD_VALUE', PROPRIETARY_WORK_ID, 'VIOLATION_TYPE', 'NOT_ALLOWED_PATTERN')))
  ) as VIOLATION_DETAILS
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_11.MW01_01
where asset_id in (${assets}))
select asset_id, line_index::varchar as asset_part, concat_ws('::', RECORD_TYPE, GET_PATH(value, 'FIELD')::varchar, GET_PATH(value, 'VIOLATION_TYPE')::varchar) violation, value as violation_details from v, table(flatten(input => v.VIOLATION_DETAILS));`});


var insertViolations_SU01 = snowflake.execute({sqlText: `INSERT INTO VIOLATION (
  ASSET_ID,
  ASSET_PART,
  VIOLATION,
  VIOLATION_DETAIL
) 
WITH
v as (SELECT
  ASSET_ID,
  LINE_INDEX,
  'SU01' as RECORD_TYPE,
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('SU01'), null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(BLOCK_ID is not null AND ARRAY_SIZE(BLOCK_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'BLOCK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', BLOCK_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(BLOCK_ID is null OR ARRAY_SIZE(BLOCK_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'BLOCK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', BLOCK_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SUMMARY_RECORD_ID is not null AND ARRAY_SIZE(SUMMARY_RECORD_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUMMARY_RECORD_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', SUMMARY_RECORD_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(SUMMARY_RECORD_ID is null OR ARRAY_SIZE(SUMMARY_RECORD_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUMMARY_RECORD_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', SUMMARY_RECORD_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SALES_TRANSACTION_ID is not null AND ARRAY_SIZE(SALES_TRANSACTION_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'SALES_TRANSACTION_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', SALES_TRANSACTION_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(SALES_TRANSACTION_ID is null OR ARRAY_SIZE(SALES_TRANSACTION_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SALES_TRANSACTION_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', SALES_TRANSACTION_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(TRANSACTED_RELEASE is null OR ARRAY_SIZE(TRANSACTED_RELEASE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'TRANSACTED_RELEASE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', TRANSACTED_RELEASE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(TRANSACTED_RESOURCE is null OR ARRAY_SIZE(TRANSACTED_RESOURCE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'TRANSACTED_RESOURCE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', TRANSACTED_RESOURCE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(IS_ROYALTY_BEARING is not null AND ARRAY_SIZE(IS_ROYALTY_BEARING) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'IS_ROYALTY_BEARING', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', IS_ROYALTY_BEARING, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(IS_ROYALTY_BEARING is null OR ARRAY_SIZE(IS_ROYALTY_BEARING) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'IS_ROYALTY_BEARING', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', IS_ROYALTY_BEARING, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(IS_ROYALTY_BEARING[0] is null, null, IFF(RLIKE(IS_ROYALTY_BEARING[0]::string, '(true|false|yes|no|y|n|0|1)', 'i'), null, OBJECT_CONSTRUCT('FIELD', 'IS_ROYALTY_BEARING', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', IS_ROYALTY_BEARING, 'VIOLATION_TYPE', 'NOT_BOOLEAN'))),
    IFF(SALES_UPGRADE is not null AND ARRAY_SIZE(SALES_UPGRADE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'SALES_UPGRADE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', SALES_UPGRADE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(SALES_UPGRADE is null OR ARRAY_SIZE(SALES_UPGRADE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SALES_UPGRADE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', SALES_UPGRADE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SALES_UPGRADE[0] is null, null, IFF(RLIKE(SALES_UPGRADE[0]::string, '(true|false|yes|no|y|n|0|1)', 'i'), null, OBJECT_CONSTRUCT('FIELD', 'SALES_UPGRADE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', SALES_UPGRADE, 'VIOLATION_TYPE', 'NOT_BOOLEAN'))),
    IFF(USAGES is not null AND ARRAY_SIZE(USAGES) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'USAGES', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', USAGES, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(USAGES is null OR ARRAY_SIZE(USAGES) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'USAGES', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', USAGES, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(USAGES[0] is null, null, IFF(USAGES[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'USAGES', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', USAGES, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(RETURNS is not null AND ARRAY_SIZE(RETURNS) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RETURNS', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', RETURNS, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RETURNS is null OR ARRAY_SIZE(RETURNS) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RETURNS', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', RETURNS, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RETURNS[0] is null, null, IFF(RETURNS[0]::string REGEXP '\\\\d+', null, OBJECT_CONSTRUCT('FIELD', 'RETURNS', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', RETURNS, 'VIOLATION_TYPE', 'NOT_INTEGER'))),
    IFF(PRICE_CONSUMER_PAID_EXC_SALES_TAX is null OR ARRAY_SIZE(PRICE_CONSUMER_PAID_EXC_SALES_TAX) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'PRICE_CONSUMER_PAID_EXC_SALES_TAX', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', PRICE_CONSUMER_PAID_EXC_SALES_TAX, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(PRICE_CONSUMER_PAID_EXC_SALES_TAX[0] is null, null, IFF(PRICE_CONSUMER_PAID_EXC_SALES_TAX[0]::string REGEXP '\\\\d+(\\.\\\\d+)?', null, OBJECT_CONSTRUCT('FIELD', 'PRICE_CONSUMER_PAID_EXC_SALES_TAX', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', PRICE_CONSUMER_PAID_EXC_SALES_TAX, 'VIOLATION_TYPE', 'NOT_DECIMAL'))),
    IFF(PROMOTIONAL_ACTIVITY is null OR ARRAY_SIZE(PROMOTIONAL_ACTIVITY) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'PROMOTIONAL_ACTIVITY', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU01', 'FIELD_VALUE', PROMOTIONAL_ACTIVITY, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS'))
  ) as VIOLATION_DETAILS
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_11.SU01
where asset_id in (${assets}))
select asset_id, line_index::varchar as asset_part, concat_ws('::', RECORD_TYPE, GET_PATH(value, 'FIELD')::varchar, GET_PATH(value, 'VIOLATION_TYPE')::varchar) violation, value as violation_details from v, table(flatten(input => v.VIOLATION_DETAILS));`});


var insertViolations_SU02 = snowflake.execute({sqlText: `INSERT INTO VIOLATION (
  ASSET_ID,
  ASSET_PART,
  VIOLATION,
  VIOLATION_DETAIL
) 
WITH
v as (SELECT
  ASSET_ID,
  LINE_INDEX,
  'SU02' as RECORD_TYPE,
  ARRAY_CONSTRUCT_COMPACT(
    IFF(RECORD_TYPE is not null AND ARRAY_SIZE(RECORD_TYPE) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU02', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(RECORD_TYPE is null OR ARRAY_SIZE(RECORD_TYPE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU02', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(RECORD_TYPE[0] is null, null, IFF(RECORD_TYPE[0]::string IN ('SU02'), null, OBJECT_CONSTRUCT('FIELD', 'RECORD_TYPE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU02', 'FIELD_VALUE', RECORD_TYPE, 'VIOLATION_TYPE', 'NOT_ALLOWED_VALUE'))),
    IFF(BLOCK_ID is not null AND ARRAY_SIZE(BLOCK_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'BLOCK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU02', 'FIELD_VALUE', BLOCK_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(BLOCK_ID is null OR ARRAY_SIZE(BLOCK_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'BLOCK_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU02', 'FIELD_VALUE', BLOCK_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SUMMARY_RECORD_ID is not null AND ARRAY_SIZE(SUMMARY_RECORD_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUMMARY_RECORD_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU02', 'FIELD_VALUE', SUMMARY_RECORD_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(SUMMARY_RECORD_ID is null OR ARRAY_SIZE(SUMMARY_RECORD_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SUMMARY_RECORD_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU02', 'FIELD_VALUE', SUMMARY_RECORD_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(SALES_TRANSACTION_ID is not null AND ARRAY_SIZE(SALES_TRANSACTION_ID) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'SALES_TRANSACTION_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU02', 'FIELD_VALUE', SALES_TRANSACTION_ID, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(SALES_TRANSACTION_ID is null OR ARRAY_SIZE(SALES_TRANSACTION_ID) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'SALES_TRANSACTION_ID', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU02', 'FIELD_VALUE', SALES_TRANSACTION_ID, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(TRANSACTED_RELEASE is null OR ARRAY_SIZE(TRANSACTED_RELEASE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'TRANSACTED_RELEASE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU02', 'FIELD_VALUE', TRANSACTED_RELEASE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(TRANSACTED_RESOURCE is null OR ARRAY_SIZE(TRANSACTED_RESOURCE) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'TRANSACTED_RESOURCE', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU02', 'FIELD_VALUE', TRANSACTED_RESOURCE, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(IS_ROYALTY_BEARING is null OR ARRAY_SIZE(IS_ROYALTY_BEARING) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'IS_ROYALTY_BEARING', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU02', 'FIELD_VALUE', IS_ROYALTY_BEARING, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(IS_ROYALTY_BEARING[0] is null, null, IFF(RLIKE(IS_ROYALTY_BEARING[0]::string, '(true|false|yes|no|y|n|0|1)', 'i'), null, OBJECT_CONSTRUCT('FIELD', 'IS_ROYALTY_BEARING', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU02', 'FIELD_VALUE', IS_ROYALTY_BEARING, 'VIOLATION_TYPE', 'NOT_BOOLEAN'))),
    IFF(NUMBER_OF_STREAMS is not null AND ARRAY_SIZE(NUMBER_OF_STREAMS) >= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_STREAMS', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU02', 'FIELD_VALUE', NUMBER_OF_STREAMS, 'VIOLATION_TYPE', 'REQUIRED')),
    IFF(NUMBER_OF_STREAMS is null OR ARRAY_SIZE(NUMBER_OF_STREAMS) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_STREAMS', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU02', 'FIELD_VALUE', NUMBER_OF_STREAMS, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(NUMBER_OF_STREAMS[0] is null, null, IFF(NUMBER_OF_STREAMS[0]::string REGEXP '\\\\d+(\\.\\\\d+)?', null, OBJECT_CONSTRUCT('FIELD', 'NUMBER_OF_STREAMS', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU02', 'FIELD_VALUE', NUMBER_OF_STREAMS, 'VIOLATION_TYPE', 'NOT_DECIMAL'))),
    IFF(PRICE_CONSUMER_PAID_EXC_SALES_TAX is null OR ARRAY_SIZE(PRICE_CONSUMER_PAID_EXC_SALES_TAX) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'PRICE_CONSUMER_PAID_EXC_SALES_TAX', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU02', 'FIELD_VALUE', PRICE_CONSUMER_PAID_EXC_SALES_TAX, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS')),
    IFF(PRICE_CONSUMER_PAID_EXC_SALES_TAX[0] is null, null, IFF(PRICE_CONSUMER_PAID_EXC_SALES_TAX[0]::string REGEXP '\\\\d+(\\.\\\\d+)?', null, OBJECT_CONSTRUCT('FIELD', 'PRICE_CONSUMER_PAID_EXC_SALES_TAX', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU02', 'FIELD_VALUE', PRICE_CONSUMER_PAID_EXC_SALES_TAX, 'VIOLATION_TYPE', 'NOT_DECIMAL'))),
    IFF(PROMOTIONAL_ACTIVITY is null OR ARRAY_SIZE(PROMOTIONAL_ACTIVITY) <= 1, null, OBJECT_CONSTRUCT('FIELD', 'PROMOTIONAL_ACTIVITY', 'LINE_INDEX', LINE_INDEX::integer, 'RECORD_TYPE', 'SU02', 'FIELD_VALUE', PROMOTIONAL_ACTIVITY, 'VIOLATION_TYPE', 'HAS_MULTIPLE_ITEMS'))
  ) as VIOLATION_DETAILS
from %ENV%_DDEX_DSR.UNTYPED_BAP_MRB_11.SU02
where asset_id in (${assets}))
select asset_id, line_index::varchar as asset_part, concat_ws('::', RECORD_TYPE, GET_PATH(value, 'FIELD')::varchar, GET_PATH(value, 'VIOLATION_TYPE')::varchar) violation, value as violation_details from v, table(flatten(input => v.VIOLATION_DETAILS));`});


  $$
  ;

