use schema UNTYPED_AVP_MRB_10;

CREATE OR REPLACE TABLE HEAD (
  ASSET_ID  VARCHAR,
  LINE_INDEX VARCHAR,
  RECORD_TYPE ARRAY,
  MESSAGE_VERSION ARRAY,
  PROFILE ARRAY,
  PROFILE_VERSION ARRAY,
  MESSAGE_ID ARRAY,
  MESSAGE_CREATED_DATE_TIME ARRAY,
  FILE_NUMBER ARRAY,
  NUMBER_OF_FILES ARRAY,
  USAGE_START_DATE ARRAY,
  USAGE_END_DATE ARRAY,
  SENDER_PARTY_ID ARRAY,
  SENDER_NAME ARRAY,
  SERVICE_DESCRIPTION ARRAY,
  RECIPIENT_PARTY_ID ARRAY,
  RECIPIENT_NAME ARRAY,
  REPRESENTED_REPERTOIRE ARRAY,
  UNEXPECTED_DATA ARRAY);


CREATE OR REPLACE TABLE FOOT (
  ASSET_ID  VARCHAR,
  LINE_INDEX VARCHAR,
  RECORD_TYPE ARRAY,
  NUMBER_OF_LINES_IN_FILE ARRAY,
  NUMBER_OF_LINES_IN_REPORT ARRAY,
  NUMBER_OF_SUMMARY_RECORDS ARRAY,
  NUMBER_OF_BLOCKS_IN_FILE ARRAY,
  NUMBER_OF_BLOCKS_IN_REPORT ARRAY,
  UNEXPECTED_DATA ARRAY);


CREATE OR REPLACE TABLE SY04_01 (
  ASSET_ID  VARCHAR,
  LINE_INDEX VARCHAR,
  RECORD_TYPE ARRAY,
  SUMMARY_RECORD_ID ARRAY,
  DISTRIBUTION_CHANNEL ARRAY,
  DISTRIBUTION_CHANNEL_DPID ARRAY,
  COMMERCIAL_MODEL ARRAY,
  USE_TYPE ARRAY,
  TERRITORY ARRAY,
  SERVICE_DESCRIPTION ARRAY,
  SUBSCRIBER_TYPE ARRAY,
  SUBSCRIBERS ARRAY,
  SUB_PERIOD_START_DATE ARRAY,
  SUB_PERIOD_END_DATE ARRAY,
  USAGES_IN_SUB_PERIOD ARRAY,
  USAGES_IN_REPORTING_PERIOD ARRAY,
  CURRENCY_OF_REPORTING ARRAY,
  CURRENCY_OF_TRANSACTION ARRAY,
  EXCHANGE_RATE ARRAY,
  CONSUMER_PAID_UNIT_PRICE ARRAY,
  NET_REVENUE ARRAY,
  MUSIC_USAGE_PERCENTAGE ARRAY,
  UNEXPECTED_DATA ARRAY);


CREATE OR REPLACE TABLE RE03 (
  ASSET_ID  VARCHAR,
  LINE_INDEX VARCHAR,
  RECORD_TYPE ARRAY,
  BLOCK_ID ARRAY,
  RELEASE_REFERENCE ARRAY,
  DSP_RELEASE_ID ARRAY,
  PROPRIETARY_RELEASE_ID ARRAY,
  ICPN ARRAY,
  TITLE ARRAY,
  SUB_TITLE ARRAY,
  SERIES_TITLE ARRAY,
  SEASON_NUMBER ARRAY,
  DISPLAY_ARTIST_NAME ARRAY,
  DISPLAY_ARTIST_PARTY_ID ARRAY,
  RELEASE_TYPE ARRAY,
  DATA_PROVIDER_NAME ARRAY,
  UNEXPECTED_DATA ARRAY);


CREATE OR REPLACE TABLE AS03 (
  ASSET_ID  VARCHAR,
  LINE_INDEX VARCHAR,
  RECORD_TYPE ARRAY,
  BLOCK_ID ARRAY,
  RESOURCE_REFERENCE ARRAY,
  DSP_RESOURCE_ID ARRAY,
  ISAN ARRAY,
  EIDR ARRAY,
  PROPRIETARY_ID ARRAY,
  VIDEO_TYPE ARRAY,
  TITLE ARRAY,
  SUB_TITLE ARRAY,
  ORIGINAL_TITLE ARRAY,
  SEASON_NUMBER ARRAY,
  EPISODE_NUMBER ARRAY,
  GENRE ARRAY,
  DURATION ARRAY,
  PRODUCER_NAME ARRAY,
  PRODUCER_PARTY_ID ARRAY,
  DIRECTOR_NAME ARRAY,
  DIRECTOR_PARTY_ID ARRAY,
  ACTOR_NAME ARRAY,
  ACTOR_PARTY_ID ARRAY,
  LANGUAGE_LOCALIZATION_TYPE ARRAY,
  HAS_CAPTIONING ARRAY,
  HAS_AUDIO_DESCRIPTION ARRAY,
  LANGUAGE_OF_PERFORMANCE ARRAY,
  LANGUAGE_OF_DUBBING ARRAY,
  PRODUCTION_OR_RELEASE_DATE ARRAY,
  COUNTRY_OF_PRODUCTION ARRAY,
  UNEXPECTED_DATA ARRAY);


CREATE OR REPLACE TABLE SU03_01 (
  ASSET_ID  VARCHAR,
  LINE_INDEX VARCHAR,
  RECORD_TYPE ARRAY,
  BLOCK_ID ARRAY,
  SALES_TRANSACTION_ID ARRAY,
  SUMMARY_RECORD_ID ARRAY,
  DSP_RESOURCE_ID ARRAY,
  USAGES ARRAY,
  NET_REVENUE ARRAY,
  VALIDITY_PERIOD_START ARRAY,
  VALIDITY_PERIOD_END ARRAY,
  UNEXPECTED_DATA ARRAY);


CREATE OR REPLACE TABLE UNEXPECTED_RECORD (
  ASSET_ID  VARCHAR,
  LINE_INDEX VARCHAR,
  UNEXPECTED_DATA ARRAY);


