CREATE DATABASE IF NOT EXISTS {{ENV_NAME}}_DDEX_DSR;
USE DATABASE {{ENV_NAME}}_CCID;
CREATE SCHEMA IF NOT EXISTS {{TYPED_SCHEMA}};
CREATE SCHEMA IF NOT EXISTS {{UNTYPED_SCHEMA}};
CREATE SCHEMA IF NOT EXISTS {{VALIDATION_SCHEMA}};
CREATE SCHEMA IF NOT EXISTS {{PUBLISHED_SCHEMA}};